### ISSUE TITLE
BUG in gost.dll

### ISSUE THREAD

**Issue by WarlordXXX** [gost-engine/engine#104]
When decrypt and extracted signed data with a gost.dll - data include additional "\r" symbols, this is BUG. The attachment file "X0000000.XXX.sig" contain decrypted signed data as example. If extract data from example file then extracted data will be included additional "\r" symbols - what is not correct.
[X0000000.XXX.sig.zip](https://github.com/gost-engine/engine/files/2759529/X0000000.XXX.sig.zip)

OS: Windows 7 64-bit
OpenSSL 1.1.1a 32-bit

**Comment by beldmit** [comment]
Could you please write all the operations you did?

**Comment by WarlordXXX** [comment]
> Could you please write all the operations you did to get this result?

1. openssl cms -decrypt -engine gost -inform DER -in "X0000000.XXX.sig.enc" -recip "Key.key" -out "X0000000.XXX.sig"
After execute X0000000.XXX.sig is Base64 signeddata, but included additional "\r" symbols.
2. X0000000.XXX.sig decode from Base64 to DER.
3. openssl cms -engine gost -verify -inform DER -in "X0000000.XXX.sig" -noverify -signer "X0000000.XXX.signer.cer" -out "X0000000.XXX"
After execute X0000000.XXX included additional "\r" symbols - what is not correct.

You can execute step 2 and 3 on the X0000000.XXX.sig to get result...

**Comment by beldmit** [comment]
Could you check it with non-gost keys? I do not remember any BIO operations in the gost engine code.

**Comment by WarlordXXX** [comment]
Well, i cheked it with non-gost key in openssl versions 1.1.1a and 1.1.0g - decrypted out file include additional "\r" symbols :(

**Comment by beldmit** [comment]
If I remember correctly, this is intended behavior, so you'd better ask about it at openssl-users@
