### ISSUE TITLE
Kuznechik-CTRACPKM and Magma-CTRACPKM

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#112]
It makes sense to have separate instances of Kuznechik/Magma ciphers in CTR-ACPKM modes with IV length 8/4 bytes respectively to match TLS specification. It will minimize the modification of openssl code mentioning the GOST cipher NIDs.

**Comment by vt-alt** [comment]
Я думаю, может можно как-то сигнализировать шифру с какой длиной `iv` работать для `ctr`. Все таки openssh это исключительный случай. Может быть для него можно сделать отдельный `ctrl` позволяющий установить полный `iv`.

ps. Релевантный код tls для reference: https://github.com/openssl/openssl/commit/7573c2f7aa0e8427c59fed5b0a46e652c3bd39bb

**Comment by beldmit** [comment]
Прибил гвоздями половинную длину. По стандарту и по разъяснениям КриптоПро иной модели использования не предусмотрено.
