### ISSUE TITLE
ASan tests for Travis-CI

### ISSUE THREAD

**Issue by vt-alt** [gost-engine/engine#116]
Problem is, it's hard to make engine (perl) test to work, because `openssl` binary doing `dlopen` to `gost.so`, which would be built with ASan, and that produces all sorts of weird errors.

Just to note command to build with ASan:
```
cmake -DOPENSSL_ROOT_DIR=...... -DCMAKE_C_FLAGS="-fsanitize=address -fno-omit-frame-pointer -g3"  ..
```
Also for openssl build:
```
./config -d ......
```

**Comment by beldmit** [comment]
Seems to be implemented?

**Comment by vt-alt** [comment]
Да. Но как заставить perl тесты с ним работать я не знаю. Так что можно считать это задание выполненным для C тестов.
