### ISSUE TITLE
Support for IANA GOST-chiphersuites for TLS 1.2

### ISSUE THREAD

**Issue by amdei** [gost-engine/engine#118]
IANA have included public identifiers for GOST-chiphersuites into their registry:
https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-4
While usage of old identifiers from private space will be continued, it is necessary to support new ones.

ID | Name| N | N | Reference
-- | -- | -- | -- | --
0xC1,0x00 | TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC | N | N | [draft-smyshlyaev-tls12-gost-suites]
0xC1,0x01 | TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC | N | N | [draft-smyshlyaev-tls12-gost-suites]
0xC1,0x02 | TLS_GOSTR341112_256_WITH_28147_CNT_IMIT | N | N | [draft-smyshlyaev-tls12-gost-suites]

**Comment by beldmit** [comment]
Has nothing to do with the engine itself.  Will be supported in OpenSSL.
