### ISSUE TITLE
Проблемы со сборкой на Ubuntu 16.04

### ISSUE THREAD

**Issue by sholkyman** [gost-engine/engine#129]
ubuntu server 16.04
cmake version 3.5.1
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)
OpenSSL 1.1.1b  26 Feb 2019

При выполнении `cmake --build . --config Release` возникают ошибки компиляции:

`cc1: all warnings being treated as errors
CMakeFiles/gost_engine.dir/build.make:326: recipe for target 'CMakeFiles/gost_engine.dir/gost_pmeth.c.o' failed
make[2]: *** [CMakeFiles/gost_engine.dir/gost_pmeth.c.o] Error 1
CMakeFiles/Makefile2:173: recipe for target 'CMakeFiles/gost_engine.dir/all' failed
make[1]: *** [CMakeFiles/gost_engine.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2`

Прикладываю файл с полным логом.
[log.txt](https://github.com/gost-engine/engine/files/3053200/log.txt)
 
Чего не хватает?

**Comment by beldmit** [comment]
Не надо брать ветку master. Возьмите 1_1_0

**Comment by sholkyman** [comment]
Спасибо за оперативность. Сборка прошла без ошибок.
Теперь пробую `cmake --build . --target install --config Release`
и получаю ошибку
`make: *** No rule to make target 'install'.  Stop.`

**Comment by sholkyman** [comment]
Нужно было вместо `install` указать `all`:
```
cmake --build . --target all --config Release
[ 40%] Built target gost
[ 46%] Built target gostsum
[ 86%] Built target gost_engine
[ 93%] Built target test_grasshopper
[100%] Built target gost12sum
```

Проверяю:
```
openssl version -e
ENGINESDIR: "/usr/local/ssl/lib/engines-1.1"
```

Но в директории `/usr/local/ssl/lib/engines-1.1` отсутствует файл `gost.so`
При сборке, разумеется, я указывал этот и другие свои пути в `DOPENSSL_ROOT_DIR`, `DOPENSSL_LIBRARIES` и `DOPENSSL_ENGINES_DIR`

**Comment by beldmit** [comment]
А цели install там с шансами нет. Копировать руками. 
Вообще в Debian, RedHat (fc30) и Alt есть пакеты, и лучше бы пользоваться ими, сбекпортив по необходимости.

**Comment by sholkyman** [comment]
Не понял фразы "А цели install там с шансами нет." какими шансами?)

Подскажите где найти рабочий пакет для debian?

**Comment by beldmit** [comment]
https://packages.debian.org/sid/libengine-gost-openssl1.1

Я не помню, прописана ли эта цель в CMakeLists.
