### ISSUE TITLE
Некорректный расчет хеша по ГОСТ Р 34.11-94

### ISSUE THREAD

**Issue by Grundik** [gost-engine/engine#142]
```
$ openssl version
OpenSSL 1.1.1b  26 Feb 2019
$ openssl engine gost -c
(gost) Reference implementation of GOST engine
 [gost89, gost89-cnt, gost89-cnt-12, gost89-cbc, grasshopper-ecb, grasshopper-cbc, grasshopper-cfb, grasshopper-ofb, grasshopper-ctr, md_gost94, gost-mac, md_gost12_256, md_gost12_512, gost-mac-12, gost2001, gost-mac, gost2012_256, gost2012_512, gost-mac-12]
```
К сожалению не знаю как вывести версию именно движка. Версия пакета libengine-gost-openssl1.1 — 1.1.0.3-1, Debian sid.

```
$ echo -n | openssl dgst -engine gost -md_gost94
engine "gost" set.
(stdin)= 3f25bc1fbbce27ca10fb1958f319473ae7e17482c3b53ecf47a7e2de8aabe4c8
```
Однако для пустой строки хеш должен быть 981e5f3ca30c841487830f84fb433e13ac1101569b9c13584ac483234cd656c0. Такой неправильный результат был в #79, т.е. проблема не новая.

Других случаев ошибочного расчета пока не нашел, например для такой строки результат верный:
```
$ echo -n 1234567 | openssl dgst -engine gost -md_gost94
engine "gost" set.
(stdin)= ac6c8db95769043e2a42833ed7bbd29542f923eabd57b5f5aa28f3f3238fd850
```

**Comment by beldmit** [comment]
Будет патч - я его приму, но так как алгоритм уже уходящий, а случай вырожденный, то я особого смысла в этом не вижу.

**Comment by Grundik** [comment]
Вопрос в том, действительно ли это конкретно один случай такой, или же есть какие-то общие условия когда такая проблема проявляется, а это лишь один из возможных примеров.

Я пока не копал код, почему так получается, но, т.к. без понимания масштаба проблемы пользоваться этим алгоритмом совсем нельзя, попробую разобраться как будет время.

**Comment by beldmit** [comment]
Проблема именно с пустой строкой для ГОСТа 94 года была. Деталей не помню.

**Comment by Grundik** [comment]
Там зачем-то лишний раз вызывается hash_step в таком случае. Убрал, и хеш стал корректным. Надеюсь не пропустил какую-то идею, заложенную в этом вызове.

**Comment by vt-alt** [comment]
См. #143#issuecomment-495804502

**Comment by Grundik** [comment]
Продолжил дискуссию там

**Comment by beldmit** [comment]
Закрываю ввиду малой практической значимости.
