### ISSUE TITLE
запуск тестов из папки "test" в рамках CI

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#148]
привет,

в этом комите https://github.com/gost-engine/engine/commit/97430ebfe8d60932f3da76e43fd8a297579f1030#diff-354f30a63fb0907d4ad57269548329e3 зачем-то выпилили запуск тестов из папки "test"

но при этом @abbra  зачем-то притащил Test2::V0 вот тут https://github.com/gost-engine/engine/commit/90c34c7c32fc226e5e8c8f127bdb6b522d7f0de7#diff-354f30a63fb0907d4ad57269548329e3

предложение такое - подумать, нужны ли тесты, если да - вернуть. если нет - выпилить остатки, в т.ч. Test2::V0

**Comment by beldmit** [comment]
Make test их запускает и они нужны. Другой вопрос, что их мало и на новый функционал я в процессе отладки обычно пишу что-то низкоуровневое на C.

Test2::V0 есть в Ubuntu и бекпортах для Debian. Я его вчера поставил.

**Comment by chipitsine** [comment]
пардон. проверю еще

**Comment by beldmit** [comment]
Вроде всё работает, закрываю.
