### ISSUE TITLE
Пожалуйста добавьте поддержку для экспорта/импорта 512 битных ключей КриптоПро

### ISSUE THREAD

**Issue by hackomatic** [gost-engine/engine#157]
gost-engine содержит код для расшифровки блоба экспортированного закрытого ключа КриптоПро, однако поддерживается только блоб размером 44 байта (ukm[8] + key[32] + 4 байта имитозащита):
https://github.com/gost-engine/engine/blob/master/gost_keywrap.c

Для эксперимента я модифицировал пример EncryptKey из КриптоПро SDK и сделал дамп ASN1 экспортированного блоба закрытого ключа без заголовка и он полностью соответствует RFC 4357, при этом блоб для 512 битного ключа отличается только длиной элемента самого ключа (ukm[8] + key[64] + 4 байта имитозащита).

**Comment by beldmit** [comment]
Можете подробнее описать, для каких протоколов требуется эта поддержка?

**Comment by hackomatic** [comment]
У вас уже реализована поддержка для ключей 256 бит, нужно просто добавить поддержку для 512 бит, чтобы иметь возможность импортировать и экспортировать закрытые ключи этой длины.

**Comment by beldmit** [comment]
Вы не ответили на мой вопрос.

**Comment by hackomatic** [comment]
Прошу прощения, видимо мне непонятен Ваш вопрос. Вы спрашиваете где используется поддержка для 512 битных ключей? Ответ как мне кажется очевиден: там же, где и поддержка для 256 битных ключей, которая уже есть - для экспорта/импорта закрытого ключа в блобе, поддерживаемом КриптоПро. Или Вы справшиваете для чего в gost-engine код в gost_keywrap.c?

**Comment by beldmit** [comment]
Да. Вот этот экспорт используется в TLS, причём он универсальный для битности ключей по спецификациям, и в CMS (тоже универсальный). 

Если есть функциональность, для которой экспорта текущего не хватает, я могу это добавить. Но если таковой нет, то смысла пока не вижу.

**Comment by hackomatic** [comment]
Мне хотелось бы иметь возможность импортировать закрытые ключи КриптоПро с помощью gost-engine. Импорт 256-битных ключей есть, но поддержки для 512-битных ключей нет. Я понимаю, что в RFC не описывается формат блоба для 512-битных ключей, однако есть де-факто реализация КриптоПро, которая это умеет делать, и было бы логично, чтобы gost-engine это тоже умел делать.

**Comment by beldmit** [comment]
Я готов принять патч с добавлением этой функциональности, но самому времени на это у меня сейчас нет :(

**Comment by beldmit** [comment]
Функциональность добавлена некоторое время назад в мастер-ветку. Спасибо @vt-alt

**Comment by hackomatic** [comment]
Спасибо!

**Comment by hackomatic** [comment]
> Функциональность добавлена некоторое время назад в мастер-ветку. Спасибо @vt-alt

Дмитрий, я не могу найти соответствующего кода в gost-engine, можете указать на коммит?

Для анализа и сравнения, посмотрите пожалуйста на мой код для расшифровки блоба закрытого ключа КриптоПро в аналоге P12FromGostCSP от Etersoft: https://github.com/Etersoft/p12export

**Comment by beldmit** [comment]
Коммиты
486cd1d88be05434966105074afedf1b1e32314c
eaf0efe8098a2a3701f469d777ec1fd2e00574b1
1c8b7f9a2a51ba2a6d668c2cd4e4672ed6731166

**Comment by vt-alt** [comment]
> Для анализа и сравнения, посмотрите пожалуйста на мой код для расшифровки блоба закрытого ключа КриптоПро в аналоге P12FromGostCSP от Etersoft: https://github.com/Etersoft/p12export

@hackomatic Нужно искать этот код?

Тест на конвертацию *ключей* в PEM и обратно, в DER и обратно есть в `test_sign.c` в `test_sign()`, то же самое для *сертификатов* есть в `test_params.c` в `test_cert()`.

ccacae62bbe1f1dd695bc8f94ea8c2e603d86ce7
1f05588788bf45f84a9794eb57cd3dfdebee140a

**Comment by vt-alt** [comment]
Я что-то посмотрел, у вас используется:
* `i2d_PKCS12_fp`, `d2i_PKCS12_fp` - такого теста у меня нет.
* `d2i_X509` и `d2i_ASN1_SEQUENCE_ANY` есть в test_params.c
* `d2i_GOST_KEY_TRANSPORT_PRO` это я не знаю что такое.

**Comment by hackomatic** [comment]
> > Для анализа и сравнения, посмотрите пожалуйста на мой код для расшифровки блоба закрытого ключа КриптоПро в аналоге P12FromGostCSP от Etersoft: https://github.com/Etersoft/p12export
> 
> @hackomatic Нужно искать этот код?

key_unwrap_2012:
https://github.com/Etersoft/p12export/blob/master/p12export/p12export.c#L337
key_unwrap_2001:
https://github.com/Etersoft/p12export/blob/master/p12export/p12export.c#L359

> Я что-то посмотрел, у вас используется:
> 
>     * `i2d_PKCS12_fp`, `d2i_PKCS12_fp` - такого теста у меня нет.
> 
>     * `d2i_X509` и `d2i_ASN1_SEQUENCE_ANY` есть в test_params.c
> 
>     * `d2i_GOST_KEY_TRANSPORT_PRO` это я не знаю что такое.

d2i_GOST_KEY_TRANSPORT_PRO - это формат блоба зашифрованного ключа, который отдает КриптоПро (CALG_PRO12_EXPORT), ASN1 структуры для него находятся в
https://github.com/Etersoft/p12export/blob/master/p12export/gost_asn1_pro.c
https://github.com/Etersoft/p12export/blob/master/p12export/gost_asn1_pro.h

**Comment by vt-alt** [comment]
Спасибо. Ясно. Я почему-то глюкнул и подумал, что вы говорите про тесты экспорта/импорта. Сорян. Сам фунционал, по-моему, есть ещё с 2019. Собственно, тесты для все видов ключей это подтверждают.

**Comment by hackomatic** [comment]
> Спасибо. Ясно. Я почему-то глюкнул и подумал, что вы говорите про тесты экспорта/импорта. Сорян. Сам фунционал, по-моему, есть ещё с 2019. Собственно, тесты для все видов ключей это подтверждают.

Безусловно, функционал для расшифровки весь есть, большое спасибо. Чего нет - это поддержки формата блоба CALG_PRO12_EXPORT и нужно было вдумчиво почитать спецификации ТК26. Если есть желание добавить расшифровку CALG_PRO12_EXPORT в gost-engine - можете использовать мой код.
