### ISSUE TITLE
Compilation manual?

### ISSUE THREAD

**Issue by rkfg** [gost-engine/engine#16]
The engine fails to compile on OpenSSL 1.1.0. I know it isn't released yet but I need GOST 34.10-2012 because -2001 is deprecated by now. There are several issues with opaque data structures, I hacked my way around it with this patch:
```diff
diff --git a/Makefile b/Makefile
index 95014cb..0c906e0 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 DIR=ccgost
 TOP=../..
 CC=cc
-INCLUDES= -I../../include
+INCLUDES= -I../../include -I../../crypto/include
 CFLAG=-g
 MAKEFILE= Makefile
 AR= ar r
diff --git a/gost_ameth.c b/gost_ameth.c
index 8a9cd28..2336787 100644
--- a/gost_ameth.c
+++ b/gost_ameth.c
@@ -18,6 +18,7 @@
 #endif
 #include "gost_lcl.h"
 #include "e_gost_err.h"
+#include <internal/evp_int.h>
 
 /*
  * Pack bignum into byte buffer of given size, filling all leading bytes by
diff --git a/gost_lcl.h b/gost_lcl.h
index a82362f..945ca48 100644
--- a/gost_lcl.h
+++ b/gost_lcl.h
@@ -35,6 +35,11 @@ typedef struct R3410_ec {
     char *y;
 } R3410_ec_params;
 
+struct DSA_SIG_st {
+    BIGNUM *r;
+    BIGNUM *s;
+};
+
 extern R3410_ec_params R3410_2001_paramset[],
     *R3410_2012_256_paramset, R3410_2012_512_paramset[];
```
It's by no means proper but at least I can compile from the openssl_1_1_0 branch. Master has much more issues so I gave up on it. Still, `make` produces this:
```
(cd ../..; make DIRS=engines sub_all)
make[1]: Entering directory '/home/rkfg/soft/openssl'
make[1]: *** No rule to make target 'sub_all'.  Stop.
make[1]: Leaving directory '/home/rkfg/soft/openssl'
Makefile:20: recipe for target 'top' failed
make: *** [top] Error 2
```
Indeed, there are no such targets. `make lib` only touches the `lib` file and does nothing else. Basically, I have a bunch of object files but no shared library to use.

I don't know how the engine directory should be named so I chose ccgost as it was named before. OpenSSL (branch is OpenSSL_1_1_0-pre4) itself doesn't seem to compile the engine by default even with `enable-shared` option. I can compile OpenSSL without problems but gost-engine gives me headaches.

**Comment by beldmit** [comment]
Well, now you can build the engine as drop-in replacement of the one in 1.0.2 branch. The necessary patches are available. 

But yes, it's a problem to compile the engine against the 1.1.0 version because of the opaquization of many internal structures. It's a bad idea to #include internal header instead of using the accessors. And yes, it's necessary to create the new build mechanism (automake, cmake?).  The patches are welcome.

**Comment by rkfg** [comment]
Hmm, will give it a try, thanks. For DSS I haven't found any setters, only a getter is available so the only solution I could use without hacking OpenSSL itself is to provide the structure. And going into ASN.1 internals would be even harder. Making it work on 1.0.2 is pretty sufficient for me.

**Comment by rkfg** [comment]
It seems I succeeded at compiling it with patches for 1.0.2, thanks again. The patches need patches though (sound funny, yeah): [this diff](https://github.com/gost-engine/engine/blob/master/patches/1.0.2/cipher_modes.diff) doesn't have a leading prefix component so it must be applied with `patch -p0` while all others have it and thus are applied with `patch -p1`. Trivial fix.

**Comment by levitte** [comment]
That patch is the wrong solution.  Use `DSA_SIG_get0` to get the BIGNUMs (`perldoc doc/crypto/DSA_SIG_new.pod` in the OpenSSL source).

**Comment by rkfg** [comment]
It was not a patch but a mere workaround to get it compiled. DSA_SIG_get0 can be used to *get* the fields but surprisingly there's no function to *set* them which is being done there.

Nevermind, I successfully used the engine on OpenSSL 1.0.2 with patches so I guess this should be closed.

**Comment by levitte** [comment]
From the manual page:

    DSA_SIG_get0() returns internal pointers the r and s values contained in
    sig. The values can then be examined *or initialised*.

**Comment by beldmit** [comment]
I've committed the fix to the 1_1_0 branch but still now I do not have a relevant way to make the engine.
