### ISSUE TITLE
test_grasshopper OMAC fails on openssl/master

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#163]
Not sure if it's similar to #151. MacOS Mojave 10.14.6, Xcode-10.3, current OpenSSL master, current GOST engine master.

I'm not getting any error messages besides this:
```
$ build/bin/test_grasshopper
. . . . .
# Tests for omac
OMAC test from GOST R 34.13-2015
Resize result size from 16 to 8
  MAC[16] =  336f4d296059fbe34ddeb35b37749c67
Test FAILED
. . . . .
```
All the other tests pass.

### Update
Somehow, the mac does **not** get resized, as you can see if you add debugging output to `test_mac()` around lines 357 etc.:
```
    EVP_MD_CTX_free(ctx);
    printf("  MAC[%2u] = ", md_len);
    hexdump(md_value, md_len);
    printf("  exp[%2lu] = ", mac_size);
    hexdump(mac, mac_size);
```
and then observe
```
$ bin/test_grasshopper
. . . . .
# Tests for omac
OMAC test from GOST R 34.13-2015
Resize result size from 16 to 8
  MAC[16] =  336f4d296059fbe34ddeb35b37749c67
  exp[ 8] =  336f4d296059fbe3
Test FAILED
. . . . .
```

With OpenSSL-1.1.1c everything works fine.

**Comment by levitte** [comment]
This may be an OpenSSL error, actually.  We're doing some very deep replumbing, and it's possible we've lost some details...

**Comment by levitte** [comment]
Hmmm, I'm having zero problem, running this command:

```
: ; ENGINE_DIR=./bin LD_LIBRARY_PATH=~/.private-install/opt/openssl-3.0/lib/ ./build/bin/test_grasshopper 
...
= All tests passed!
```

.... and just so we don't fight stoopidly over versions:

```
: ; ENGINE_DIR=./bin LD_LIBRARY_PATH=~/.private-install/opt/openssl-3.0/lib/ ldd ./build/bin/test_grasshopper 
	linux-vdso.so.1 (0x00007ffe8ebcc000)
	gost.so.. => /home/levitte/gitwrk/github.com/gost-engine/build/bin/gost.so.. (0x00007f94be042000)
	libcrypto.so.3 => /home/levitte/.private-install/opt/openssl-3.0/lib/libcrypto.so.3 (0x00007f94bdc93000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f94bda7a000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f94bda75000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94bda54000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f94be0a2000)
```

(what I wonder, thought, is *why* the *hell* test_grasshopper is linked with `gost.so`.  That's incredibly wrong...  but shouldn't matter performance wise)

**Comment by levitte** [comment]
Is your openssl 3 build up to date?

**Comment by levitte** [comment]
In #146, you said that `EVP_DigestFinal_ex()` uses (or at least returns) the wrong size.  Sounds like you may have found a bug there.  Would you mind debugging it and looking at what happens with `mdsize`?  That's the governing local variable...

**Comment by beldmit** [comment]
Comparing the `dtruss` logs via `vimdiff`, I see some stuff that seems significant to me.

First, the `~` is not expanded in the successful case. So the config is actually not loaded.

Then, the path to the engine in the failing case is 
```/Users/ur20980/openssl-3/lib/engines-3/gost.dylib```

and in the successful it is
```/Users/ur20980/src/grasshopper-engine/build/bin/gost.dylib```

which seem different.

I usually use explicit dynamic_path to ensure that the engine is loaded.

**Comment by beldmit** [comment]
In the file `s2-g-out.txt` I see that you did not succeed  to load the specified config file:

```
12579/0x31082d:  open_nocancel("/Users/ur20980/src/openssl/openssl-3.cnf\0", 0x0, 0x1B6)     = -1 Err#2
```

There can be, though, a problem related to loading the engine twice but I suspect some strange mismatch between library and engine.

**Comment by beldmit** [comment]
> I think it is happening, because I was getting so many "GOST engine already loaded" messages that they were breaking my scripts, so I suppressed it. Is it possible to avoid/remedy this problem?

Well, if this message appears, it means something inconsistent in your scripts. I can't imagine a reason to load the engine twice.

**Comment by levitte** [comment]
> Well, if this message appears, it means something inconsistent in your scripts. I can't imagine a reason to load the engine twice.

I can.  If `OPENSSL_CONF` is defined and has the config for gost, and `-engine gost` is specified at the same time...

Something to know about OpenSSL 3 is that it *always* loads the config file.

**Comment by beldmit** [comment]
> > Well, if this message appears, it means something inconsistent in your scripts. I can't imagine a reason to load the engine twice.
> 
> I can. If `OPENSSL_CONF` is defined and has the config for gost, and `-engine gost` is specified at the same time...

I mean not a technical reason, but an intention. For me, it looks like the `-engine gost` is unnecessary and should be removed. 
 
> Something to know about OpenSSL 3 is that it _always_ loads the config file.

As far as I understand, as the config file is loaded, the list of available algorithms is fixed, and not all applications (I mean openssl-*) will be able to pick them from the engine loaded via the -engine cmdline key.

**Comment by beldmit** [comment]
BTW, @levitte, what is the best way to deal with a try to load engine twice? I currently return an error from bind_gost, but is it the best option?

**Comment by levitte** [comment]
> I mean not a technical reason, but an intention. For me, it looks like the `-engine gost` is unnecessary and should be removed.

That's entirely your choice.  Basically, you can do one or the other, but not both, at least safely.

**Comment by levitte** [comment]
> BTW, @levitte, what is the best way to deal with a try to load engine twice? I currently return an error from bind_gost, but is it the best option?

That's a fairly normal think to do.  We don't do any explicit check in the OpenSSL engines, but rely on the diverse `ENGINE_set_` functions to return an error if they can't deal with the new engine for whatever reason.

**Comment by beldmit** [comment]
> ```
> engine_id = gost
> default_algorithms = ALL
> CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet
> PBE_PARAMS = "gost12_512"
> ```

AFAIR, default_algorithms is unnecessary at all. 
CRYPT_PARAMS is used for PKCS#7 (selection of gost89 params on encryption).
PBE_PARAMS is used during PKCS#12 creation.

**Comment by beldmit** [comment]
AFAIR, there are some reasonable defaults for these variables.

**Comment by mouse07410** [comment]
More of similar traces. They show that if an empty config is given, engine is loaded from the `build/bin` directory, and all is well. If the real (and correct!) config is given, the engine is loaded from `~/openssl-3/lib/engines-3` directory, and `EVP_DigestFinal_ex()` malfunctions by ignoring `mac_size`.
[no-good-out.txt](https://github.com/gost-engine/engine/files/3557304/no-good-out.txt)
[good-out.txt](https://github.com/gost-engine/engine/files/3557305/good-out.txt)

**Comment by beldmit** [comment]
Here is the initialization of the failing test:

https://github.com/gost-engine/engine/blob/master/test_grasshopper.c#L371-L377

This block was added when the test became incompatible with the OpenSSL master branch, see 
https://github.com/gost-engine/engine/commit/034066376d4b3743368a5907d2cbec20983af3e0

Maybe it should be fixed another way.

**Comment by mouse07410** [comment]
I question this line: https://github.com/gost-engine/engine/blob/ecad16119a101a1f1947a80e9f630ac2dc2c2794/test_grasshopper.c#L377

At the very least, `RAND_bytes()` shouldn't default to the GOST engine, IMHO. 
@beldmit  @levitte what do you think?

**Comment by beldmit** [comment]
I think that as the engine does not provide its own RAND_METHOD or anything similar, this command should not interfere with randomness. If it does, it means that the behavior has changed here between 1.1.1 and 3.

**Comment by mouse07410** [comment]
OK, that makes sense (and I have no evidence that it interferes with randomness).

 And this `EVP_DigestFinal_ex()` issue is weird. Doesn't happen on 1.1.1...

**Comment by mouse07410** [comment]
I added debugging printout to `test_grasshopper.c`:
```
	printf("Resize result size from %d to %zu (mdsize=%d)\n", 
		EVP_MD_CTX_size(ctx), mac_size, EVP_MD_size(EVP_MD_CTX_md(ctx)));
	T(EVP_MD_meth_set_result_size((EVP_MD *)EVP_MD_CTX_md(ctx), mac_size));
    }
    T(EVP_MD_meth_get_ctrl(EVP_MD_CTX_md(ctx))(ctx, EVP_MD_CTRL_SET_KEY, sizeof(K), (void *)K));
    if (acpkm)
	T(EVP_MD_meth_get_ctrl(EVP_MD_CTX_md(ctx))(ctx,
                EVP_CTRL_KEY_MESH, acpkm, acpkm_t ? &acpkm_t : NULL));
    T(EVP_DigestUpdate(ctx, pt, pt_size));
    printf("Right before EVP_DigestFinal_ex() mdsize=%d\n", EVP_MD_size(EVP_MD_CTX_md(ctx)));
    T(EVP_DigestFinal_ex(ctx, md_value, &md_len));
    EVP_MD_CTX_free(ctx);
    printf("  MAC[%u] = ", md_len);
    hexdump(md_value, md_len);
```

Here's the output:
```
. . . . .
7: OMAC test from GOST R 34.13-2015
7: Resize result size from 16 to 8 (mdsize=16)
7: Right before EVP_DigestFinal_ex() mdsize=8
7:   MAC[16] =  336f4d296059fbe34ddeb35b37749c67
7: Test FAILED
. . . . .
```

The responsible code in OpenSSL master is https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L316-L337

@levitte what do you make of this?
@beldmit is it possible that the GOST engine somehow does not respect the `mdsize` value passed to it? Where would one look for OMAC?

**Comment by beldmit** [comment]
Finally caught. 

Here we go to a legacy branch (as gost engine is not a provider yet). And a result size is set to the default value for the tested OMAC, ignoring the one present in the legacy context.

So it's time to change the engine to a provider, isn't it?

**Comment by mouse07410** [comment]
> ...And a result size is set to the default value for the tested OMAC...

You mean this: https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L341-L345

So 
https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L343 
uses the default value, while 
https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L326 
uses the provided `mdsize`? 

But what about https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L345 ? It appears to use the value for `mdsize` that we set, so why isn't it what we expect to be?

**Comment by beldmit** [comment]
> > ...And a result size is set to the default value for the tested OMAC...
> 
> You mean this: https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L341-L345

Yes.

> So
> https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L343
> uses the default value, 

No. In case of this OMAC it uses a full length. Then it should be truncated according to the actual.

> while  https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L326
> uses the provided `mdsize`?

This string just takes a default value.


> But what about https://github.com/openssl/openssl/blob/5ffc33244cd4d66e47dfa66ce89cb38d0f3074cc/crypto/evp/digest.c#L345 ? It appears to use the value for `mdsize` that we set, so why isn't it what we expect to be?

This is a default value, taken from the EVP_MD object, not from the EVP_MD_CTX one.

> Also, how does `OPENSSL_CONF="" build/bin/test_grasshopper` manage to avoid this pitfall?

No idea yet.

**Comment by mouse07410** [comment]
> ...it uses a full length. Then it should be truncated according to the actual length set in the context. 

OK. What entity performs the truncation?

> This is a default value, taken from the `EVP_MD` object, not from the `EVP_MD_CTX` one

I hear you, but what about this:
```
# Tests for omac
OMAC test from GOST R 34.13-2015
Resize result size from 16 to 8 (mdsize=16)
Right before EVP_DigestFinal_ex() md_ctx_size=8 mdsize=8
  MAC[16] =  336f4d296059fbe34ddeb35b37749c67
Test FAILED
```
produced by
```
   T(EVP_DigestUpdate(ctx, pt, pt_size));
    printf("Right before EVP_DigestFinal_ex() md_ctx_size=%d mdsize=%d\n",
        EVP_MD_CTX_size(ctx), EVP_MD_size(EVP_MD_CTX_md(ctx)));
    T(EVP_DigestFinal_ex(ctx, md_value, &md_len));
    EVP_MD_CTX_free(ctx);
    printf("  MAC[%u] = ", md_len);
    hexdump(md_value, md_len);
```

**Comment by beldmit** [comment]
> > ...it uses a full length. Then it should be truncated according to the actual length set in the context.
> 
> OK. What entity performs the truncation?

The output size is set and should not be overwritten, but it is.

> 
> > This is a default value, taken from the `EVP_MD` object, not from the `EVP_MD_CTX` one
> 
> I hear you, but what about this:
> 
> ```
> # Tests for omac
> OMAC test from GOST R 34.13-2015
> Resize result size from 16 to 8 (mdsize=16)
> Right before EVP_DigestFinal_ex() md_ctx_size=8 mdsize=8
>   MAC[16] =  336f4d296059fbe34ddeb35b37749c67
> Test FAILED
> ```
> 
> produced by
> 
> ```
>    T(EVP_DigestUpdate(ctx, pt, pt_size));
>     printf("Right before EVP_DigestFinal_ex() md_ctx_size=%d mdsize=%d\n",
>         EVP_MD_CTX_size(ctx), EVP_MD_size(EVP_MD_CTX_md(ctx)));
>     T(EVP_DigestFinal_ex(ctx, md_value, &md_len));
>     EVP_MD_CTX_free(ctx);
>     printf("  MAC[%u] = ", md_len);
>     hexdump(md_value, md_len);
> ```
It is exactly the case.  md_len is overwritten, though it should not.

**Comment by mouse07410** [comment]
OK. First, what's the difference between
```c
ret = ctx->digest->final(ctx, md);
```
which overwrites `mdsize`, and
```c
ret = ctx->digest->dfinal(ctx->provctx, md, &size, mdsize);
```
which does not? Or `->dfinal()` was never invoked, so we don't even know if it behaves OK or not?

**Comment by beldmit** [comment]
If I'm correct, `->dfinal()` is never invoked because the engine is not converted to a provider.

**Comment by mouse07410** [comment]
> ...`->dfinal()` is never invoked because the engine is not converted to a provider...

Yeah, that sounds reasonable...

Where's the code for `->final()`? Is it provided by the engine? OpenSSL itself? Split between these two? 
@levitte would you like to chime in? ;-)

**Comment by beldmit** [comment]
`->final()`  is provided by the engine.

**Comment by mouse07410** [comment]
Where exactly? And is it possible that the `->final))` in the engine ignores the given `mdsize` and takes the default instead???

**Comment by beldmit** [comment]
Final in the engine calculates the full value and truncates it afterwards.  It's a callback in the EVP_MD structure. The length to be truncated to is set via the control function. But the EVP_DigestFinal_ex returns back the default length, so the output stays untruncated.

**Comment by mouse07410** [comment]
Are we talking about `omac_imit_final()` ?

**Comment by beldmit** [comment]
The requested size is set here 
https://github.com/gost-engine/engine/blob/ecad16119a101a1f1947a80e9f630ac2dc2c2794/gost_omac.c#L205-L227
or here:
https://github.com/gost-engine/engine/blob/master/gost_omac_acpkm.c#L468-L490

Then it is overwritten in the OpenSSL master branch.

**Comment by mouse07410** [comment]
> Then it is overwritten in the OpenSSL master branch.

To begin with, I rather doubt that OpenSSL could overwrite `dgst_size`, for the simple reason that nowhere in the sources that variable is referred to:
```
$ pwd
/Users/uri/src/openssl
$ git branch
  OpenSSL_1_0_2-stable
  OpenSSL_1_1_0-stable
  OpenSSL_1_1_1-stable
* master
$ find . -name '*.[ch]' -exec fgrep -n dgst_size {} \;
$ 
```
`dgst_size` seems to be strictly local to the GOST engine. So, to change it, OpenSSL would have to issue another `EVP_MD_CTRL_MAC_LEN` command, and the relevant code in `crypto/evp/digest.c` just doesn't seem to have that.

I wonder where the engine *returns* its current digest size.

**Comment by beldmit** [comment]
I'll take a look at it on Monday.

I was not exact speaking about overwriting. The caller sets the desired size into the local context, then the digest is calculated, then OpenSSL requests the size and gets not the context-specific but the default value.

**Comment by levitte** [comment]
> The caller sets the desired size into the local context, then the digest is calculated, then OpenSSL requests the size and gets not the context-specific but the default value.

If the digest has context dependent output size, then the caller must call `EVP_DigestFinalXOF()` rather than `EVP_DigestFinal_ex()`.  Unfortunately, [the manual](https://www.openssl.org/docs/manmaster/man3/EVP_DigestFinalXOF.html) isn't terribly explicit on this

**Comment by mouse07410** [comment]
> OpenSSL 3 still works the same way as before...

Then I'm confused. When I do  `OPENSSL_CONF="" build/bin/test_grasshopper` the resulting suggest length is correct. If I omit setting `OPENSSL_CONF` or set it to *any* other value, the resulting length is default instead of explicitly specified.

Should the code use ...XOF conditionally when compiled on OpenSSL-3?

**Comment by beldmit** [comment]
Well, I am not sure it is a good idea to use a new function. We have a variable length outpup for GOST MAC, but it is fixed for this MACs in TLS, and it is smaller then the maximum size. It works for 1.1.*, and if the behavior has changed, it should be taken into account for TLS in 3.*

**Comment by levitte** [comment]
This has me wonder what the hell the engine is doing.
I'm not in a position to check that out today, though... or maybe tonight

**Comment by mouse07410** [comment]
Also, I thought the truncation is or at least can be done in the `omac_imit_final()` when it decide how many bytes of the output to `memcpy()` to `md`. But no matter how I change that part of the code, first - no debugging output shows up, and second - length of the result stays default.

**Comment by levitte** [comment]
This issue may be related, btw:
https://github.com/openssl/openssl/issues/9746#issuecomment-526904917

**Comment by mouse07410** [comment]
Hmm, not sure how. You're saying that maybe OpenSSL didn't like the proposed length but instead of reporting am error, fails silently? I doubt it, as it does return the digest, albeit of the default length...

**Comment by mouse07410** [comment]
https://github.com/mouse07410/engine/blob/6603024f0b81bfa8f89d9a918e761268e492cfc6/gost_omac.c#L77-L104

In the above code, any clue why 
- introduced debugging fprintf do not show up on any output?
- memcpy appears to copy more than it's supposed to?

**Comment by beldmit** [comment]
No, if the truncation is done in omac_imit_final, we will still be requested about the maximum length.

**Comment by beldmit** [comment]
I will be ready to explain what the hell the engine is doing tomorrow evening or on Tuesday

**Comment by mouse07410** [comment]
> I will be ready to explain what the hell the engine is doing

Hopefully, also why the truncation in the engine didn't work, and debugging printout?

**Comment by beldmit** [comment]
The truncation in the engine does not work because the engine always operates with the full length.

**Comment by mouse07410** [comment]
What about `memcpy(md, mac, mac_size);` where `mac_size` in my fork set to what CTX says the size should be (and upon entry was proven to be 8)?

**Comment by beldmit** [comment]
> What about the last `memcpy(md, mac, mac_size);` in `gost_imit_final ()` where `mac_size` in my fork set to what CTX says the size should be (and upon entry was proven to be 8)?

Could you please provide a link to the code? `gost_imit_final` has nothing to do with OMAC and I do not see this call in it...

**Comment by mouse07410** [comment]
I meant `omac_imit_final()`. The line in question is
https://github.com/mouse07410/engine/blob/9d2ae202386fec703ff5d0d14475a87e8fa44551/gost_omac.c#L97

It looks like after OpenSSL `CMAC_final()` returns with whatever many bytes of digest, `omac_imit_final()` decides how many bytes to copy into `md`.

Also, it would be nice to know why the debugging output surrounding those lines never shows up anywhere.

**Comment by beldmit** [comment]
```
# define EVP_MD_CTX_size(e)              EVP_MD_size(EVP_MD_CTX_md(e))
```
So it means that we always get a full length (as `EVP_MD_size` returns it) and no truncation at all.

**Comment by beldmit** [comment]
I have a bad feeling about this line in tests:
https://github.com/gost-engine/engine/blob/master/test_grasshopper.c#L348

I think we should call `omac_imit_ctrl` with EVP_MD_CTRL_MAC_LEN as 2nd argument.
@levitte, could you please confirm?

**Comment by mouse07410** [comment]
> So it means that we always get a full length (as `EVP_MD_size()` returns it) and no truncation at all.

No it doesn't - because in the test `EVP_MD_size()` returns what was set before with `EVP_MD_meth_set_result_size()` - aka the correct value of 8. 

My fork shows that clearly:
```
. . . . .
7: OMAC test from GOST R 34.13-2015
7: Resize result size from 16 to 8 (mdsize=16)
7: Digest size before final: MD_CTX_size=8 mac_size=8 EVP_MD_size=8
7: Digest size after final:  MD_CTX_size=8 mac_size=8 EVP_MD_size=8
7:   MAC[16] =  336f4d296059fbe34ddeb35b37749c67
7: Test FAILED
. . . . .
```

and here's the code (https://github.com/mouse07410/engine/blob/15cef7a52fd9c039d81a52daf04d33d411e2d5fa/test_grasshopper.c#L345-L365):
```
. . . . .
    T(EVP_MD_meth_get_ctrl(EVP_MD_CTX_md(ctx))(ctx, EVP_MD_CTRL_SET_KEY, sizeof(K), (void *)K));
    if (acpkm)
        T(EVP_MD_meth_get_ctrl(EVP_MD_CTX_md(ctx))(ctx,
                EVP_CTRL_KEY_MESH, acpkm, acpkm_t ? &acpkm_t : NULL));
    T(EVP_DigestUpdate(ctx, pt, pt_size));
    printf("Digest size before final: MD_CTX_size=%d mac_size=%zu EVP_MD_size=%d\n",
           EVP_MD_CTX_size(ctx), mac_size, EVP_MD_size(EVP_MD_CTX_md(ctx)));
    T(EVP_DigestFinal_ex(ctx, md_value, &md_len));
    printf("Digest size after final:  MD_CTX_size=%d mac_size=%zu EVP_MD_size=%d\n",
           EVP_MD_CTX_size(ctx), mac_size, EVP_MD_size(EVP_MD_CTX_md(ctx)));
    EVP_MD_CTX_free(ctx);
    printf("  MAC[%u] = ", md_len);
. . . . .
```

So, again, my question is: why debugging output from `gost_omac.c` doesn't show up anywhere, why the provided digest size (that OpenSSL apparently recognizes) gets ignored, and why `omac_imit_final()` that is supposed to `memcpy()` only the required number of bytes, appears to copy the default amount?

**Comment by beldmit** [comment]
1. Is the engine built with -DDEBUG? If no, the debug print from `omac_imit_final` will be omitted. The other variant is that the other instance of the engine is called in tests, but I think everything is OK with your setup here.

2. Just 2 cents regarding  https://github.com/mouse07410/engine/blob/15cef7a52fd9c039d81a52daf04d33d411e2d5fa/test_grasshopper.c#L358-L362

It would be better to replace `mac_size` with `md_len` in `printf`s, as `mac_size` does not change here, but `md_len` does.

3. EVP_DigestFinal_ex takes a resulting length from `**ctx->digest**`, and the changed length is set as a property of `**ctx->reqdigest**`. I try to understand whether they point to the same address (if no, it explains everything), but for now, I got lost in EVP_DigestInit_ex where they both are set. 

As `ctx->reqdigest` seem to appear only in 3.0, it could explain much.

4. Anyway the call to `EVP_MD_meth_set_result_size` seems erroneous, as it replace a global property of the digest, and the test should be fixed.

Dear @levitte, could you please clarify about pp 3-4?

**Comment by mouse07410** [comment]
> Is the engine built with `-DDEBUG`?

If it wasn't - why would I expect the output that's compiled conditionally on `DEBUG` being set?

> It would be better to replace `mac_size` with `md_len` in `printf`s, as `mac_size` does not change here, but `md_len` does

Thanks. Based on how I understand your code, both variables matter. I'll make sure `md_len` is included. *Not that it helps much, as long as that output doesn't show up!*

@levitte pp 3-4 in @beldmit post above are yours. ;-)

**Comment by beldmit** [comment]
> > Is the engine built with `-DDEBUG`?
> 
> If it wasn't - why would I expect the output that's compiled conditionally on `DEBUG` being set?

May I ask you either to remove `#ifdef DEBUG` or add `#pragma error` into one of the blocks just to be sure?

**Comment by mouse07410** [comment]
~~As I don't fully understand the implications of `#pragma error`, I removed the `#ifdef`'s. Still, nothing gets printed from `gost_omac.c`.~~ *Apparently, it gets printed - but the tests filter everything out. So, to see it I have to manually invoke `build/bin/test_grasshopper`. That's refreshing - at least debugging output works. ;)*

I've also added `md_len` to the debugging output from `test_grasshopper.c`:
```
# Tests for omac
OMAC test from GOST R 34.13-2015
Resize result size from 16 to 8 (mdsize=16)
Digest size before final: MD_CTX_size=8 mac_size=8 EVP_MD_size=8 md_len=8
/Users/ur20980/src/engine/gost_omac.c:90 mac_size=16 c->dgst_size=16 ctx_md_size=8
/Users/ur20980/src/engine/gost_omac.c:100 mac_size=8 c->dgst_size=16 ctx_md_size=8
Digest size after final:  MD_CTX_size=8 mac_size=8 EVP_MD_size=8 md_len=16
  MAC[16] =  336f4d296059fbe30000000000000000
Test FAILED
```

The culprit appears to be `c->dgst_size` that did not change from 16 to 8.

**Comment by beldmit** [comment]
Could you please replace

```
	T(EVP_MD_meth_set_result_size((EVP_MD *)EVP_MD_CTX_md(ctx), mac_size));
```
With 
```
     T(EVP_MD_meth_get_ctrl(EVP_MD_CTX_md(ctx))(ctx, EVP_MD_CTRL_MAC_LEN, mac_size, NULL));
```

**Comment by mouse07410** [comment]
Instead of replacing that line, I added the one you suggested, thinking that "кашу маслом не испортишь" - see my fork. 

The result showed that now `omac_imit_ctrl()` *does* get invoked to change the digest size, but it still isn't enough:
```
7: # Tests for omac
7: OMAC test from GOST R 34.13-2015
7: Resize result size from 16 to 8 (mdsize=16)
7: /Users/uri/src/grasshopper-engine/gost_omac.c:169 omac_imit_ctrl(): type=0x1005  arg=8
7: /Users/uri/src/grasshopper-engine/gost_omac.c:169 omac_imit_ctrl(): type=0x1004  arg=32
7: Digest size before final: MD_CTX_size=8 mac_size=8 EVP_MD_size=8 md_len=8
7: Digest size after final:  MD_CTX_size=8 mac_size=8 EVP_MD_size=8 md_len=16
7:   MAC[16] =  336f4d296059fbe30000000000000000
7: Test FAILED
. . . . .
```

The OMAC default size (16 bytes) remains stuck somewhere. Maybe another CTX, maybe something else. Note, that I tried before manually changing `c->dgst_size`, and it did not have the desired effect either (default size prevailed).

Can the order of operations (setting digest size, setting the key) matter? *I know - I'm grasping at the straws.*

**Comment by beldmit** [comment]
Could you also check that `ctx->digest` and `ctx->reqdigest` point to different EVP_MD objects in `EVP_DigestFinal_ex`?

**Comment by mouse07410** [comment]
Probably cannot - debugging with multiple shared libraries turns out to be unreliable (or I haven't figured out how).

I conjecture, based on what we've seen, that they *are* different.

**Comment by beldmit** [comment]
Could you please just add some debug print to verify?

**Comment by mouse07410** [comment]
I sure will. But you see that some prints just don't show up. So there's no guarantee the would show up either.

**Comment by levitte** [comment]
Oh boy...  what a pile of confusion.

1.  *Do not use `EVP_MD_meth_`, `EVP_CIPHER_meth_` or any other `_meth_` function unless you're constructing a new method structure*
    (basically, if you do, you're screwing up things, quite badly...  think threaded applications)
2.  There is `EVP_MD_size()`, which always only returns the preset *constant* size from the method.  This value is (at least in theory) not possible to modify by anyone but the method creator.
3.  There is `EVP_MD_CTX_size()`, which I now discover just does `EVP_MD_size(EVP_MD_CTX_md(ctx))` even in OpenSSL 3.0, which was perfectly OK as long as we only dealt with constant size MDs.
4.  There is `EVP_DigestFinalXOF()`, which is currently *the only supported way* to get a digest result other than what is given by the size stored in the `EVP_MD` structure (it uses internal ctrl() / set_ctx_params() functionality to set the size for that specific context).

**Comment by levitte** [comment]
#169 adds XOF support to the Grasshopper MDs, and cleans up `test_grasshopper.c`.  Perhaps @mouse07410 will have fewer problems then?

**Comment by mouse07410** [comment]
> ...what a pile of confusion...

No offense meant - but thanks to the OpenSSL developers for creating that pile by making incompatible and poorly-documented changes (whose necessity I can't claim to grasp yet).

> There is `EVP_DigestFinalXOF()`, which is currently *the only supported way* to get a digest result other than what is given by the size stored in the `EVP_MD` structure

Simply replacing `EVP_DigestFinal_ex()` with `EVP_DigestFinalXOF()` did not work: it did truncate the output, but the resulting digest became all zeroes (for *all* the Grasshopper-based digests):
```
. . . . .
7: # Tests for omac
7: OMAC test from GOST R 34.13-2015
7: /Users/ur20980/src/engine/gost_omac.c:168 omac_imit_ctrl(): type=0x1004  arg=32
7: Digest size before final: MD_CTX_size=16 mac_size=8 EVP_MD_size=16 md_len=8
7: Digest size after final:  MD_CTX_size=16 mac_size=8 EVP_MD_size=16 md_len=8
7:   MAC[8] =  0000000000000000
7: Test FAILED
7: OMAC-ACPKM test from R 1323565.1.017-2018 A.4.1
7: Digest size before final: MD_CTX_size=16 mac_size=16 EVP_MD_size=16 md_len=16
7: Digest size after final:  MD_CTX_size=16 mac_size=16 EVP_MD_size=16 md_len=16
7:   MAC[16] =  00000000000000000000000000000000
7: Test FAILED
7: OMAC-ACPKM test from R 1323565.1.017-2018 A.4.2
7: Digest size before final: MD_CTX_size=16 mac_size=16 EVP_MD_size=16 md_len=16
7: Digest size after final:  MD_CTX_size=16 mac_size=16 EVP_MD_size=16 md_len=16
7:   MAC[16] =  00000000000000000000000000000000
7: Test FAILED
7: = Some tests FAILED
. . . . .
```

> #169 adds XOF support to the Grasshopper MDs, and cleans up `test_grasshopper.c`. Perhaps @mouse07410 will have fewer problems then?

Thank you - with #169 indeed **both OpenSSL-1.1.1 and 3.0 tests all pass**.

More so, with this PR merged, somehow `test_grasshopper` began running correctly when the correct `OPENSSL_CONF` was set. ;-)

@levitte thanks again!

**Comment by mouse07410** [comment]
#169 closes this issue

**Comment by levitte** [comment]
> No offense meant - but thanks to the OpenSSL developers for creating that pile by making incompatible and poorly-documented changes (whose necessity I can't claim to grasp yet).

None taken. The `_meth_` functions were created for those who want to create an `EVP_MD`, `EVP_CIPHER` or what not after those structures became opaque. Typically, all engines had to start using them.

**Comment by levitte** [comment]
> Thank you - with #169 indeed both OpenSSL-1.1.1 and 3.0 tests all pass.

Great! I'm just glad I could finally figure it out

**Comment by mouse07410** [comment]
@levitte but why then did the `_meth_...()` code work with OpenSSL-1.1.1? And somehow, worked with 3.0 *if* `OPENSSL_CONF=""` was set???

**Comment by mouse07410** [comment]
@beldmit let's merge #169 before the code gets stale! ;-)

**Comment by levitte** [comment]
> @levitte but why... 

I have *no* idea, and quite frankly don't want to dive into that for the moment. I have enough on my plate as it is.

**Comment by mouse07410** [comment]
> . . . frankly don't want to dive into that for the moment. I have enough on my plate as it is . . .

:-)  Understood. It works now, which is what matters.

**Comment by vt-alt** [comment]
@levitte Big thanks for your help!
