### ISSUE TITLE
pkey_gost_ec_derive return code

### ISSUE THREAD

**Issue by dbanisimov** [gost-engine/engine#17]
In OpenSSL docs for [EVP_PKEY_derive](https://www.openssl.org/docs/manmaster/crypto/EVP_PKEY_derive.html) it is stated that:

> EVP_PKEY_derive_init() and EVP_PKEY_derive() return 1 for success and 0 or a negative value for failure.

OpenSSL DH implementation follows this convention.

GOST engine returns key length on success which may break some code that expects '1'.

**Comment by beldmit** [comment]
Fixed in master.
