### ISSUE TITLE
OMAC-ACPKM cipher mode registration

### ISSUE THREAD

**Issue by UndefBehavior** [gost-engine/engine#171]
gost-engine registers omac-acpkm mode for Kuznechik cipher with NID_id_tc26_cipher_gostr3412_2015_kuznyechik_ctracpkm_omac identifier. This identificator corresponds to OID 1.2.643.7.1.1.5.2.2 which is described by TK26 as a "CTR cipher mode for Kuznechik cipher with ACPKM re-keying mechanism with MAC calculation". I suppose that this OID must be specific to TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC cipher suite from draft-smyshlyaev-tls12-gost-suites.

Is it right to register OMAC_ACPKM mode this way? Should it be registered explicitly? Would it be better to enable ACPKM for MAC by activating EVP_CTRL_KEY_MESH control? Should openssl contain some "grasshopper-mac-acpkm" nid if it does not?

**Comment by beldmit** [comment]
I will reply later, not sure when.

**Comment by beldmit** [comment]
I took a brief look at it and I think you are right and there is something weird in this OID mapping. I'll take a more close look sometime later.

**Comment by beldmit** [comment]
As colleagues from CryptoPro clarified, there is no OID for *OMAC-ACPKM, as they are not in use currently. The OID 1.2.643.7.1.1.5.2.2 means MtE data processing.

**Comment by UndefBehavior** [comment]
How this OID must be handled by OpenSSL and gost-engine? There is no open information about its usage. Mustn't OpenSSL has NIDs without corresponding OIDs especially for registration OMAC-ACPKM cipher mode for Magma and Kuznechik?

**Comment by beldmit** [comment]
Currently OpenSSL must have NID, but not OID.

**Comment by UndefBehavior** [comment]
Is it ok, if I do a PR in OpenSSL with Nids of OMAC_ACPKM for Magma and Kuznechik? Must we use NID_grasshopper_mac with KEY_MESH_CTRL instead? The first option is prefferable to me because of the possibility to use default value for section size

**Comment by beldmit** [comment]
Not sure. If I understand correctly, the upcoming OpenSSL major version will refer to string names, not to NIDs, on fetching algorithms. @levitte, am I correct?

**Comment by levitte** [comment]
You are correct, algos are (externally) referred to by name, not by number, when using the new fetching interface. 

(I have it on good authority that this was the original intention, that you would "fetch" algorithms with functions like EVP_get_cipherbyname, and that NIDs would be strictly internal. Unfortunately, the obj header files were made public and hell broke loose)

**Comment by UndefBehavior** [comment]
Okay then it is good to add SN/LN for this mode. I think that the main problem is inability to add algorithm without modifying openssl public headers. There is a possibility to add object via OBJ_create() but it is impossible without OID which isn't suitable for algorithms. You can't use EVP_get_cipherbyname  without it.

So I mean OBJ without OID by "NID" here, I'm sorry for confusion

**Comment by levitte** [comment]
Hmmm, I don't quite remember, but I *think* there's away to add an object without an OID.

But anyway, I agree that having to add stuff to the openssl publig headers is a problem. Our intent is that the new provider interface will take that kind of problem away.

**Comment by beldmit** [comment]
It definitely exists, I've already done it many times...

**Comment by UndefBehavior** [comment]
Unfortunately, I didn't find this way, I thought that there is a way via creating OBJ manually with registration your own ASN1_OBJECT but the fields of this structure are private.

I haven't find out the features of providers but the 1.1.1 branch will be main for users at least year I suppose so it will be useful to handle cipher mode properly which is already implemented in the engine.

**Comment by beldmit** [comment]
Oops. I'm afraid no chance to register object without NID in run-time...

**Comment by levitte** [comment]
I could have sworn I have written a small example engine the gets a NID dynamically and adds a cipher object tied to that NID. I can try to dig that up.
(don't hold your breath)

**Comment by UndefBehavior** [comment]
It is possible to get a new NID via OBJ_new_nid() and assign CIPHER or MD but what is case of using it? Must engine has a specific function to bring this NID to user? How is it possible to use such CIPHER/MD via OpenSSL tool?

**Comment by levitte** [comment]
EVP_get_cipherbyname() should be able to find a dynamically added cipher by its name.

**Comment by UndefBehavior** [comment]
Name is SN/LN, is I'm right? I didn't find the way to register it for an algorithm without OID. The only way I found is the registering an alias but this is not the case because an alias must be for existing OBJ which will be inconstistent for alias in this situation

**Comment by beldmit** [comment]
Well, both these objects are registered in OpenSSL master, so this issue can be closed.
