### ISSUE TITLE
Некорректный PKSC12 (Bad keyset) сформированный по сертификату и ключу GOST2012_256(512)

### ISSUE THREAD

**Issue by TrunovS** [gost-engine/engine#173]
Доброго времени суток.

Версия engine v1.1.0.3, openssl 1.1.0k

Пытаюсь сгенерировать приватный ключ, сертификат и вставить все это в хранилище сертификатов Windows 10 следующим образом:
1. `openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:A -out gost.key`
2. `openssl req -engine gost -new -x509 -key gost.key -out gost.crt`
3. `openssl pkcs12 -export -out gost.pfx -inkey gost.key -in gost.crt`

или:
 1. `openssl req -x509 -newkey gost2012_256 -pkeyopt paramset:A -keyout gost.key -out gost.crt -subj "/CN=test" -days 600`
2. `openssl pkcs12 -export -name "test" -out gost.pfx -inkey gost.key -in gost.crt`

- При загрузке через `certutil.exe -user  -importPFX gost.pfx` выдается сообщение: Bad keyset
Keyset does not excist. 
- При попытке загрузить pfx в Firefox также выдается ошибка о невозможности добавить файл к сертификатам.
- При импорте того же сертификата через GUI Windows молча устанавливается, но при использовании из wincrypt выдается тоже "Bad keyset". 

Пробовал как написано в документации использовать `-keypbe gost89  -certpbe gost89 -macalg md_gost94` заменяя или нет md_gost94 на md_gost12_256, в разных комбинациях  что приводит к немного другой ошибке `Bad encode`.

В файле openssl.cfg добавлены поля:
``` sh
    [openssl_def]
    engines = engine_section

    [engine_section]
    gost = gost_section

    [gost_section]
    engine_id = gost
    dynamic_path = /usr/lib/openssl/engines/libgost.so
    default_algorithms = ALL
    CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet
```
И все этапы генерации проходят без сообщений об ошибках.

Для rsa sha256 генерация и импорт проходит успешно:
1. `openssl req -x509 -newkey rsa:4096 -sha256 -keyout sha.key -out sha.crt -subj "/CN=test" -days 600`
2. `openssl pkcs12 -export -name "test" -out sha.pfx -inkey sha.key -in sha.crt`
3. `certutil.exe -user  -importPFX sha.pfx`

Эти симптомы, как я понимаю свидетельствуют:
- о том что приватная часть сформированная gost engine не попала в pkcs12 в момент экспорта.
- или о неправильном экспортировании сертификатов сформированных gost engine в pksc12.

**Comment by beldmit** [comment]
certutil.exe - это что? Я этого не писал :)

**Comment by TrunovS** [comment]
certutil это импорт pfx в стор сертификатов Windows через CMD. Привел его в пример способов каким я пытался импортировать pkcs12.

**Comment by beldmit** [comment]
Windows по умолчанию ГОСТы не умеет. Если у Вас не установлен никакой криптопровайдер, который умеет ГОСТ в Windows, то импорт не сработает.

**Comment by TrunovS** [comment]
Спасибо. Попытался импортировать через КриптоПро 4 `certmgr.exe -inst -store "My" -pfx -file .\gost.pfx` 
```
=============================================================================
1-------
Issuer              : CN=test
Subject             : CN=test
Serial              : 0x00875345B11979CB69
SHA1 Hash           : f8650680b15fd8d93d40fd067d6ab688fca842c0
SubjKeyID           : d4dc8302104176f3e3ba574ce7b767b83410c51d
Signature Algorithm : ГОСТ Р 34.11-2012/34.10-2012 256 бит
PublicKey Algorithm : ГОСТ Р 34.10-2012 256 бит (512 bits)
Not valid before    : 18/09/2019  15:52:16 UTC
Not valid after     : 10/05/2021  15:52:16 UTC
PrivateKey Link     : Yes
Container           : test
Provider Name       : Microsoft Software Key Storage Provider
Provider Info       : ProvType: 0, KeySpec: 0, Flags: 0x0
==============================================================
```
, однако при попытке протестировать загруженный сертификат ошибка - "Набор ключей не существует".

**Comment by beldmit** [comment]
Этот вопрос, наверное, стоит задать в КриптоПро.

**Comment by TrunovS** [comment]
Спасибо. Хотел бы уточнить. Известна ли Вам история успеха импорта для сертификатов сформированных gost engine в формате pfx какого-то из стандартов 2001, 2012?

**Comment by beldmit** [comment]
Ну, совместимость при всех правильных параметрах есть и с КриптоПро, и с Инфотексом. Но

1. Есть грабли с одинарным/двойным врапом ключа (у КриптоПро двойной, у Инфотекса одинарный)
2. Надо тщательно подбирать алгоритмы, внутри вроде бы умолчания от ТК26.
3. Со старыми версиями и с новыми есть варианты, как считать MAC. Подробности в файле 
crypto/pkcs12/p12_mutl.c из openssl.

**Comment by TrunovS** [comment]
Не могли бы немного поподробнее рассказать, ну или направить на опцию openssl про одинарный/двойной врап ключа. Какой по-умолчанию используется в gost engine? 
Есть ли какие-то взаимоисключающие алгоритмы (п.2) при формировании gost2012_256 ключей и сертификатов?

**Comment by beldmit** [comment]
По умолчанию одинарный, искать по словам GOST_PARAM_PK_FORMAT
Нет, взаимоисключающих нет, но что рекомендовал ТК26, я навскидку не помню, а engine всеядный.

**Comment by beldmit** [comment]
Можно закрывать?

**Comment by TrunovS** [comment]
Да, спасибо, за помощь.
