### ISSUE TITLE
Нужно ли проверять на 0 перед вызовом "*_free" функций?

### ISSUE THREAD

**Issue by outspace** [gost-engine/engine#177]
Просматривая код энжина возник вопрос по поводу проверок на 0 перед вызовом free функций. Насколько мне известно, то обычно такие проверки делать не нужно.
Как пример можно взять кусок кода:
https://github.com/gost-engine/engine/blob/5038c47d799e77d347ef84f390699157c4438e3e/gost_ameth.c#L777-L785

Мне интересно чем обусловлены такие проверки и как делать правильно?

**Comment by beldmit** [comment]
В OpenSSL их обычно делать не нужно, но для этого надо инициализировать указатели NULL-ом.
