### ISSUE TITLE
Работа функции gost_grasshopper_set_asn1_parameters()

### ISSUE THREAD

**Issue by outspace** [gost-engine/engine#180]
Если посмотреть на функцию gost_grasshopper_set_asn1_parameters():
https://github.com/gost-engine/engine/blob/5038c47d799e77d347ef84f390699157c4438e3e/gost_grasshopper_cipher.c#L707-L725

Я не знаю дописана ли эта функция, но по моим впечатлениям каждый ее вызов будет приводить к ошибке + утечке os.

**Comment by beldmit** [comment]
Она и должна так работать, освобождение происходит в вызывающем коде.

**Comment by outspace** [comment]
Ну с работой я может и погорячился, но очевидно что  в 716 строчке должно быть освобождение os.

**Comment by outspace** [comment]
Да и вообще я не уверен что здесь нужен вызов ASN1_OCTET_STRING_set.

**Comment by beldmit** [comment]
Вызов нужен, утечку вроде закрыл. Спасибо!

**Comment by outspace** [comment]
Вызов в OPENSSL_free(buf); был вроде как излишний, но так тоже норм.

**Comment by outspace** [comment]
Так и все же что делает тот вызов? Вызов ASN1_OCTET_STRING_set с параметрами NULL и 0 просто зануляет значения,  ASN1_OCTET_STRING_new() их зануляет при создании. В чем разница? 

Вызовы OPENSSL_free(buf) ничего страшного не несут учитывая что buf всегда равен NULL. Но зачем их делать я не понимаю.

**Comment by beldmit** [comment]
Пока она ничего не делает. Потом должно вырасти что-то вот такое:
https://github.com/gost-engine/engine/blob/7f55249334f0dd265a3c2579812cbcec6c946944/gost_crypt.c#L956-L999

Дело в том, что этот код писался, пока стандартов на использование Кузнечика в CMS не было. Сейчас он пояился и его надо дописать.
