### ISSUE TITLE
GOST R 3411-94 hashes differ in gostsum and rhash/libgcrypt

### ISSUE THREAD

**Issue by mikhailnov** [gost-engine/engine#189]
[worker-info.log](https://github.com/gost-engine/engine/files/3901853/worker-info.log)

gostsum gives one hash, rhash and libgcrypt give another one.

```
user@pay2:~/Загрузки$ gostsum worker-info.log
41441122cb6ee14524a4a424d855536ed41f1fc213c5bea080ada002d1e4b0a4 worker-info.log
user@pay2:~/Загрузки$ rhash --gost94 worker-info.log
c01fb5cab48bbebd098be5af7d4e6d0c2b03379d5d2d8ed3eb85083c5a6312cc  worker-info.log
user@pay2:~/Загрузки$ 
[root@rosa-2019 worker-info]# rpm -qp --dump /mnt/dev/rosa-pkgs/worker-info/worker-info-0.3-2-rosa2019.1.noarch.rpm
/worker-info.log 3063 1574945587 c01fb5cab48bbebd098be5af7d4e6d0c2b03379d5d2d8ed3eb85083c5a6312cc 0100664 root root 0 0 0 X
```

rhash and libgcrypt have the same result, gostsum has another. Reproduced using rhash and gostsum on Ubutnu 19.10 and ROSA 2019.1. Test file is attached.

Как так?

**Comment by mikhailnov** [comment]
`gost12sum` and `rhash --gost12-256` have the same results, `gost12sum -l` and `rhash --gost12-512` also have the same results.

**Comment by vt-alt** [comment]
@mikhailnov Можно получить этот `worker-info-0.3-2-rosa2019.1.noarch.rpm`? Мне интересно как именно вы туда прикрутили ГОСТ.

**Comment by beldmit** [comment]
Коммерческая реализация даёт ```openssl dgst -md_gost94 worker.log```
```a4b0e4d102a0ad80a0bec513c21f1fd46e5355d824a4a42445e16ecb22114441```

**Comment by beldmit** [comment]
Порядок байт обратный, но это известная багофича. КриптоПро проверить прямо сейчас не могу, но попробую.

Убедитесь пожалуйста, что в rhash и libgcrypt не зашиты так называемые тестовые параметры хеша. Тестовые и production параметры доступны, например, здесь:

https://metacpan.org/source/GRAY/Digest-GOST-0.06/src/gost.c#L450-477

**Comment by mikhailnov** [comment]
(оффтоп) @vt-alt ГОСТ мы прикрутили через libgcrypt, использовать который RPM 5 уже немного умел и который имеет апстримную реализацию алгоритмов хеширования:
https://abf.io/soft/rpm5/commit/5bf4d7c6391be2408e59680999d8a83fb279d64a
https://abf.io/import/rpm/commit/da3f192507c0e2e839bf1d7f9a0ea5fe8f6d3709
В RPM 4 libgcrypt нет, но параллельно с beecrypt реализована поддержка OpenSSL, в теории, наверное, можно gost-engine прикрутить.
Основная проблема с криптоподписью пакетов по ГОСТ - в gnupg нет подписей по ГОСТ, даже с патчами `manowar@`.
Образец пакета с хешированием по ГОСТ-2012 Stribog-256 (этой issue речь шла про ГОСТ-1994): https://file-store.rosalinux.ru/download/ce8d45dc59ec72eaeaa61ebd7373aae94cc5d68a
С чтением этих пакетов в RPM, ничего не знающих об этих алгоритмах, есть проблема: https://github.com/rpm-software-management/rpm/issues/959

**Comment by beldmit** [comment]
А, то есть rhash использует gcrypt, поэтому результаты и совпадают :)

**Comment by mikhailnov** [comment]
> А, то есть rhash использует gcrypt, поэтому результаты и совпадают :)

Не использует. Вот пример коммита, добавлявшего алгоритмы: https://github.com/rhash/RHash/commit/826354c0c7200f9d9a1735140e913135b6864919 Никаких отсылок к libgcrypt. В сборочных зависимостях пакета rhash также нет gcrypt (https://abf.io/import/rhash/blob/rosa2019.1/rhash.spec)

Попробую для начала libressl в OpenBSD.

**Comment by mikhailnov** [comment]
libressl portable показал то же, что и "коммерческая реализация" у вас:
```
$ /opt/libressl/bin/openssl dgst -md_gost94 worker-info.log
md_gost94(worker-info.log)= a4b0e4d102a0ad80a0bec513c21f1fd46e5355d824a4a42445e16ecb22114441
```
Попробую сравнить таблицы, но ни разу таким не занимался.

**Comment by vt-alt** [comment]
@mikhailnov Спасибо за информацию и файл!

**Comment by lumag** [comment]
Rhash использует тестовый S-Box из стандарта. В libgcrypt есть поддержка как тестового `GCRY_MD_GOSTR3411_94`,  так и CryptoProшного `GCRY_MD_GOSTR3411_CP` S-Box. Правильнее использовать, по-моему, криптопрошный (см. RFC4357).

**Comment by beldmit** [comment]
Никакой другой на практике не использовался никогда. Массово во всяком случае.

**Comment by beldmit** [comment]
Могу закрывать?

**Comment by mikhailnov** [comment]
Спасибо! Замена `GCRY_MD_GOSTR3411_94` на `GCRY_MD_GOSTR3411_CP` исправило хеши. Простите за ложную тревогу.

P.S. Для тех, кто сюда попадет и будет думать, почему в `gostsum` обратный порядок бит:
https://ru.wikipedia.org/wiki/ГОСТ_Р_34.11-94#Формат_вывода
