### ISSUE TITLE
ошибка сборки в cirrus-ci

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#199]
https://github.com/gost-engine/engine/runs/385094611

```
/usr/local/bin/perl "-I." -Mconfigdata "util/dofile.pl"  "-oMakefile" util/shlib_wrap.sh.in > "util/shlib_wrap.sh"
chmod a+x util/shlib_wrap.sh
pod2man --name=CA.PL --section=1 --center=OpenSSL  --release=3.0.0-dev   > doc/man/man1/CA.pl.1
pod2man: unable to format standard input
*** Error code 1
```

ээээ.... такое как вообще ? в ветке мастер поменялась система сборки ? это проявляется только в freebsd ? это надо репортить  в OpenSSL ?

может, кстати, им предложить cirrus-ci / freebsd ?

**Comment by beldmit** [comment]
Да, репортить туда. И cirrus предложить, наверное, стоит.

Сделаете?

**Comment by chipitsine** [comment]
ок, сделаю

**Comment by chipitsine** [comment]
насчет cirrus-ci, там надо контрибутить.
я как-то год назад сканировал распечатанный агримент для контрибута в openssl.
юристы на той стороне решили поиграть в дурачка "у тебя не хватает подписи". подпись явно была. я забил в итоге.

**Comment by chipitsine** [comment]
https://github.com/openssl/openssl/issues/10817

**Comment by beldmit** [comment]
Индивидуальный cla подписать не проблема. А после истории с nginx я перестал считать это требование блажью.

**Comment by chipitsine** [comment]
я думаю, юристы переоценили моё желание законтрибутить (бумага таки была с подписью). обычный опенсорс, который не особо кому-то в какое-то место уперся.

ладно. посмотрим

**Comment by chipitsine** [comment]
Вроде починили, пока закрою
