### ISSUE TITLE
Add framework to add entries into object database.

### ISSUE THREAD

**Issue by vbwagner** [gost-engine/engine#2]
Now, gost engine depends entirely on neccessary OIDs and SNs added to core OpenSSL object database. This prevent using  of updated engine with already released OpenSSL.

It would be nice if separately maintained engine would work with older versions of OpenSSL declaring new NIDs if possible, but taking advantage of existing ones if neccessary.

**Comment by beldmit** [comment]
It was a long story. I'm afraid it's irrelevant now.
