### ISSUE TITLE
core dump in grasshopper-ctr mode

### ISSUE THREAD

**Issue by greenEkatherine** [gost-engine/engine#20]
The issue appears through using the branch openssl_1_1_0: encryption/decryption command 
` ./openssl enc -grasshopper-ctr <...>` 
return 
`openssl: malloc.c:2395: sysmalloc: Assertion (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed. Core dump`

**Comment by beldmit** [comment]
Please try the patch from https://github.com/gost-engine/engine/pull/21
