### ISSUE TITLE
Branch openssl_1_0_2 doesn't build with OpenSSL 1.0.2

### ISSUE THREAD

**Issue by Pulfer** [gost-engine/engine#23]
Branch openssl_1_0_2 doesn't build with OpenSSL 1.0.2 (patched with patches from https://github.com/gost-engine/engine/tree/master/patches/1.0.2 ).

Because of this commit: https://github.com/gost-engine/engine/commit/a170809d792816448cb4c95f3473531a1a917e69

**Comment by beldmit** [comment]
Could you please provide the pull-request?

**Comment by Pulfer** [comment]
I don't have any. Just tried to build the code and found that openssl_1_0_2 branch is compatibile with OpenSSL 1.1.0 but not 1.0.2 since 04.01.2016. 

Maybe it makes sense to reset openssl_1_0_2 branch to pre- https://github.com/gost-engine/engine/commit/a170809d792816448cb4c95f3473531a1a917e69 state.

**Comment by beldmit** [comment]
Please try now. I recreated the branch from the place I think to be a reasonable initial commit.

**Comment by Pulfer** [comment]
Thanx for doing it. I'll try to build and test soon. Meanwhile can you please tell me if this config is OK for GOST 2012? I'm not sure about CRYPT_PARAMS value.

> # OpenSSL default section
> [openssl_def]
> engines = engine_section
> 
> # Engine scetion
> [engine_section]
> gost = gost_section
> 
> # Engine gost section
> [gost_section]
> engine_id = gost
> dynamic_path = /usr/lib/ssl/engines/libgost.so
> default_algorithms = ALL
> CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet

**Comment by beldmit** [comment]
I think it should.
