### ISSUE TITLE
Branch openssl_1_1_0 fails engine test

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#234]
MacOS 10.15.4, Xcode-11.4.1, OpenSSL-1.1.1g. Branch `openssl_1_1_0`.
```
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /Users/ur20980/src/grasshopper-engine/build
    Start 1: engine
1/2 Test #1: engine ...........................***Failed    1.14 sec
    Start 2: grasshopper
2/2 Test #2: grasshopper ......................   Passed    0.42 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   1.57 sec

The following tests FAILED:
	  1 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```

- complete log: [ossl111-build.txt](https://github.com/gost-engine/engine/files/4577757/ossl111-build.txt)
- test output - short: [test-out.txt](https://github.com/gost-engine/engine/files/4577769/test-out.txt)
- test output - long: [test-long-out.txt](https://github.com/gost-engine/engine/files/4577775/test-long-out.txt)

Somehow, it seems to fail to even find the engine.

Detailed errors:
- `test/tests.err` (removing a thousand or so of 'Engine "gost" set' messages) [tests.err.txt](https://github.com/gost-engine/engine/files/4577806/tests.err.txt)
- `build/Testing/Temporary/LastTest.log` [LastTest.log.txt](https://github.com/gost-engine/engine/files/4577814/LastTest.log.txt)

**Comment by mouse07410** [comment]
The problem turned out to be what the scripts `test/00-engine.t` and others set `OPENSSL_ENGINES` if it is not provided. It was set to `../.libs`, which hasn't been around for ages.

Changing it to `abs_path('../bin')` resolved the issue. I suggest you do the same in the `openssl_1_1_0` branch (unless you have a better solution, which would be OK).

With the change described above:
[ossl111-build.txt](https://github.com/gost-engine/engine/files/4604241/ossl111-build.txt)

**Comment by beldmit** [comment]
Could you please submit a PR fixing this problem?

**Comment by beldmit** [comment]
Committed the fix you suggest.
