### ISSUE TITLE
LNK1149 the output file name is the same as the input file "C:\Users\ksv\Downloads\engine-openssl_1_1_0\build\Release\gost.lib" gost_engine

### ISSUE THREAD

**Issue by ksv87** [gost-engine/engine#249]
Build on Windows 10 Pro x64
When building the gost_engine project in Visual Studio 2019 - error LNK1149 the name of the output file matches the name of the input file "C:\Users\ksv\Downloads\engine-openssl_1_1_0\build\Release\gost.lib" gost_engine
What am I doing wrong?
OpenSSL version "1.1.0m"

**Comment by beldmit** [comment]
Sorry, I don't have windows installation. Could you please provide a full log?

**Comment by ksv87** [comment]
[gost_engine.log](https://github.com/gost-engine/engine/files/4633451/gost_engine.log)

**Comment by beldmit** [comment]
Sorry, not enough information anyway.

**Comment by ksv87** [comment]
Я так понял, что Вы говорите на русском языке.
Если я пытаюсь cmake'ом сделатть проект для nmake - при сборке проекта другая ошибка:
error LNK2019: ссылка на неразрешенный внешний символ __builtin_expect в функции grasshopper_galois_mul

**Comment by beldmit** [comment]
Говорю, да. Куда я денусь :)
А компилятор при этом какой?

**Comment by beldmit** [comment]
Тут ноги растут отсюда:

https://github.com/gost-engine/engine/blob/6036eb9be5403af769f211b1056d34bf65028aea/gost_grasshopper_defines.h#L16-L33

Я этот кусок не писал и не понимаю, попробуйте как-нибудь его причесать. Возможно, там путаница в проверках на компилятор.

**Comment by ksv87** [comment]
я пробую сейчас через MinGW собрать:
мне кажется тут что то зациклилось или это нормально и нужно подождать?
![Screenshot_3](https://user-images.githubusercontent.com/15774585/82036211-476a2700-96a9-11ea-861f-63f19711960c.jpg)

**Comment by beldmit** [comment]
Надеюсь, что подождать

**Comment by ksv87** [comment]
Пробую собрать релиз 1.1.0.3

C:\Users\ksv\Downloads\engine-1.1.0.3\mgw>mingw32-make gost_engine
Scanning dependencies of target gost
[  4%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.obj
[  8%] Building C object CMakeFiles/gost.dir/gost_ec_sign.c.obj
[ 12%] Building C object CMakeFiles/gost.dir/gost89.c.obj
[ 16%] Building C object CMakeFiles/gost.dir/gosthash.c.obj
[ 20%] Building C object CMakeFiles/gost.dir/gost_grasshopper_core.c.obj
[ 25%] Building C object CMakeFiles/gost.dir/gost_grasshopper_defines.c.obj
[ 29%] Building C object CMakeFiles/gost.dir/gost_grasshopper_galois_precompiled.c.obj
[ 33%] Building C object CMakeFiles/gost.dir/gost_grasshopper_precompiled.c.obj
[ 37%] Building C object CMakeFiles/gost.dir/gost_grasshopper_cipher.c.obj
[ 41%] Building C object CMakeFiles/gost.dir/gost_grasshopper_mac.c.obj
[ 45%] Building C object CMakeFiles/gost.dir/gosthash2012.c.obj
[ 50%] Linking C static library libgost.a
[ 50%] Built target gost
Scanning dependencies of target gost_engine
[ 54%] Building C object CMakeFiles/gost_engine.dir/e_gost_err.c.obj
[ 58%] Building C object CMakeFiles/gost_engine.dir/gost_asn1.c.obj
[ 62%] Building C object CMakeFiles/gost_engine.dir/gost_crypt.c.obj
[ 66%] Building C object CMakeFiles/gost_engine.dir/gost_ctl.c.obj
[ 70%] Building C object CMakeFiles/gost_engine.dir/gost_eng.c.obj
[ 75%] Building C object CMakeFiles/gost_engine.dir/gost_keywrap.c.obj
[ 79%] Building C object CMakeFiles/gost_engine.dir/gost_params.c.obj
[ 83%] Building C object CMakeFiles/gost_engine.dir/gost_ameth.c.obj
[ 87%] Building C object CMakeFiles/gost_engine.dir/gost_md.c.obj
[ 91%] Building C object CMakeFiles/gost_engine.dir/gost_md2012.c.obj
[ 95%] Building C object CMakeFiles/gost_engine.dir/gost_pmeth.c.obj
[100%] Linking C shared module ..\bin\gost.dll
libgost.a(gost_ec_keyx.c.obj): In function `VKO_compute_key':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:50: undefined reference to `OBJ_nid2sn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:50: undefined reference to `EVP_get_digestbyname'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:63: undefined reference to `EC_POINT_mul'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:78: undefined reference to `EVP_MD_CTX_new'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:83: undefined reference to `EVP_MD_CTX_reset'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:84: undefined reference to `EVP_DigestInit_ex'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:85: undefined reference to `EVP_DigestUpdate'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:96: undefined reference to `EVP_MD_CTX_free'
libgost.a(gost_ec_keyx.c.obj): In function `pkey_gost_ec_derive':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:115: undefined reference to `EVP_PKEY_CTX_get0_peerkey'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:129: undefined reference to `EVP_PKEY_get_default_digest_nid'
libgost.a(gost_ec_keyx.c.obj): In function `pkey_GOST_ECcp_encrypt':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:166: undefined reference to `EVP_PKEY_CTX_get0_peerkey'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:203: undefined reference to `EVP_PKEY_get_default_digest_nid'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:187: undefined reference to `EVP_PKEY_new'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:189: undefined reference to `EVP_PKEY_copy_parameters'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:255: undefined reference to `EVP_PKEY_free'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:230: undefined reference to `X509_PUBKEY_set'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:240: undefined reference to `EVP_PKEY_free'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:243: undefined reference to `EVP_PKEY_CTX_ctrl'
libgost.a(gost_ec_keyx.c.obj): In function `pkey_GOST_ECcp_decrypt':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:291: undefined reference to `X509_PUBKEY_get'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:293: undefined reference to `EVP_PKEY_derive_set_peer'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:306: undefined reference to `EVP_PKEY_CTX_get0_peerkey'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:325: undefined reference to `EVP_PKEY_get_default_digest_nid'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:341: undefined reference to `EVP_PKEY_free'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_keyx.c:300: undefined reference to `EVP_PKEY_CTX_ctrl'
libgost.a(gost_ec_sign.c.obj): In function `fill_GOST_EC_params':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:104: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:105: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:106: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:107: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:112: undefined reference to `EC_GROUP_new_curve_GFp'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:124: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:125: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:127: undefined reference to `BN_hex2bn'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:132: undefined reference to `EC_GROUP_set_generator'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:136: undefined reference to `EC_GROUP_set_curve_name'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:146: undefined reference to `EC_GROUP_free'
libgost.a(gost_ec_sign.c.obj): In function `gost_ec_sign':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:202: undefined reference to `BN_div'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:213: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:225: undefined reference to `BN_rand_range'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:232: undefined reference to `BN_add'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:234: undefined reference to `BN_add'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:237: undefined reference to `EC_POINT_mul'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:254: undefined reference to `BN_nnmod'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:259: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:274: undefined reference to `BN_mod_add'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:279: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:281: undefined reference to `BN_dup'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:282: undefined reference to `BN_dup'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:214: undefined reference to `BN_set_word'
libgost.a(gost_ec_sign.c.obj): In function `gost_ec_verify':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:350: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:350: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:351: undefined reference to `BN_cmp'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:351: undefined reference to `BN_cmp'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:359: undefined reference to `BN_div'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:369: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:369: undefined reference to `BN_set_word'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:373: undefined reference to `BN_mod_inverse'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:375: undefined reference to `BN_sub'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:393: undefined reference to `EC_POINT_mul'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:401: undefined reference to `BN_div'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:412: undefined reference to `BN_cmp'
libgost.a(gost_ec_sign.c.obj): In function `gost_ec_compute_public':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:464: undefined reference to `EC_POINT_mul'
libgost.a(gost_ec_sign.c.obj): In function `gost_ec_keygen':
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:516: undefined reference to `BN_is_zero'
C:/Users/ksv/Downloads/engine-1.1.0.3/gost_ec_sign.c:511: undefined reference to `BN_rand_range'
collect2.exe: error: ld returned 1 exit status
mingw32-make[3]: *** [CMakeFiles\gost_engine.dir\build.make:256: ../bin/gost.dll] Error 1
mingw32-make[2]: *** [CMakeFiles\Makefile2:155: CMakeFiles/gost_engine.dir/all] Error 2
mingw32-make[1]: *** [CMakeFiles\Makefile2:162: CMakeFiles/gost_engine.dir/rule] Error 2
mingw32-make: *** [Makefile:163: gost_engine] Error 2

**Comment by ksv87** [comment]
конфигурил вот так
C:\Users\ksv\Downloads\engine-1.1.0.3\mgw>cmake -G "MinGW Makefiles" -DOPENSSL_ROOT_DIR="C:/Users/ksv/Downloads/openssl-OpenSSL_1_1_0-stable" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-IC:/Users/ksv/Downloads/openssl-OpenSSL_1_1_0-stable/include -LC:/Users/ksv/Downloads/openssl-OpenSSL_1_1_0-stable" ..
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- LITTLE_ENDIAN
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_ROOT_DIR

**Comment by beldmit** [comment]
Ну тут хотя бы понятно, он libcrypto не увидел.

**Comment by ksv87** [comment]
теперь так пробую

C:\Users\ksv\Downloads\engine-1.1.0.3\mgw>cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS="-IC:/Users/ksv/Downloads/openssl-OpenSSL_1_1_0-stable/include C:/OpenSSL/lib/libcrypto.lib" ..
-- The C compiler identification is GNU 8.3.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Searching 16 bit integer - Using unsigned short
-- Check if the system is big endian - little endian
-- LITTLE_ENDIAN
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/ksv/Downloads/engine-1.1.0.3/mgw

C:\Users\ksv\Downloads\engine-1.1.0.3\mgw>mingw32-make gost_engine
Scanning dependencies of target gost
[  4%] Building C object CMakeFiles/gost.dir/gost_ec_keyx.c.obj
gcc.exe: warning: C:/OpenSSL/lib/libcrypto.lib: linker input file unused because linking not done
[  8%] Building C object CMakeFiles/gost.dir/gost_ec_sign.c.obj
gcc.exe: warning: C:/OpenSSL/lib/libcrypto.lib: linker input file unused because linking not done
[ 12%] Building C object CMakeFiles/gost.dir/gost89.c.obj

как правильно указать путь к либе?
извиняюсь за такие вопросы, но я только учусь)

**Comment by beldmit** [comment]
К сожалению, очень давно не брал в руки компиляцию под Windows.

**Comment by ksv87** [comment]
решил проблему так:
- удалил gost12sum.c
- удалил gostsum.c
- скомпилил сразу все файлы, без разбивки по подпроектам gcc *.c -I"C:\Program Files\OpenSSL\include" -L"C:\Program Files\OpenSSL\lib" -lcrypto -shared -o test.dll

**Comment by ksv87** [comment]
gcc *.c -I"C:\Program Files\OpenSSL\include" -L"C:\Program Files\OpenSSL\lib" -lcrypto -DL_ENDIAN -shared -o test.dll

правильная команда для windows 10 pro x64
