### ISSUE TITLE
целостность этого сертификата не гарантирована возможно он поврежден гост 2012

### ISSUE THREAD

**Issue by ksv87** [gost-engine/engine#250]
Добрый день!

После генерации сертификата через openssl + gost_engine получается невалидный сертификат.

"Целостность этого сертификата не гарантирована возможно он поврежден"
"Этот сертификат содержит недействительную цифровую подпись."
![1](https://user-images.githubusercontent.com/15774585/82195012-60b8e080-9900-11ea-9bfb-754329bd6607.jpg)
![2](https://user-images.githubusercontent.com/15774585/82195018-6282a400-9900-11ea-85d8-41bf7e4c4e4c.jpg)

Возможно Вы сталкивались с такой проблемой

**Comment by beldmit** [comment]
Вы его ставите в Windows без установленного криптопровайдера с ГОСТ? Если да, то Windows про ГОСТ просто ничего не знает.

**Comment by ksv87** [comment]
У меня установлены Крипто ПРО и Випнет, тестовые сертификаты выпущенные ЦС и крипто про и випнет - работают, ошибок таких не пишут

**Comment by ksv87** [comment]
openssl req -x509 -newkey gost2012_256 -pkeyopt paramset:A -nodes -keyout key.pem -out cert.crt

**Comment by beldmit** [comment]
Сертификат у вас получился самоподписанный? Во-первых, надо проверить, что у вас в нём стоит флаг CA:true и импортировать как сертификат УЦ.

Во-вторых, надо смотреть на экстеншены по сравнению с теми, которые признаются.

**Comment by ksv87** [comment]
да, наверное дело в дефолтном конфиге опенссл, где бы найти рабочий конфиг для ГОСТ...

**Comment by ksv87** [comment]
интересно то, что по ГОСТ 2001 такой ошибки не возникает...

**Comment by ksv87** [comment]
```C:\Users\ksv\Downloads\testCA>openssl x509 -in ca.cer -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            b8:98:09:9e:f3:48:37:8d
    Signature Algorithm: GOST R 34.10-2012 with GOST R 34.11-2012 (256 bit)
        Issuer: C = RU, ST = vrn, L = vrn, O = Ksv Ltd
        Validity
            Not Before: May 18 10:54:23 2020 GMT
            Not After : May 18 10:54:23 2021 GMT
        Subject: C = RU, ST = vrn, L = vrn, O = Ksv Ltd
        Subject Public Key Info:
            Public Key Algorithm: GOST R 34.10-2012 with 256 bit modulus
                Public key:
                   X:A4677601CFF45634903D4D24A915DEB2AA8C1E71136E3AE06EB051A2D9AF3996
                   Y:1290E5B07BE519954EAB51AC5CD58EC6F9C5865FE1C120C75F5E4B010D8C6855
                Parameter set: id-GostR3410-2001-CryptoPro-A-ParamSet
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                34:63:4F:E5:BB:A1:87:1E:77:AD:E8:78:C7:9B:4C:B0:AF:57:F7:36
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Certificate Policies:
                Policy: 1.2.643.100.113.1
                Policy: 1.2.643.100.113.2
                Policy: X509v3 Any Policy

            Signing Tool of Subject:
                ..ksvpro
    Signature Algorithm: GOST R 34.10-2012 with GOST R 34.11-2012 (256 bit)
         35:cf:b8:62:ad:98:c8:b0:d6:93:e7:7e:2f:e0:78:b8:e4:24:
         93:41:17:27:d7:fb:8f:e8:f5:20:01:a3:60:af:95:d1:0d:28:
         49:e8:d0:85:60:67:bc:38:7c:46:5b:21:55:11:49:a2:bb:8a:
         f1:44:e0:83:9a:00:e3:ab:91:7a
```

От валидного сертификата ЦС отличается только информацией о Signing Tool of Subject и парой служебных оидов оснастки майкросовтовской, по выдаче сертификатов

**Comment by ksv87** [comment]
не могли бы Вы сформировать тестовый сертификат по 2012 госту и приложить к сообщению? так если ошибка останется - будет понятнее, дело в настройках openssl или нет

**Comment by beldmit** [comment]
К сожалению, грамотного самоподписанного сертификата со всеми расширениями у меня нет. Возможно, через некоторое время мы выложим на сайте cryptocom.ru скрипты для тестового УЦ.

**Comment by ksv87** [comment]
а демо версия криптоком openssl не доступна к скачиванию без запроса?

**Comment by beldmit** [comment]
Нет

**Comment by ksv87** [comment]
для чистоты эксперимента воспользовался статьей https://itnan.ru/post.php?c=1&p=353534
докер образ rnix/openssl-gost (дебиан)

создал там сертификат, скопировал к себе - ошибка та же, 
для ГОСТ 2012 - Этот сертификат содержит недействительную цифровую подпись.
для ГОСТ 2001 - Все хорошо.

пробовал копировать на машину где только 1 крипто про стоит - ошибка осталась.

может дело все же в коде подписи по гост 2012?

**Comment by beldmit** [comment]
До сих пор мне про такие ошибки никто не сообщал. 

Можете вытащить корневой сертификат КриптоПро CSP с Вашей машины, какой-нибудь подписанный на нём клиентский, и проверить подпись?

**Comment by ksv87** [comment]
прошу прощения, сертификат сформированный в докере на другой машине без ошибки, видимо что то с моим ПК.

**Comment by beldmit** [comment]
Возможно, проблема с определением ENDIANESS?
Тесты на дайджест проходят?

**Comment by ksv87** [comment]
возможно, скорее всего я что то криво собрал, тесты не компилировал... 
но если русскими буквами писать - кракозябры в сертификате получаются...

**Comment by ksv87** [comment]
да, дело было в том что я собрал без флага -DL_ENDIAN, с ним пересобрал - все ОК.
спасибо за помощь!
