### ISSUE TITLE
Files w/o copyright line

### ISSUE THREAD

**Issue by vt-alt** [gost-engine/engine#257]
```
gost-engine$ git grep -L -e Copyright -e Tishkov -- '*.[ch]'
gost_gost2015.c
gost_gost2015.h
test_keyexpimp.c
test_tlstree.c
```
Думаю, эти файлы хотят, чтоб в них добавили `Copyright`.

**Comment by beldmit** [comment]
Добавить можно, но если ты мне ещё и объяснишь, зачем это делают - будет круто

**Comment by vt-alt** [comment]
Чтоб копия файла отдельно от всего проекта содержала авторство (и лиценцию тоже бы неплохо). Копия может возникнуть, если кто-то захочет взять этот файл в свой проект. Еще вариант, когда кто-то хочет дополнить файл своим кодом и добавить кредит себе, но чтоб он не был первой строкой и не выглядел как будто бы он (она) присваивает себе чужое авторство.

Ну это кроме всяких легальных полезностей для исключительных ситуаций (в которых я не разбираюсь особо). https://softwarefreedom.org/resources/2012/ManagingCopyrightInformation.html

**Comment by vt-alt** [comment]
Попросил дать ещё мнение умных людей, вот что говорят:

> IANAL, но люди этой профессии говорили, что надо.

**Comment by beldmit** [comment]
Добавил

**Comment by vt-alt** [comment]
Спасибо!
