### ISSUE TITLE
Clang scan-build issues

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#258]
/home/beldmit/upstream/engine/test_sign.c:220:44: warning: Null pointer passed to 1st parameter expecting 'nonnull'
    T(EVP_PKEY_set_type_str(key1, algname, strlen(algname)));
                                           ^~~~~~~~~~~~~~~
/home/beldmit/upstream/engine/test_sign.c:23:23: note: expanded from macro 'T'
#define T(e) ({ if (!(e)) { \
                      ^
1 warning generated.
/home/beldmit/upstream/engine/benchmark/sign.c:93:16: warning: Null pointer passed to 1st parameter expecting 'nonnull'
                                data_len = atoi(optarg);
                                           ^~~~~~~~~~~~
/home/beldmit/upstream/engine/benchmark/sign.c:96:14: warning: Null pointer passed to 1st parameter expecting 'nonnull'
                                cycles = atoi(optarg);
                                         ^~~~~~~~~~~~
2 warnings generated.

**Comment by vt-alt** [comment]
По-моему этот баг находило Svace. Да, там бред написан.

**Comment by vt-alt** [comment]
JFYI. Что Svace писало:

DEREF_AFTER_NULL.EX;Critical;Average;Unspecified;Undecided;;sign.c;93;main;After having been compared to NULL value at sign.c:89, pointer 'optarg' is dereferenced at sign.c:93 by calling function 'atoi'.

**Comment by vt-alt** [comment]
А почему closed? "Бред написан" не в репорте, а в коде.
```
gost-engine ((a90ad6c...))$ bin/sign -l -
Segmentation fault
```

**Comment by beldmit** [comment]
Потому что туплю.
