### ISSUE TITLE
Openssl 1.0.2k 

### ISSUE THREAD

**Issue by batonser** [gost-engine/engine#269]
Всем доброго дня.
При накладывания патчей столкнулся с такой ошибкой, исходники openssl-1.0.2k
for p in ls ../engine/patches/1.0.2/; do patch -p1 < ../engine/patches/1.0.2/$p; done
patching file crypto/objects/obj_dat.h
patching file crypto/objects/obj_mac.h
patching file crypto/objects/obj_mac.num
patching file crypto/objects/obj_xref.h
patching file crypto/objects/obj_xref.txt
patching file crypto/objects/objects.txt
patching file crypto/asn1/a_mbstr.c
patching file crypto/asn1/a_strnid.c
Hunk #1 FAILED at 193.
1 out of 1 hunk FAILED -- saving rejects to file crypto/asn1/a_strnid.c.rej
patching file crypto/evp/evp_pbe.c
patching file crypto/pkcs12/p12_mutl.c
patching file crypto/cms/cms_sd.c
patching file crypto/pkcs7/pk7_smime.c

Действия таковы, скачал исходники, распаковал. Скачал ветку git clone -b openssl_1_0_2 https://github.com/gost-engine/engine.git.
Ну и собственно попробовал применить патчи. Помоги пжста. 

Вопреки тому что патч не совсем полностью наложился, все же решил проверить дальнейшие действия 
- ./config shared zlib
- make test
И получил следующее 
................
c_zlib.c:25:19: fatal error: zlib.h: No such file or directory
 # include <zlib.h>
            
compilation terminated.
make[4]: *** [c_zlib.o] Error 1
make[4]: Leaving directory `/root/1.0.2k/openssl-1.0.2k/crypto/comp'
make[3]: *** [subdirs] Error 1
make[3]: Leaving directory `/root/1.0.2k/openssl-1.0.2k/crypto'
make[2]: *** [build_crypto] Error 1
make[2]: Leaving directory `/root/1.0.2k/openssl-1.0.2k'
make[1]: *** [../libcrypto.a] Error 2
make[1]: Leaving directory `/root/1.0.2k/openssl-1.0.2k/test'
make: *** [tests] Error 2

**Comment by batonser** [comment]
C ошибкой zlib.h разобрался, не хватало пакета zlib-devel это для Центоса 7 , а вот про патчи актуально

**Comment by beldmit** [comment]
У Вас есть причины использовать именно 1.0.2 с патчами?

**Comment by batonser** [comment]
> У Вас есть причины использовать именно 1.0.2 с патчами?

Ну раз это возможно, то почему бы и нет ? А причина проста, openssl 1.0.2k используется php7, и теперь что бы php7 принял новый openssl(выше версией) мне нада соберать php из сорцов как и nginx c апачем. Что усложняет процесс общей задачи. Поэтому я бы хотел пропатчить именно версию openssl 1.0.2к.

**Comment by beldmit** [comment]
Покажите rej-файл. Но для PHP скорее всего этим можно пренебречь, это вывод числовых строк в сертификатах скорее всего.

**Comment by batonser** [comment]
# cat nano crypto/asn1/a_strnid.c.rej
cat: nano: No such file or directory
--- crypto/asn1/a_strnid.c
+++ crypto/asn1/a_strnid.c
@@ -193,7 +193,10 @@
     {NID_dnQualifier, -1, -1, B_ASN1_PRINTABLESTRING, STABLE_NO_MASK},
     {NID_domainComponent, 1, -1, B_ASN1_IA5STRING, STABLE_NO_MASK},
     {NID_ms_csp_name, -1, -1, B_ASN1_BMPSTRING, STABLE_NO_MASK},
-    {NID_jurisdictionCountryName, 2, 2, B_ASN1_PRINTABLESTRING, STABLE_NO_MASK}
+    {NID_jurisdictionCountryName, 2, 2, B_ASN1_PRINTABLESTRING, STABLE_NO_MASK},
+    {NID_INN, 1, 12, B_ASN1_NUMERICSTRING, STABLE_NO_MASK},
+    {NID_OGRN, 1, 13, B_ASN1_NUMERICSTRING, STABLE_NO_MASK},
+    {NID_SNILS, 1, 11, B_ASN1_NUMERICSTRING, STABLE_NO_MASK}
 };
 
 static int sk_table_cmp(const ASN1_STRING_TABLE *const *a,

**Comment by beldmit** [comment]
В общем, думаю, Вам это не нужно. Можете приложить патч по смыслу самостоятельно (там, кажется, сортировка по NID), можете вообще забить.

**Comment by batonser** [comment]
> В общем, думаю, Вам это не нужно. Можете приложить патч по смыслу самостоятельно (там, кажется, сортировка по NID), можете вообще забить.

Вы имеете ввиду можно пропустить данную ошибку и продолжать дальше ?

**Comment by beldmit** [comment]
Скорее всего да.

**Comment by batonser** [comment]
Хорошо, Спасибо что откликнулись.
