### ISSUE TITLE
Travis builds

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#270]
Travis has stopped reporting its results to the engine build. It should be fixed.

**Comment by vt-alt** [comment]
Думаю, его надо удалить/добавить заново.

**Comment by beldmit** [comment]
Возникла у меня одна мысль, ща проверю.

**Comment by chipitsine** [comment]
там только задания по расписанию https://travis-ci.org/github/gost-engine/engine/requests


у кого есть админские права, посмотрите в 

https://github.com/gost-engine/engine/settings/hooks
https://github.com/gost-engine/engine/settings/installations

есть там травис ? и там историю посмотреть можно

**Comment by beldmit** [comment]
Я удалил Travis из settings/hooks и он вроде как прописался в settings/installations

**Comment by beldmit** [comment]
Вроде заработало. Спасибо!

**Comment by vt-alt** [comment]
Спасибо!
