### ISSUE TITLE
Current master fails test6 with OpenSSL-3

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#276]
MacOS 10.15.6, Xcode-11.7, current master of OpenSSL, current master of gost-engine:
```
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /Users/ur20980/src/grasshopper-engine/build
      Start  1: digest
 1/10 Test  #1: digest ...........................   Passed    0.08 sec
      Start  2: ciphers
 2/10 Test  #2: ciphers ..........................   Passed    0.05 sec
      Start  3: curves
 3/10 Test  #3: curves ...........................   Passed    0.03 sec
      Start  4: parameters
 4/10 Test  #4: parameters .......................   Passed    0.03 sec
      Start  5: derive
 5/10 Test  #5: derive ...........................   Passed    0.06 sec
      Start  6: sign/verify
 6/10 Test  #6: sign/verify ......................Child aborted***Exception:   0.01 sec
      Start  7: TLS
 7/10 Test  #7: TLS ..............................   Passed    0.89 sec
      Start  8: context
 8/10 Test  #8: context ..........................   Passed    0.02 sec
      Start  9: keyexpimp
 9/10 Test  #9: keyexpimp ........................   Passed    0.01 sec
      Start 10: gost89
10/10 Test #10: gost89 ...........................   Passed    0.01 sec

90% tests passed, 1 tests failed out of 10

Total Test time (real) =   1.20 sec

The following tests FAILED:
	  6 - sign/verify (Child aborted)
Errors while running CTest
make: *** [test] Error 8
```

![Screen Shot 2020-09-08 at 14 30 37](https://user-images.githubusercontent.com/5923577/92514419-e0382b80-f1df-11ea-9c1f-859940b488f0.png)

**Comment by beldmit** [comment]
Sorry, but I cannot reproduce it :(
I've just rebuilt both openssl and engine from scratch.

**Comment by mouse07410** [comment]
> Sorry, but I cannot reproduce it :(

Strange... I have it on the `master`, and `openssl_1_1_1` branch is worse:
```
. . . . .
50% tests passed, 5 tests failed out of 10

Total Test time (real) =   7.32 sec

The following tests FAILED:
          3 - parameters (Child aborted)
          4 - sign/verify (Failed)
          5 - TLS (Child aborted)
          7 - grasshopper (Failed)
          8 - keyexpimp (Failed)
Errors while running CTest
```

Here are the complete build+test logs:
- for branch `openssl_1_1_1` with system-wide install of OpenSSL-1.1.1g: [ossl111-build-bad.txt](https://github.com/gost-engine/engine/files/5190862/ossl111-build-bad.txt)
- for branch `master` with locally-installed OpenSSL 3.0.0-alpha7-dev: [ossl3-build.txt](https://github.com/gost-engine/engine/files/5190881/ossl3-build.txt)

**Comment by beldmit** [comment]
Could you please add a separate bug report for the 1.1.1 branch? I'll try to reproduce it and fix any problems.

Yes, I use Linux and it can be a reason for not-reproducing the bug. I've seen @levitte's fix for the `store_lib.c`, many thanks!

**Comment by mouse07410** [comment]
> Could you please add a separate bug report for the 1.1.1 branch? I'll try to reproduce it and fix any problems.

Will do.
