### ISSUE TITLE
Не могу собрать gost-engine

### ISSUE THREAD

**Issue by VVSite** [gost-engine/engine#28]
Доброго времени суток!
Пытаюсь собрать из Ваших исходников gost-engine по инструкции Build, команда 
**make TOP=../openssl-1.0.2d**
я уже по всякому менял, и l вместо d (openssl 1.0.2l),  выдает ошибку:
**make: *** Не заданы цели и не найден make-файл.  Останов.**
Если пытаюсь собрать по инструкции CMake_Readme.md из проекта, то сыпятся ошибки (вывод в прицепе)
Версия Linux FC19(требование заказчика), openssl - 1.0.2l (с сайта)
[gost-engine-make-error.txt](https://github.com/gost-engine/engine/files/1101574/gost-engine-make-error.txt)

**Comment by beldmit** [comment]
Для сборки с версией 1.0.2 надо выписать соответствующую ветку, применить к исходникам openssl патчи из этой ветки и заменить ту версию engine, которая в исходниках openssl на выписанную копию.

**Comment by VVSite** [comment]
Спасибо за ответ. А в каком из файлов проекта лежит инструкция как это все сделать?

**Comment by beldmit** [comment]
Ни в каком :(
Patches are welcome.

**Comment by beldmit** [comment]
Для версии 1.1.0 всё несколько лучше.

**Comment by VVSite** [comment]
Да, с 1.1.0 получилось.

**Comment by golubkovden** [comment]
@VVSite можешь рассказать как собрал с 1.1 ?

**Comment by beldmit** [comment]
Вообще там в README всё написано. 
cmake -DCMAKE_C_FLAGS=...
make
