### ISSUE TITLE
gost_cipher_do_cbc multiple blocks decryption is failing

### ISSUE THREAD

**Issue by wbeck10** [gost-engine/engine#281]
Hi there,

We have found an issue regarding to encrypt gost with cbc. Multiple blocks decryption doesn't work in our case.
After adding following patch it works:
```
/* GOST encryption in CBC mode */
static int gost_cipher_do_cbc(EVP_CIPHER_CTX *ctx, unsigned char *out,
                       const unsigned char *in, size_t inl)
{
    unsigned char b[8];
    const unsigned char *in_ptr = in;
    unsigned char *out_ptr = out;
    int i;
    struct ossl_gost_cipher_ctx *c = EVP_CIPHER_CTX_get_cipher_data(ctx);
    unsigned char *iv = EVP_CIPHER_CTX_iv_noconst(ctx);
    if (EVP_CIPHER_CTX_encrypting(ctx)) {
        while (inl > 0) {
            for (i = 0; i < 8; i++) {
                b[i] = iv[i] ^ in_ptr[i];
            }
            gostcrypt(&(c->cctx), b, out_ptr);
            memcpy(iv, out_ptr, 8);
            out_ptr += 8;
            in_ptr += 8;
            inl -= 8;
        }
    } else {
        while (inl > 0) {
+          unsigned char tmpiv[8];
            gostdecrypt(&(c->cctx), in_ptr, b);
+          memcpy(tmpiv, in_ptr, 8);
            for (i = 0; i < 8; i++) {
                out_ptr[i] = iv[i] ^ b[i];
            }
-          memcpy(iv, in_ptr, 8);
+          memcpy(iv, tmpiv, 8);
            out_ptr += 8;
            in_ptr += 8;
            inl -= 8;
```

**Comment by beldmit** [comment]
Well. 

CBC mode implies padding (see, e.g, https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_block_chaining_(CBC)) when data blocks are not full. If your data size has a reminder other than 0 dividing to block size, you should pad it.

**Comment by wbeck10** [comment]
Sorry for being unclear. I didn't know that github displays the diff as a pullet point list.
The diff can be shown here:
https://github.com/gost-engine/engine/compare/master...wbeck10:master =>
@@ -575,11 +622,13 @@ static int gost_cipher_do_cbc(EVP_CIPHER_CTX *ctx, unsigned char *out,

The initialization vector wasn't restored.

**Comment by vt-alt** [comment]
You can post diff if you quote it between `~~~` lines, like this:
```
~~~
diff...
~~~
```

**Comment by beldmit** [comment]
I've updated the original comment to show diff correctly.

**Comment by vt-alt** [comment]
Regarding `test_ciphers`, yes, NID_gost89_cbc is not tested. Would be good to have some test vector data for it.

**Comment by beldmit** [comment]
@wbeck10, could you please submit some test cases? The best option is smth using the `openssl enc` command-line utility.

**Comment by wbeck10** [comment]
Yes I'll do it tomorrow.
It is quite late now in Down Under.
Cheers,
 WB

**Comment by vt-alt** [comment]
Example:
~~~
$ head -c12345 /dev/urandom > a
$ openssl enc -gost89-cbc -k test -pbkdf2 -e -in a -out encrypted-file
$ openssl enc -gost89-cbc -k test -pbkdf2 -d -in encrypted-file -out b
$ sha1sum a b
d9486d02348c949705efd8196142651046c7ab95  a
d9486d02348c949705efd8196142651046c7ab95  b
~~~

**Comment by beldmit** [comment]
This is without any patch, isn't it?

**Comment by vt-alt** [comment]
Oh, yes.

**Comment by vt-alt** [comment]
Well, `openssl enc` will not reproduce the error, because, fix is for in-place decryption.

**Comment by beldmit** [comment]
Fair point.

**Comment by beldmit** [comment]
@wbeck10 could you submit a PR? At least fixing the wrong behavior without tests...

**Comment by wbeck10** [comment]
Sorry about the delay, I was quite loaded with work yesterday, however I was able to get a test vector:
key= 3031323334353637303132333435363730313233343536373031323334353637
iv=37363534333231303031323334353637
plaintext=48656c6c6f576f726c642d3132333435 => which is "HelloWorld-12345"
crypttext=6f72f47a5440052aba8f21ccb1956d05

**Comment by wbeck10** [comment]
Can you give me access rights to create a branch?
git push --set-upstream origin fix_281
Username for 'https://github.com': wbeck10
Password for 'https://wbeck10@github.com': 
remote: Permission to gost-engine/engine.git denied to wbeck10.
fatal: unable to access 'https://github.com/gost-engine/engine.git/': The requested URL returned error: 403

**Comment by beldmit** [comment]
If I understand correctly, you should fork the gost-engine repo, commit to it, and create a PR.
