### ISSUE TITLE
Поддержка TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC и TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC ?

### ISSUE THREAD

**Issue by fdn721** [gost-engine/engine#282]
Добрый день.

gost-engine поддерживает следующие Cipher Suite:

TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC
TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC

?

**Comment by beldmit** [comment]
Сейчас, кажется, нет. Там надо сделать минимальные доработки и тогда будет.

**Comment by Voldemar0** [comment]
Привет!

Я правильно понимаю, что пока использовать TLS с Кузнечиком невозможно ?
Т.е. обе ciphersuite из readme: GOST2001-GOST89-GOST89 и GOST2012-GOST8912-GOST8912 - это Магма и других вариантов в стабильных релизах пока нет ?

**Comment by beldmit** [comment]
В 3.x уже есть. Но там нет гостового TLS 1.3
