### ISSUE TITLE
GOST elliptic curve algorithms for digital signatures and key exchange

### ISSUE THREAD

**Issue by pedroalbanese** [gost-engine/engine#285]
Hi,

I am trying to create an elliptical curve based key pair, but I can't do it with the ids listed here.

In LibreSSL I can create through the commands:

libressl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:id-GostR3410-2001-CryptoPro-XchA-ParamSet -pkeyopt ec_param_enc:named_curve
and
libressl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:id-tc26-gost-3410-2012-512-paramSetB -pkeyopt ec_param_enc:named_curve

but when I try in OpenSSL by the command:
openssl ecparam -engine gost -name id-Gost28147-89-CryptoPro-A-ParamSet

I get the following error:
unable to create curve (id-Gost28147-89-CryptoPro-A-ParamSet)

How do I create EC key with GOST in OpenSSL? I mean, how do I get the shared key by derivation with GOST?

Thanks in advance.

**Comment by vt-alt** [comment]
https://github.com/gost-engine/engine/blob/master/README.gost 1. Generation of private key

**Comment by pedroalbanese** [comment]
Sorry, I read this document before and I didn't understand it.

I'll explain my question better using SM2 as an example:

In LibreSSL I can perform the following operation:

openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve: sm2 -out sm2key1.txt
openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve: sm2 -out sm2key2.txt

openssl pkey -pubout -in sm2key1.txt -out sm2pubkey1.txt
openssl pkey -pubout -in sm2key2.txt -out sm2pubkey2.txt

openssl pkeyutl -derive -inkey sm2key1.txt -peerkey sm2pubkey2.txt -out shared1.txt
openssl pkeyutl -derive -inkey sm2key2.txt -peerkey sm2pubkey1.txt -out shared2.txt

openssl enc -e -sm4 -md sm3 -pbkdf2 -iter 10000 -kfile shared1.txt -in plain.txt -out cipher.txt
openssl enc -d -sm4 -md sm3 -pbkdf2 -iter 10000 -kfile shared2.txt -in cipher.txt -out plain.txt

I would like to know how to do it with GOST, because it is possible in LibreSSL, in the previous example.

**Comment by pedroalbanese** [comment]
According to documents, the parameters XA, XB are for key exchange, however when I try to derive the sum of the keys with pkeyutl -derive, I get the following error:

3104: error: 8107A07D: lib (129): PKEY_GOST_EC_DERIVE: ukm not set: C: \ OpenSSL-Win32 \ en
gine \ gost_ec_keyx.c: 120:

**Comment by beldmit** [comment]
See examples here:

https://github.com/gost-engine/engine/blob/874d48d88c6b69c7f2f6765b0c9bfae6585ac8e4/test/04-pkey.t#L299-L325

**Comment by pedroalbanese** [comment]
I trying via commandline. 

This command don't work with GOST keys (at least by command line):
"openssl pkeyutl -derive -inkey bob.prv -keyform PEM -peerkey malice.pub -peerform PEM -pkeyopt ukmhex:0100000000000000 -out secret_m.bin"

I get the error:
pkeyutl: Can't set parameter "ukmhex:0100000000000000":

The example describes exactly what I need, but not with GOST. I need to derive the shared secret, by command line, but from GOST keys:

openssl pkeyutl -engine gost -derive -inkey GOSTPivkey1.txt -peerkey GOSTPubkey2.txt -out shared.txt

 Is this not possible in OpenSSL? I imagine so, because it is possible in LibreSSL.

**Comment by beldmit** [comment]
First of all, what branch(es) of openssl and gost-engine do you use?

**Comment by pedroalbanese** [comment]
Now, OpenSSL 1.1.1h, libengine-gost-openssl1.1-1.1.0.1.

**Comment by beldmit** [comment]
Try to build gost-engine from the 1_1_1 branch. The ukmhex option appeared there.

**Comment by pedroalbanese** [comment]
Don't joke that I have to compile this. I'm on Windows. I don't even know where to find branch 1_1_1. Where do I download it?

But this function has been widely disseminated in the documentation since at least 2016. Why? Since version 1.0.0 of OpenSSL, the key exchange function is described in the GOST Engine. The XA, XB paramset were developed for this purpose.

LibreSSL itself, which is a version 1.0.2 fork, has this capability. I believe it is not properly documented, but there would be no reason to announce this feature without it being available in previous versions.

Anyway, in Kali and Debian, both updated, I can't do the derivation either.

**Comment by beldmit** [comment]
Sure. This function is present since 1.0.2. But till 1.1.1 nobody wanted to test it via the command line.

https://github.com/gost-engine/engine/tree/openssl_1_1_1 is the link to the 1.1.1 branch of the gost-engine.

**Comment by pedroalbanese** [comment]
I can't compile:

CMake Error at C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  suitable version "1.1.1h", minimum required is "1.1.1")
Call Stack (most recent call first):
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by beldmit** [comment]
Sorry, can't assist you because of a lack of a Windows machine.

**Comment by pedroalbanese** [comment]
Same way with version 1.1.2 also it asks for at least one previous version ¬¬

CMake Error at C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  suitable version "1.1.2", minimum required is "1.1.1")
Call Stack (most recent call first):
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by pedroalbanese** [comment]
I will give up on this attempt. I compiled and installed version 1.1.1, but it doesn't work. Thx.

CMake Error at C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found
  suitable version "1.1.1", minimum required is "1.1.1")
Call Stack (most recent call first):
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/msys32/mingw32/share/cmake-3.18/Modules/FindOpenSSL.cmake:486 (find_package_handle_standard_args)
  CMakeLists.txt:11 (find_package)

**Comment by pedroalbanese** [comment]
The bug is registered. MSYS2

**Comment by DJm00n** [comment]
@pedroalbanese have you tried to provide path to OpenSSL to CMake via `-DOPENSSL_ROOT_DIR=/PATH/TO/OPENSSL/`?
See https://github.com/gost-engine/engine/blob/master/INSTALL.md for details.

**Comment by pedroalbanese** [comment]
Sorry, but GOST R 34.13–2015 - Symmetric cypher Grasshopper ("Kuznechik"), is GOST R 34.12–2015..
I remember writing it wrong somewhere as well
https://github.com/gost-engine/engine/blob/master/README.gost

**Comment by pedroalbanese** [comment]
I wrote my own VKO system, see: https://github.com/pedroalbanese/gosttk

Thanks to Dmitry, Thanks to GOST Engine team!
