### ISSUE TITLE
Ошибка при формировании ключа

### ISSUE THREAD

**Issue by VVSite** [gost-engine/engine#29]
Снова здравствуйте! Выполняю команду:
**openssl genpkey -algorithm gost2012_512 -pkeyopt paramset:A -out seckey.pem -gost89-cnt-12 -pass pass:hello**

выдает ошибку: 
**Error writing key
140489600395072:error:0D0A706C:asn1 encoding routines:PKCS5_pbe2_set_iv:cipher has no object identifier:crypto/asn1/p5_pbev2.c:53:
140489600395072:error:2307D00D:PKCS12 routines:PKCS8_encrypt:ASN1 lib:crypto/pkcs12/p12_p8e.c:32:**

Вывод команды **openssl engine -c** :
(dynamic) Dynamic engine loading support
(gost) Reference implementation of GOST engine
 [gost89, gost89-cnt, gost89-cnt-12, gost89-cbc, grasshopper-ecb, grasshopper-cbc, grasshopper-cfb, grasshopper-ofb, grasshopper-ctr, md_gost94, gost-mac, md_gost12_256, md_gost12_512, gost-mac-12, gost2001, gost-mac, gost2012_256, gost2012_512, gost-mac-12]

**Comment by beldmit** [comment]
Какая версия openssl?

**Comment by VVSite** [comment]
Собрал свежую, которая на оф. сайте 
OpenSSL 1.1.0f  25 May 2017

**Comment by beldmit** [comment]
Если я правильно помню, то тут нужно указывать в качестве алгоритма шифрования -gost89, оно автоматом возьмёт параметры 2012 года и всё будет работать.

**Comment by beldmit** [comment]
Отдельного OID-а для gost89-cnt в природе нет.

**Comment by VVSite** [comment]
А, понятно. С gost89 работает корректно.
