### ISSUE TITLE
centos 8 / openssl_1_1_1 issue

### ISSUE THREAD

**Issue by sergeeximius** [gost-engine/engine#294]
Добрый день
По инструкции сделал следующее:

```
$ dnf install openssl-devel cmake make 
$ git clone --branch openssl_1_1_1 https://github.com/gost-engine/engine.git
$ cd engine && mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ cmake --build . --config Release
$ cmake --build . --target install --config Release
```

Конфиг взял example.conf и положил в /etc/pki/tls/openssl.cnf взамен родного. При этом вижу что openssl подцепила gost, но не вижу чтобы были криптоалгоритмы gost.

```
$ openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support
(gost) Reference implementation of GOST engine
$ openssl ciphers -v | grep GOST
$
```

Похоже что-то я недоделал, а что не могу понять, так как инструкция на этом заканчивается. Подскажите, plz.
Делал по заявке от разработчиков, они говорят что их скрипт которому нужен был ГОСТ в итоге работает. Так что я несколько в ступоре.

**Comment by beldmit** [comment]
А как вы проверяете наличие криптоалгоритмов ГОСТ?

```openssl dgst -md_gost12_256 somefile``` что выдаёт?

**Comment by sergeeximius** [comment]
Проверяю такой командой:
`$ openssl ciphers -v`

Вот результат той что вы привели:
```
$ openssl dgst -md_gost12_256 task
md_gost12_256(task)= 3f539a213e97c802cc229d474c6aa32a825a360b2a933a949fd925208d9ce1bb
```

**Comment by beldmit** [comment]
Это значит, что алгоритмы ГОСТ присутствуют. 
Если у вас RedHat-based дистрибутив, то там есть дополнительные меры по ограничению шифронаборов, https://access.redhat.com/articles/3666211

**Comment by sergeeximius** [comment]
Да, у меня CentOS 8.
Ок, спасибо за разъяснения.
