### ISSUE TITLE
Программное использование движка

### ISSUE THREAD

**Issue by ksv87** [gost-engine/engine#303]
Добрый день, подскажите, возможно ли в своём приложении на c++ использовать данный движок? Программно работать со стандартным libcrypto разобрался как, а как прикрутить ГОСТ не пойму... Подскажите, пожалуйста

**Comment by beldmit** [comment]
Ну либо грузить конфиг с прописанным в него gost-engine явным образом (и это предпочтительно), либо звать `ENGINE_by_id('gost')`

**Comment by ksv87** [comment]
А как это сработает, я думал что когда использую libcrypto моя программа будет работать и на системах без установленного openssl, в папке с программой будет dll libcrypto, а  dll движка нужно будет просто положить в папку engine в директории с exe?

**Comment by beldmit** [comment]
Укажете путь к файлу конфигурации, и сработает

**Comment by ksv87** [comment]
Я просто не использовал явным образом файл конфигурации, видимо нужно изучить это, спасибо
