### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by pedroalbanese** [gost-engine/engine#305]
Hi Dmitry,

How do I compile for Android? I have the static Openssl 1.1.1 binary for armel that runs on my Android. I would like to know how to compile gost.so static for armv6, because I can't use the GOST Engine there.

Thanks in advance.

**Comment by beldmit** [comment]
If there is no engine support on Android, I'm afraid you have to add some parts of the engine code to the OpenSSL build tree yourself

**Comment by pedroalbanese** [comment]
I ended up compiling openssl 1.0.2, with support only for gost98, cryptopro and 2001. I don't have support for the -pbkdf2 function, but it's working. If there are any tips on how to compile with the branch vt_alt_openssl_1_0_2_alt, I would like to know.

**Comment by pedroalbanese** [comment]
What exactly "Compatibility: OpenSSL 1.0.2 (needs patches)" means? In vt_alt_openssl_1_0_2_alt. Is it possible to compile this version of the library in version 1.0.2 of Openssl? What I need to do?

**Comment by beldmit** [comment]
If I remember correctly, you have to patch the OpenSSL sources. The patches are present in the sources.

**Comment by beldmit** [comment]
Could you please explain what do you want to get and what is the purpose of what you want to get? Maybe I will be able to help you better

**Comment by pedroalbanese** [comment]
I need a static OpenSSL binary with GOST Engine support to run on an Android armel. I managed to compile version 1.0.2t, which has support for GOST89, CryptoPro, and 2001. I can only compile this version statically. In later versions of OpenSSL, gost.so and gost.dll cannot be compiled statically. So I would like to know how to compile version 1.0.2t, with branch 1_1_0 of GOST Engine, for example (which says it supports this version of OpenSSL). I need support for the Streebog and Kuznyechik algorithms in version 1.0.2t of OpenSSL, to be a static build (otherwise it doesn't run on Android).

How do I apply the patches? Is it manually? I would like to understand how to compile some two branches against version 1.0.2.

**Comment by beldmit** [comment]
Yes, you have to apply the patches manually. I am also not sure whether it is possible to provide a statical linkage with engine.

**Comment by beldmit** [comment]
BTW, why do you want Magma and Kuznyechik? They will be almost unusable with OpenSSL 1.0.2 - neither CMS function nor TLS will not be available, so only low-level EVP mode will be available.

**Comment by pedroalbanese** [comment]
More precisely Streebog and Kuznyechik, for symmetric encryption, I just thought there was a usual known way of doing it, since branch 1_1_0 cites compatibility with version 1.0.2 of OpenSSL, so I thought it was nothing exceptional.

**Comment by beldmit** [comment]
Sure, it will work for symmetric encryption.

**Comment by pedroalbanese** [comment]
I just needed something like this:
https://github.com/pedroalbanese/gosttk

Symmetric encryption, digital signature and VKO. Only.

I had to write it myself, and this is compatible with Android / WindowsXP / Kali / Mac. Soon will support TLS 1.3

I would love to be able to use GOST Engine on Android, but it was easier to rewrite part of the functions than to compile the program statically properly. Tips are welcome.

I really appreciate the attention.
