### ISSUE TITLE
Compatibility with OpenSSL-1.0.2 is broken

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#31]
The title says it all: it seems impossible to build this engine with OpenSSL-1.0.2 any more. And 1.0.2 is the current standard for the vast majority of the deployed applications (those that aren't stuck with 0.9.8 :), so it is infeasible to replace the standard OpenSSL installation (which is 1.0.2l) with 1.1...

**Comment by beldmit** [comment]
You should take the branch matching to openssl 1.0.2 and add some patches (included in repo) to openssl. It's a deliberate decision.

**Comment by mouse07410** [comment]
> You should take the branch matching to openssl 1.0.2

OK, that's fair.

> and add some patches (included in repo) to openssl

And this is not - an engine should not require modification to the stock OpenSSL. For example, while I do maintain a (separate) 1.1 installation, the operational OpenSSL is 1.0.2l. I do not want to create a custom fork of it.

> It's a deliberate decision.

Regarding branching - understood. That's fine. Regarding the need to patch the OpenSSL source - I urge you to reconsider.

**Comment by beldmit** [comment]
Well, we have the gost engine with GOST2001 algorithm as a part of openssl 1.0.2. If you need newer algorithms, you need a lot of OIDs for it. So you have to apply this patches.

**Comment by mouse07410** [comment]
>  If you need newer algorithms, you need a lot of OIDs for it. So you have to apply this patches.

You have a point. 

But branch `openssl_1_0_2` still does not even try to compile:
```
$ git branch
  master
* openssl_1_0_2
$ make
(cd ../..; /Applications/Xcode.app/Contents/Developer/usr/bin/make DIRS=engines sub_all)
make[1]: *** No rule to make target `sub_all'.  Stop.
make: *** [top] Error 2
$
```

**Comment by beldmit** [comment]
It's a bug in documentation :(
The code in openssl_1_0_2 is not designed for compiling outside the openssl sources tree, so you have to copy it instead of the existing ccgost engine.

**Comment by mouse07410** [comment]
> It's a bug in documentation :(

Happens... Might I ask to have it fixed? ;-)

> The code in openssl_1_0_2 is not designed for compiling outside the openssl sources tree, so you have to copy it instead of the existing ccgost engine.

Are patches still necessary? All of those in `patches/1.0.2` directory?

**Comment by beldmit** [comment]
I'll try to fix it when I return home. For a long time the only user of this code was a company that knew about this behaviour, so now when new users appear I have to fix it.

Yes, you need all those patches.
