### ISSUE TITLE
MacOS: Master fails one test in a strange way

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#311]
MacOS 10.15.7, Xcode-12.4, current master.
```
.  .  .  .  .
10/11 Test #10: gost89 ...........................   Passed    0.01 sec
      Start 11: engine
11/11 Test #11: engine ...........................***Failed    4.18 sec

91% tests passed, 1 tests failed out of 11

Total Test time (real) =   6.26 sec

The following tests FAILED:
	 11 - engine (Failed)
Errors while running CTest
```
and
```
.  .  .  .  .
11: ok 48 - CBC short text, paramset D - decrypted correctly
11: ok
11:     # Failed test 'Read and print public key gost2001:A'
11:     # at 04-pkey.t line 136.
11:     # +-------------------------------+----+-------------------------------+
11:     # | GOT                           | OP | CHECK                         |
11:     # +-------------------------------+----+-------------------------------+
11:     # | Private key: <undefined>\n    | eq | Public key:\n                 |
11:     # | Public key:\n                 |    |    X:789094AF6386A43AF191210F |
11:     # |    X:789094AF6386A43AF191210F |    | FED0AEA5D1D9750D8FF8BCD1B584B |
11:     # | FED0AEA5D1D9750D8FF8BCD1B584B |    | FAA966850E4\n                 |
11:     # | FAA966850E4\n                 |    |    Y:25ED63EE42624403D08FC60E |
11:     # |    Y:25ED63EE42624403D08FC60E |    | 5F8130F121ECDC5E297D9E3C7B106 |
11:     # | 5F8130F121ECDC5E297D9E3C7B106 |    | C906E0855E9\n                 |
11:     # | C906E0855E9\n                 |    | Parameter set: id-GostR3410-2 |
11:     # | Parameter set: id-GostR3410-2 |    | 001-CryptoPro-A-ParamSet\n    |
11:     # | 001-CryptoPro-A-ParamSet\n    |    |                               |
11:     # +-------------------------------+----+-------------------------------+
11:     # Failed test 'Read and print public key gost2001:B'
11:     # at 04-pkey.t line 136.
11:     # +-------------------------------+----+-------------------------------+
11:     # | GOT                           | OP | CHECK                         |
11:     # +-------------------------------+----+-------------------------------+
11:     # | Private key: <undefined>\n    | eq | Public key:\n                 |
11:     # | Public key:\n                 |    |    X:59C15439385CBE790274D653 |
11:     # |    X:59C15439385CBE790274D653 |    | 7D318A35B27413D265FFDC5FBE535 |
11:     # | 7D318A35B27413D265FFDC5FBE535 |    | 4DF8C7AC591\n                 |
.  .  .  .  . [many more of the above] .  .  .  .  .
```

Here are the complete log: [ossl3-build.txt](https://github.com/gost-engine/engine/files/5912659/ossl3-build.txt)

**Comment by beldmit** [comment]
hmmm... I see these tests aren't running on my current machine at all. Will take a look. Thanks!

**Comment by beldmit** [comment]
Got able to reproduce.

**Comment by mouse07410** [comment]
> Got able to reproduce.

Wonder if it's "got" or "not". :-)

Seriously, on one machine it fails, on another machine it passes. On both of my machines *all* of the other tests pass (both `master` and `openssl_1_1_1` branches).

Also, on my machines there are *three* OpenSSL installations: OS-provided `/usr/bin/openssl` that's pretty much good-for-nothing, `/opt/local/bin/openssl` v1.1.1g that's fully functional, and used for most everything - apps that I brought in or wrote myself. Then there's `$HOME/openssl-3/bin/openssl` v3.0, which is not used except for testing.

**Comment by beldmit** [comment]
Got :)
Will take a look, suspect an openssl regression

**Comment by beldmit** [comment]
Could you please current build? Works for me now.

**Comment by mouse07410** [comment]
> Could you please test the current build? Works for me now.

Thanks for waiting for my report. Yes, the current master (as of today) works fine with OpenSSL-3.0. All the tests pass.

**Comment by beldmit** [comment]
Great! Thanks

**Comment by mouse07410** [comment]
Please re-open. Today's master fails the 11th test:
```
Running tests...
/opt/local/bin/ctest --force-new-ctest-process 
Test project /Users/uri/src/grasshopper-engine/build
      Start  1: digest
 1/11 Test  #1: digest ...........................   Passed    0.12 sec
      Start  2: ciphers
 2/11 Test  #2: ciphers ..........................   Passed    0.06 sec
      Start  3: curves
 3/11 Test  #3: curves ...........................   Passed    0.05 sec
      Start  4: parameters
 4/11 Test  #4: parameters .......................   Passed    0.05 sec
      Start  5: derive
 5/11 Test  #5: derive ...........................   Passed    0.10 sec
      Start  6: sign/verify
 6/11 Test  #6: sign/verify ......................   Passed    0.21 sec
      Start  7: TLS
 7/11 Test  #7: TLS ..............................   Passed    1.11 sec
      Start  8: context
 8/11 Test  #8: context ..........................   Passed    0.02 sec
      Start  9: keyexpimp
 9/11 Test  #9: keyexpimp ........................   Passed    0.01 sec
      Start 10: gost89
10/11 Test #10: gost89 ...........................   Passed    0.01 sec
      Start 11: engine
11/11 Test #11: engine ...........................***Failed    3.98 sec

91% tests passed, 1 tests failed out of 11

Total Test time (real) =   5.73 sec

The following tests FAILED:
	 11 - engine (Failed)
Errors while running CTest
make: *** [test] Error 8
```

Details: [test-3-long-out.txt](https://github.com/gost-engine/engine/files/5992119/test-3-long-out.txt)

Also, the current CMakeLists.txt (or whatever) apparently broke the naming for the engine binary? On MacOS it used to be `gost.3.0.dylib` (when built for the OpenSSL-3.0 master), but now it is `gost.so`?

**Comment by levitte** [comment]
Unfortunately, the detailed log isn't detailed enough.  STDERR is redirected to `tests.err` by the engine recipes, it would have given you an idea of what's going on.

However, your point about the changed module name gave me all the information needed.  See, OpenSSL has the idea that dynamically loadable modules should be name *whatever*.dylib.  At the time that this was decided (20+ years ago at this point), that was the general idea.  It seems that this has shifted in modern times, and cmake among others seem to think they should be named *whatever*.so.
I've a quick fix for CMakeLists.txt, PR coming up!

**Comment by levitte** [comment]
See #315.

**Comment by mouse07410** [comment]
> Unfortunately, the detailed log isn't detailed enough. STDERR is redirected to tests.err by the engine recipes, it would have given you an idea of what's going on.

Understood. Next time I'll provide `test.err` as well. Here's the one from Feb 13th that (probably) is responsible for the error: [tests.err.txt](https://github.com/gost-engine/engine/files/5998134/tests.err.txt)

> However, your point about the changed module name gave me all the information needed.

Excellent. I must add that today's master (changes only in `CMakeLists.txt`, it seems) passes all the tests:  [test-3-out.txt](https://github.com/gost-engine/engine/files/5998139/test-3-out.txt)

Do you still want me to take a look at #315?

**Comment by beldmit** [comment]
No in fact. Many thanks!
