### ISSUE TITLE
О маршрутизаторах

### ISSUE THREAD

**Issue by 6ec123321** [gost-engine/engine#317]
Добрый вечер.

Как то стрёмно было спросить "Как собрать ваш пакет под маршрутизатор", в итоге, за 3 дня кое что сделал (помог человек):
https://github.com/openwrt/packages/pull/14800. Просьба не удалять релиз 1.1.0.3, очень надо, 1.1.0.2 - можно удалять, протестировали 1.1.0.3 (я 1_1._0_r2 ветку протестировал - разработка на ней и начиналась) работает отлично, кто не верит, читаем комменты.

Не буду ходить во круг да около, я так понял что сейчас идёт работа над ГОСТ 2015 для OpenSSL 3 ?, Если не прав, то так и пишите, без мата и всякой другой лишней информации, а больше поможет раскрытие планов по шифрованию gost_engine.

Особенно интересует настройка параметров "PBE_PARAMS =", видел так у вас наработку и коммит, но пока не понимаю как это в будущем поможет определить CRYPT_PARAM, вообще вопрос, можно сделать так, чтобы его не нужно было указывать?

**Comment by beldmit** [comment]
Спасибо вам! А Вы можете ответить на несколько вопросов про осбенности борки под OpenWRT? Мои бывшие коллеги наткнулись на ряд проблем при сборке пакетов.

**Comment by beldmit** [comment]
В апстримовой ветке да, алгоритмы 2015 года. В ветке ossl_patched - уже местами работающая версия, может быть, будет с TLS 1.3.

**Comment by 6ec123321** [comment]
> Спасибо вам! А Вы можете ответить на несколько вопросов про осбенности борки под OpenWRT? Мои бывшие коллеги наткнулись на ряд проблем при сборке пакетов.

Нет ни каких сложностей, просто у ваших коллег нет стержня в характере как у меня, пусть их хоть 10 человек будет, надо всё доводить до ума, меня 3 раза возвращали назад, но я же не сдался, а только прокачал знания. Мне не говорили что я дурак и чего то не понимаю, мне именно помогали, и практически дали готовый пример переработов мой на 100%, дальше уже надо было решать самому, т.к и в лево и в право не уйти, то результат вы сами видите в коде Makefile. У меня была одна задача, с которой ваши коллеги бы не справились - не сдаваться, если отказали, принять критику и продолжить, не проявлять эмоции. Просто это не первый мой проект на гитхабе. Кое-что я и дорабатывал, потом пять лет поддержкой занимался и внедрением новых технологий. В общем - то что произошло - меня и ждало, сильного, настойчивого, в какой то момент я уже всё бросил, я не знал как задать параметры при закачке архива, а от мысли распаковки у меня в 4 часа ночи кровь из носа пошла. Да, я пока без работы, если есть что поделать на подработку - я за. Теперь хотя бы у людей не возникнет вопросов "А на что ты способен", я еще одну тему придумал, но пока не скажу, смотрите на  git openwrt, там классная тема еще есть, потом поблагодарите xD)

**Comment by 6ec123321** [comment]
> В апстримовой ветке да, алгоритмы 2015 года. В ветке ossl_patched - уже местами работающая версия, может быть, будет с TLS 1.3.

А для ускорения работы задействовали ядро? Или опять отсебятину накатали для ФСБ ?

**Comment by 6ec123321** [comment]
grasshoper - вкомпилированно с версии ядра 5.0, я вот о чём

**Comment by 6ec123321** [comment]
Первое правило в работе сисадмина и программиста (один человек, два в одном): never back down.
Второе правило в работе сисадмин: смотри парило № 1
Третье правило в работе уже программиста: соблюдай п. 2, помни п.1
Четвертое правило ИТ-специалиста (2017 год): чем больше знаешь, тем больше понимаешь что ничего не знаешь.

**Comment by 6ec123321** [comment]
Как раз первое правило вашими людьми и не было соблюдено, да, забыл, про пятое правило, которое ваши спецы не смогут сделать, у них хер маловат для этого. Да и вообще пятое правило я придумал ), а какое оно - хотите узнать?

**Comment by 6ec123321** [comment]
Пятое правило Нет ничего не возможного, чего ты хочешь и сколько ты на это готов потратить сил, если все силы, то значит ты очень силён.

**Comment by 6ec123321** [comment]
> Пятое правило Нет ничего не возможного, чего ты хочешь и сколько ты на это готов потратить сил, если все силы, то значит ты очень силён.

Чепуха.

**Comment by 6ec123321** [comment]
Шестое правило: есть вещи требующие выдержки, а не силы - копать землю под картофель тоже долго, но есть п.1 и п.2.

**Comment by 6ec123321** [comment]
Седьмое правило: когда вы все уже сдались, пора глянуть исходный код или коммиты на джите, программист пакета умнее вас, а вы лошарка, который боится обновить пакет - вам надо возвращатся к правилу № 1 ))))

**Comment by 6ec123321** [comment]
Представьте себе, вам не из-за чего ругаться, ваши промахи в коде (пусть это и один файл), вы понимаете на 100% что вы не правы, ради чего спорить? Моя цель "сделать мир лучше", и я сверну любые горы и любые насмешки выдержу.

**Comment by 6ec123321** [comment]
Напоминает цель супермена

**Comment by 6ec123321** [comment]
Сделать мир лучше - вот тут то и кроется цель человеческого мозга, которую я давно уже у себя раскрыл, срал я на деньги - всё что мне нужно уже у меня есть, нет только девушки рядом, деньги, одежда, жильё, машина, велик, - да, хату надо заработать, не предки мне не подарят, и машину не подарят, даже если и захотят, я не возьму, нет, это их машина, в машину я душу предыдущей машины пересодил, так получилось, она надёжна на 350%. Я не возьму ничего, я хочу сказать сам себе, что вот это я заработал...

**Comment by 6ec123321** [comment]
И вот по крупице, в интернете, я снова начинаю собирать себя самого, нет, мой характер закален был в огне, и мне снова нужны самы тяжелые идеи, потому что другой сгорит от обилия мыслей или сойдет с ума, но только не я, мне по кайфу)

**Comment by 6ec123321** [comment]
Душа машины - душа хозяина, моя душа, если кого-то садят за руль, я вижу потом во сне как ездил - это и есть душа автомобиля.

**Comment by 6ec123321** [comment]
Слава богу меня наша машина прощает, я так сильно виноват перед ней, похоже с обоих сторон я сам её и помял, сам наехал на стоячую машину, даже помню, что был за удар. Короче это я сам крылья помял.

**Comment by 6ec123321** [comment]
Вопрос в том, с какой силой вы будете выпрыгивать из точки НОЛЬ в любую сторону - да это тоже не важно...

**Comment by 6ec123321** [comment]
> Спасибо вам! А Вы можете ответить на несколько вопросов про осбенности борки под OpenWRT? Мои бывшие коллеги наткнулись на ряд проблем при сборке пакетов.

Есть там ряд проблемных мест, скажем, возникла проблема с самим типом сборки через cmake. OpenWRT предполагает сборку с помощью make, а в данном случае собирать make нечего.

**Comment by 6ec123321** [comment]
Если хочется собрать gost_engine под Freshtomato или Entware - надо брать файлы с некоторыми изменениями и патчем:
https://github.com/6ec123321/entware-packages/tree/entware-backports/libs/gost_engine

У меня маршрутизатор на FreshTomato, со старыми пакетами Entware-NG сборки 2018 года, так чт оприходится временами обновлять пакеты в ручную.

**Comment by beldmit** [comment]
У меня на прошлой работе была задача собрать opk-пакет из собранных ранее бинарей. При этом получался opk-пакет, который выглядел как настоящий, но ронял pkg manager

**Comment by 6ec123321** [comment]
> У меня на прошлой работе была задача собрать opk-пакет из собранных ранее бинарей. При этом получался opk-пакет, который выглядел как настоящий, но ронял pkg manager

У меня в первый раз было так же, в итоге забросил это дело на год, недавно вот снова вернулся к этому, правда уже решил разобраться как следует и обратился к помощи самих авторов этого всего, ну и посвятили подробно по некоторым параметрам и как что работает.

**Comment by 6ec123321** [comment]
В принципе, те кто всё это начинал сами заинтересованы в том, чтобы и других научить, дабы потом всё это продвинуть в массы. Помогать они и не отказываются, я бы сказал даже наоборот весь мозг вынесут, но научат и помогут, бесплатно.

**Comment by 6ec123321** [comment]
Правда после такой активной помощи, еще потом и подумаешь, а стоит ли снова какой-нибудь пакет начинать портировать))

**Comment by 6ec123321** [comment]
> У меня на прошлой работе была задача собрать opk-пакет из собранных ранее бинарей. При этом получался opk-пакет, который выглядел как настоящий, но ронял pkg manager

А бинарники под нужную архитектуру были собраны?

**Comment by beldmit** [comment]
Да

**Comment by 6ec123321** [comment]
> Да

Скорее всего зависимости системных библиотек - вечная проблема линукса, тоже помучался с ней на маршрутизаторе, всё скомпилировалось, одна ко же segmentation fault)

**Comment by 6ec123321** [comment]
На маршрутизаторах uclibc - главная либа, с неё всё и начинается.
Подробнее на:
https://ru.wikipedia.org/wiki/UClibc#:~:text=uClibc%20%E2%80%94%20%D1%81%D0%B2%D0%BE%D0%B1%D0%BE%D0%B4%D0%BD%D0%BE%D0%B5%20%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%B5%20%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%2C%20%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%BE%D1%81%D1%82%D1%80%D0%B0%D0%BD%D1%8F%D0%B5%D0%BC%D0%BE%D0%B5%20%D0%BF%D0%BE%D0%B4%20GNU%20LGPL.

**Comment by 6ec123321** [comment]
Сейчас у меня другой вопрос, как собрать OpenVPN-client, имея gost-engine, openvpn в виндах собран с поддержкой openssl ?

**Comment by 6ec123321** [comment]
> Сейчас у меня другой вопрос, как собрать OpenVPN-client, имея gost-engine, openvpn в виндах собран с поддержкой openssl ?

Проверил на windows 7 https://swupdate.openvpn.org/community/releases/OpenVPN-2.5.0-I601-amd64.msi
Работает:
```
openvpn --show-tls
Available TLS Ciphers, listed in order of preference:

For TLS 1.3 and newer (--tls-ciphersuites):

TLS_AES_256_GCM_SHA384
TLS_CHACHA20_POLY1305_SHA256
TLS_AES_128_GCM_SHA256

For TLS 1.2 and older (--tls-cipher):

TLS-ECDHE-ECDSA-WITH-AES-256-GCM-SHA384
TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384
TLS-DHE-RSA-WITH-AES-256-GCM-SHA384
TLS-ECDHE-ECDSA-WITH-CHACHA20-POLY1305-SHA256
TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256
TLS-DHE-RSA-WITH-CHACHA20-POLY1305-SHA256
TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256
TLS-ECDHE-RSA-WITH-AES-128-GCM-SHA256
TLS-DHE-RSA-WITH-AES-128-GCM-SHA256
TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA384
TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA384
TLS-DHE-RSA-WITH-AES-256-CBC-SHA256
TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA256
TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA256
TLS-DHE-RSA-WITH-AES-128-CBC-SHA256
TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA
TLS-ECDHE-RSA-WITH-AES-256-CBC-SHA
TLS-DHE-RSA-WITH-AES-256-CBC-SHA
TLS-ECDHE-ECDSA-WITH-AES-128-CBC-SHA
TLS-ECDHE-RSA-WITH-AES-128-CBC-SHA
TLS-DHE-RSA-WITH-AES-128-CBC-SHA
GOST2012-GOST8912-GOST8912 (No IANA name known to OpenVPN, use OpenSSL name.)
GOST2001-GOST89-GOST89 (No IANA name known to OpenVPN, use OpenSSL name.)
```

**Comment by 6ec123321** [comment]
Другой пакет спортирую, чтобы у вас вопросы возникли), самый нужный), потом поговорим )

**Comment by 6ec123321** [comment]
забыл сказать, ядро линукса не ради денег придумали, и не хотят его делать платным, заметте, я тоже просто за идею, чтобы ваш проект заметили, но если вы не растете, нафиг это надо миру.

**Comment by 6ec123321** [comment]
если вы денег ждете от внедрения - вы ошиблись, мы от вас ждём нимезиду, т.е. эпопею, никаких денег, секса, только мозгов, а там, может уже кто-нибудь вас и трахнет)

**Comment by 6ec123321** [comment]
Хотел что-то поменять, но похоже менять уже поздно)
