### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by sergeilem** [gost-engine/engine#322]
`cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=${SSLDIR} -DOPENSSL_LIBRARIES=${SSLDIR}/lib -DOPENSSL_ENGINES_DIR=${SSLDIR}/lib/engines-3 ..`

results:

```
CMake Error at CMakeLists.txt:322 (install):
  install TARGETS given no RUNTIME DESTINATION for executable target
  "gostsum".

CMake Error at CMakeLists.txt:326 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "lib_gost_engine".
```

CentOS8, openssl built from https://github.com/openssl/openssl with:
`./config shared --prefix=${SSLDIR} --openssldir=${SSLDIR} && make build_libs && make build_programs && make install_sw
`

**Comment by levitte** [comment]
Curious...  according to cmake docs, that shouldn't be necessary, as those files are installed in default locations.

**Comment by levitte** [comment]
... makes me wonder what cmake version you use

**Comment by sergeilem** [comment]
cmake version 3.11.4

**Comment by levitte** [comment]
Ah, ok.  cmake documentation only talks about the defaults from [v3.14](https://cmake.org/cmake/help/v3.14/command/install.html), so it's quite possible that for older cmake versions, they have to be specified explicitly.

**Comment by sergeilem** [comment]
I think it would be better to specify paths explicitly, because cmake 3.13 and lower versions are widely used (for example cmake versions in current Debian and current CentOS are lower than 3.14).

**Comment by beldmit** [comment]
@sergeilem , could you please provide a patch?

**Comment by sergeilem** [comment]
See PR #323. It can't pass all tests because EVP_MAC_init is different in "openssl-3.0.0-alpha12" and master branches of openssl.

**Comment by beldmit** [comment]
Merged. Many thanks!
