### ISSUE TITLE
Discussion: is there a reason why "GOST 28147-89 MAC mode" isn't simply a CMAC with GOST 28147-89?

### ISSUE THREAD

**Issue by levitte** [gost-engine/engine#328]
https://github.com/gost-engine/engine/blob/336c30e54ca42f54641ee06c9dce26ecd454b6ea/README.gost#L38-L43

It seems pretty strange that you should have to implement a special EVP_MD that's really an EVP_CIPHER with special properties, when the standard CMAC could have been used in combination with GOST 28147-89...  unless there are special properties with that MAC implementation that makes it fundamentally differ from a standard CMAC.

**Comment by beldmit** [comment]
Definitely there are historical reasons. But, If I remember correctly, gost89-mac isn't CMAC.

**Comment by levitte** [comment]
> gost89-mac isn't CMAC.

From the description in README.gost, it sounds like it is...  so I'm curious what the difference is, other than there being an EVP_MD implementation to retrofit a cipher as a digest.

**Comment by beldmit** [comment]
Here is the brief description (in Russian):
https://ru.wikipedia.org/wiki/%D0%93%D0%9E%D0%A1%D0%A2_28147-89#%D0%A0%D0%B5%D0%B6%D0%B8%D0%BC_%D0%B2%D1%8B%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_%D0%B8%D0%BC%D0%B8%D1%82%D0%BE%D0%B2%D1%81%D1%82%D0%B0%D0%B2%D0%BA%D0%B8

It uses 16 rounds of encryption (instead of 32 in normal GOST cipher mode).

**Comment by levitte** [comment]
> It uses 16 rounds of encryption (instead of 32 in normal GOST cipher mode).

Ah, that's where the difference is (confirmed, that seems to be the major difference between `gostcrypt()` and `mac_block()`!  Ok then, thanks for explaining

**Comment by levitte** [comment]
(although, one can still argue that it could be a CMAC with a special variant of GOST 28147-89 :wink: ...  but I'll let that go)

**Comment by beldmit** [comment]
I think, there is a wide range of [A-Z]MACs in the wild or at least in theory.

More new versions are either pure CMACs or (I hate it) CMAC+key diversification. The last ones, fortunately, are not used in TLS/CMS protocols.
