### ISSUE TITLE
GOST engine key generation tests?

### ISSUE THREAD

**Issue by levitte** [gost-engine/engine#329]
Are there any?  I was looking for `openssl genpkey` in test/04-pkey.t, but could only find pre-generated keys...

**Comment by beldmit** [comment]
There are TCL tests.

E.g. https://github.com/gost-engine/engine/blob/master/tcl_tests/req-genpkey.try

**Comment by vt-alt** [comment]
Aren't these key generation tests?
```
gost-engine$ git grep -w EVP_PKEY_keygen *test*.c
test_derive.c:    T(EVP_PKEY_keygen(ctx, &key));
test_sign.c:    err = EVP_PKEY_keygen(ctx, &priv_key);
test_sign.c:    err = EVP_PKEY_keygen(ctx1, &key2);
test_tls.c:    T((EVP_PKEY_keygen(ctx, &pkey)) == 1);
```

**Comment by levitte** [comment]
I obviously haven't been digging enough in all the tests.

BTW, I notice that the `test_*.c` tests have a lot pretty hard coded (apart from `ENGINE_DIR` being passed as a macro during compile).  Is that desirable?
The reason I ask is that I want to re-use those test programs for the provider stuff as well, and it's pretty easy to refactor the code to be able to handle both engine and provider, given an OPENSSL_CONF environment variable with the proper configuration for each.  Would that be desirable, or would it be better to have two different programs (compiled from the same source), one that tests with the engine and the other that tests with the provider?

**Comment by beldmit** [comment]
I have no strict preferences. Many thanks for your efforts!

**Comment by vt-alt** [comment]
>  to be able to handle both engine and provider
> Would that be desirable, or would it be better to have two different programs (compiled from the same source),

Yes, why duplicate the code.

**Comment by levitte** [comment]
I've had all answers I need.  Thank you all.
