### ISSUE TITLE
Error initializing gost2001 context

### ISSUE THREAD

**Issue by achechet** [gost-engine/engine#338]
openssl genpkey -algorithm gost2001 -pkeyopt paramset:A -out gost.example.ru.key.pem
Error initializing gost2001 context
00611DD7B77F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:346:Global default library context, Algorithm (gost2001 : 0), Properties (<null>)

What is could be wrong?

I have new installation on Debian 10.10 and OpenSSL 3.0.0-beta2-dev
openssl version -a
OpenSSL 3.0.0-beta2-dev  (Library: OpenSSL 3.0.0-beta2-dev )
built on: Tue Jul 13 13:37:49 2021 UTC
platform: linux-x86_64
options:  bn(64,64)
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_BUILDING_OPENSSL -DNDEBUG
OPENSSLDIR: "/usr/local/ssl"
ENGINESDIR: "/usr/local/lib/engines-3"
MODULESDIR: "/usr/local/lib/ossl-modules"
Seeding source: os-specific
CPUINFO: OPENSSL_ia32cap=0x7ffaf3ffffebffff:0x40000000029c6fbf

openssl shows that gost engine it has:

openssl engine gost -c
(gost) Reference implementation of GOST engine
 [gost89, gost89-cnt, gost89-cnt-12, gost89-cbc, kuznyechik-ecb, kuznyechik-cbc, kuznyechik-cfb, kuznyechik-ofb, kuznyechik-ctr, magma-cbc, magma-ctr, magma-ctr-acpkm, magma-ctr-acpkm-omac, kuznyechik-ctr-acpkm, kuznyechik-ctr-acpkm-omac, magma-kexp15, kuznyechik-kexp15, md_gost94, gost-mac, md_gost12_256, md_gost12_512, gost-mac-12, magma-mac, kuznyechik-mac, kuznyechik-ctr-acpkm-omac, gost2001, id-GostR3410-2001DH, gost-mac, gost2012_256, gost2012_512, gost-mac-12, magma-mac, kuznyechik-mac, magma-ctr-acpkm-omac, kuznyechik-ctr-acpkm-omac]

**Comment by beldmit** [comment]
Could you please show your openssl config providing the loading of the GOST engine?

**Comment by achechet** [comment]
# System default
#openssl_conf = default_conf
openssl_conf = openssl_def

*****

[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2

[openssl_def]
engines = engine_section
 
[engine_section]
gost = gost_section
 
[gost_section]
engine_id = gost
dynamic_path = /usr/ssl/lib/engines-3/gost.so
default_algorithms = ALL
CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet

**Comment by achechet** [comment]
Для проверки готовности OpenSSL к работе с GOST Engine, выполним команды (подсвеченные):
	
openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support
(gost) Reference implementation of GOST engine

It does not show last string for me

**Comment by beldmit** [comment]
Если строку про gost не показывает, то это значит, что engine не загрузился. Проверьте с помощью strace, какой конфиг openssl читает, и грузит ли engine

**Comment by achechet** [comment]
find / -name openssl.cnf
/home/alex/works/openssl-master/apps/openssl.cnf
/etc/ssl/openssl.cnf
root@Open-xPKI:/etc/ssl# 
их только два в системе и сейчас оба одинаковых. но на ситуацию это не повлияло. может надо что сказать чтобы ссл перечитал конфиг?

**Comment by achechet** [comment]
почему тогда engine gost -c их показывает?

**Comment by beldmit** [comment]
> почему тогда engine gost -c их показывает?

Потому что грузит не через конфиг

**Comment by beldmit** [comment]
> find / -name openssl.cnf
> /home/alex/works/openssl-master/apps/openssl.cnf
> /etc/ssl/openssl.cnf
> root@Open-xPKI:/etc/ssl#
> их только два в системе и сейчас оба одинаковых. но на ситуацию это не повлияло. может надо что сказать чтобы ссл перечитал конфиг?

Я обычно выставляю путь к конфигу через OPENSSL_CONF явным образом.
Запуститесь под strace, посмотрите, какие файлы читаются

**Comment by achechet** [comment]
root@Open-xPKI:/home/alex# openssl version -e
ENGINESDIR: "/usr/local/lib/engines-3"
root@Open-xPKI:/home/alex# ls -al /usr/local/lib/engines-3/
total 1788
drwxr-xr-x 2 root root   4096 Jul 14 04:32 .
drwxr-xr-x 7 root root   4096 Jul 14 04:09 ..
-rwxr-xr-x 1 root root  28504 Jul 13 09:46 afalg.so
-rwxr-xr-x 1 root root  15776 Jul 13 09:46 capi.so
-rwxr-xr-x 1 alex alex 826976 Jul 13 09:52 gost.so
-rwxr-xr-x 1 alex alex 827064 Jul 13 09:52 libgost.so
-rwxr-xr-x 1 root root  72080 Jul 13 09:46 loader_attic.so
-rwxr-xr-x 1 root root  32816 Jul 13 09:46 padlock.so
root@Open-xPKI:/home/alex# 

все так? я сда ручками положил. права такие?

**Comment by beldmit** [comment]
Всё так. Выполните, наконец, инструкцию про strace.

Минимальный конфиг, который работает:
```
openssl_conf = openssl_def
[openssl_def]
engines = engine_section

[engine_section]
gost = gost_section

[gost_section]
engine_id = gost
dynamic_path = /path/to/gost.so
default_algorithms = ALL
```

**Comment by achechet** [comment]
openssl engine показала gost строчку.
конфиг искада в /usr/local/ssl/

Посыпаю голову свою седую пеплом!
спасибо за помощь!

**Comment by achechet** [comment]
Добрый день!
рискую быть посланным, но к этому готов!
выпущенный самоподписанный сертификат не импортится в openxpki…
мне хотя бы форум где можно услышать полезный совет

Отправлено с iPad

**Comment by beldmit** [comment]
Это не ко мне, это в OpenXPKI. По крайней мере, без диагностики не могу сказать вообще ничего

**Comment by achechet** [comment]
эти отказали, гост типа не поддерживаем.
какую диагностику надо?

Отправлено с iPad

**Comment by beldmit** [comment]
Ну тогда искать то место, где они ГОСТ не поддерживают, и вписывать туда поддержку. Там 15 лет назад было что-то уровня "case RSA: case DSA:", вот туда и впихивать. Не, я этим заниматься не готов :)
