### ISSUE TITLE
Портирование российских криптографических алгоритмов в протокол DTLS 1.2 ?

### ISSUE THREAD

**Issue by ArtemTheVan** [gost-engine/engine#341]
Добрый день!

Планируется ли портирование шифронаборов TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC и TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC в реализацию DTLS1.2 ?

**Comment by beldmit** [comment]
Насколько я знаю, явной спецификации в ТК26 нет. Формально ничего не мешает, в отличие от старого набора, поскольку пакеты можно обрабатывать независимо.
