### ISSUE TITLE
.github/before_script.sh shouldn't define OPENSSL_LIBRARIES

### ISSUE THREAD

**Issue by levitte** [gost-engine/engine#346]
https://github.com/gost-engine/engine/blob/36c50fa58c3cc1c5a30fd94aad77490e44abf022/.github/script.sh#L8

This is a variable that's redefined by `fina_package(OpenSSL ...)` anyway, and with a completely different meaning.

Furthermore, it doesn't seem to be used anywhere:

``` console
$ git grep OPENSSL_LIBRARIES
.cirrus.yml:    - cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ..
.github/script.sh:cmake -DOPENSSL_ROOT_DIR=$PREFIX -DOPENSSL_LIBRARIES=$PREFIX/lib -DOPENSSL_ENGINES_DIR=$PREFIX/engines ${ASAN-} ..
.github/workflows/codeql-analysis.yml:       cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ${ASAN} ..
.travis.yml:        - cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ..
.travis.yml:  - cmake -DOPENSSL_ROOT_DIR=${PREFIX} -DOPENSSL_LIBRARIES=${PREFIX}/lib -DOPENSSL_ENGINES_DIR=${PREFIX}/engines ${ASAN} ..
```

**Comment by beldmit** [comment]
Hmmm... Does it mean I can get rid of explicit `--libdir` setting?

**Comment by beldmit** [comment]
Thanks! Fixed.

**Comment by levitte** [comment]
> Hmmm... Does it mean I can get rid of explicit `--libdir` setting?

Uhm, no? That's something else...

**Comment by beldmit** [comment]
```${SETARCH-} ./config shared -d --prefix=$PREFIX --libdir=lib --openssldir=$PREFIX -Wl,-rpath=$PREFIX/lib```

I think that rpath and libdir should match, don't they?

**Comment by levitte** [comment]
> I think that rpath and libdir should match, don't they?

And they do.  From OpenSSL's INSTALL.md:

> ### libdir
> 
>     --libdir=DIR
> 
> The name of the directory under the top of the installation directory tree
> (see the `--prefix` option) where libraries will be installed.  By default
> this is `lib`. Note that on Windows only static libraries (`*.lib`) will
> be stored in this location. Shared libraries (`*.dll`) will always be
> installed to the `bin` directory.
> 
> Some build targets have a multilib postfix set in the build configuration.
> For these targets the default libdir is `lib<multilib-postfix>`. Please use
> `--libdir=lib` to override the libdir if adding the postfix is undesirable.

BTW, I would recommend having a look at OpenSSL's NOTES-Unix.md (in 3.0) or NOTES.Unix (before 3.0), regarding how to set up the rpath.  The above isn't *wrong*, but there are more flexible ways...
