### ISSUE TITLE
Почему хэши от векторов заданных в стандарте ГОСТ Р 34.11-2012 не совпадают с хэшами полученными в openssl?

### ISSUE THREAD

**Issue by buinov** [gost-engine/engine#354]
![gost341112](https://user-images.githubusercontent.com/28514390/133273667-4d21d5c0-d05f-4304-874b-07edec519b90.png)
В приложении ГОСТ Р 34.11-2012 от указанных векторов 
M1:   `32 31 30 39 38 37 36 35 34 33 32 31 30 39 38 37
         36 35 34 33 32 31 30 39 38 37 36 35 34 33 32 31
         30 39 38 37 36 35 34 33 32 31 30 39 38 37 36 35
         34 33 32 31 30 39 38 37 36 35 34 33 32 31 30` 
M2:  `FB E2 E5 F0 EE E3 C8 20 FB EA FA EB EF 20 FF FB F0 E1 E0 F0 F5 20 E0 ED 20 E8 EC E0 EB E5 F0 F2 F1 20 FF F0 EE EC 20 F1 20 FA F2 FE E5 E2 20 2C E8 F6 F3 ED E2 20 E8 E6 EE E1 E8 F0 F2 D1 20 2C E8 F0 F2 E5 E2 20 E5 D1`
получается соответственно:
с длинной хэш-кода 256 бит от сообщения M1:`00 55 7B E5 E5 84 FD 52 A4 49 B1 6B 02 51 D0 5D 27 F9 4A B7 6C BA A6 DA 89 0B 59 D8 EF 1E 15 9D`
с длинной хэш-кода 512 бит от сообщения M1:`48 6F 64 C1 91 78 79 41 7F EF 08 2B 33 81 A4 E2 11 03 24 F0 74 65 4C 38 82 3A 7B 76 F8 30 AD 00 FA 1F BA E4 2B 12 85 C0 35 2F 22 75 24 BC 9A B1 62 54 28 8D D6 86 3D CC D5 B9 F5 4A 1A D0 54 1B`
с длинной хэш-кода 256 бит от сообщения M2:`50 8F 7E 55 3C 06 50 1D 74 9A 66 FC 28 C6 CA C0 B0 05 74 6D 97 53 7F A8 5D 9E 40 90 4E FE D2 9D`
с длинной хэш-кода 512 бит от сообщения M2:`28 FB C9 BA DA 03 3B 14 60 64 2B DC DD B9 0C 3F B3 E5 6C 49 7C CD 0F 62 B8 A2 AD 49 35 E8 5F 03 76 13 96 6D E4 EE 00 53 1A E6 0F 3B 5A 47 F8 DA E0 69 15 D5 F2 F1 94 99 6F CA BF 26 22 E6 88 1E`
Скорее всего, я где-то ошибаюсь, но не могу понять где.

**Comment by beldmit** [comment]
А engine Вы сами собирали? Из какой ветки?

**Comment by buinov** [comment]
Нет, это пакет из Debian. Но я собрал этот форк https://github.com/ddulesov/engine и в нём тот результат. 
![gost341112](https://user-images.githubusercontent.com/28514390/133281865-e310a760-9fb6-4cf4-930d-a6c516cd726e.png)

**Comment by beldmit** [comment]
Проверьте, что при сборке правильно определяется ENDIANESS процессора. Перевода строк вроде бы у Вас нет.

**Comment by buinov** [comment]
В команде сборки указывается параметр L_ENDIAN.

**Comment by beldmit** [comment]
Тесты на engine проходят? Там были тесты на дайджест.

**Comment by buinov** [comment]
Тесты прошли.
Разобрался в ошибке. Оказывается в двух местах инвертировано направление байт. Просто в стандарте магмы и кузнечика нет шаманств с порядком байт. Спасибо за потраченное время!

**Comment by beldmit** [comment]
Да, там были приколы с порядком байт, причём в самом стандарте.
Если Вы засабмитите PR с комментариями, будет хорошо.
