### ISSUE TITLE
Как передать параметр UKM в функцию выработки общего секретного ключа VKO ГОСТ Р 34.10-12?

### ISSUE THREAD

**Issue by buinov** [gost-engine/engine#357]
![image](https://user-images.githubusercontent.com/28514390/134146579-b02ca5d5-f536-4a19-81b0-dd2349122598.png)
Прощу прощения за возможно банальный вопрос, но я так не понял как передать в функцию этот параметр. Интернет не дал ответов на этот вопрос.
В режиме отладки функция `pkey_gost_ec_derive` оказалась первой вызываемой стеке вызов в gost.dll
Наверное, нужно передавать через какой-то дополнительный пареметр openssl pkeyutl, но я через какой и в каком виде не понял.

**Comment by beldmit** [comment]
ukmhex

Например, https://github.com/gost-engine/engine/blob/e49a93dbfa0e97ff9b32095c84257697c54acef7/test/04-pkey.t#L333

**Comment by beldmit** [comment]
Если в 1.1.1 это в командной строке не поддерживается, то можно сбекпортить.

**Comment by buinov** [comment]
К сожалению, это не помогает. Но это сбока этого форк https://github.com/ddulesov/engine.
![image](https://user-images.githubusercontent.com/28514390/134165287-af746321-923c-4d18-9fa5-7a98e937d03d.png)
Сейчас пересобрал engine из Вашего репозитория ветку версии 1.1.1, и тут всё работает. 
![image](https://user-images.githubusercontent.com/28514390/134165805-9a3741ad-29df-474a-8c4b-9b50349d7316.png)
