### ISSUE TITLE
Docs don't say how to use Grasshopper for S/MIME (encrypt email)

### ISSUE THREAD

**Issue by mouse07410** [gost-engine/engine#36]
`README.gost` says that for S/MIME one needs to specify `-gost89`. What if one wants to use the current standard (Kuzniechik) block cipher rather than the old 1989 standard?

Similar question for other capabilities (Kuzniechik-based MAC, etc).

**Comment by beldmit** [comment]
There is no standard for using Kuznechik yet.

**Comment by mouse07410** [comment]
@beldmit but the engine includes it - so there has to be a way...? And since Kuzniechik officially supercedes Magma...?

**Comment by beldmit** [comment]
There is no specifications for CMS/TLS/etc.
There are rather strange relationships between Magma and Kuznechik and no sense to speak about superseeding.

**Comment by mouse07410** [comment]
Are you saying there is no way to create a CMS message using Kuzniechik via this engine?

Is Kuzniechik usable via `openssl enc ...`? If so, using what flags?

**Comment by beldmit** [comment]
It should be available via the enc command. The names should be grasshopper-*

**Comment by mouse07410** [comment]
> It should be available via the enc command. The names should be grasshopper-*

Understood. It works, thanks.

So there is no OID defined for, e.g., grasshopper-cbc?
Nothing like `OBJECT IDENTIFIER aes256-CBC (2 16 840 1 101 3 4 1 42)`?
Or even like `OBJECT IDENTIFIER gostCipher (1 2 643 2 2 21)`?

**Comment by beldmit** [comment]
We do not have the OIDs yet.

**Comment by mouse07410** [comment]
@beldmit just realized that I'm still confused. You said:
> There are rather strange relationships between Magma and Kuznechik and no sense to speak about superseeding.

Isn't the relationship between Magma and Kuzniechik similar to that between DES and AES? Wasn't the new standard developed to replace the old one - and if not, why bother with a new cipher...?

Also, you might know. Magma has a remarkable property of non-linear keyspace. E.g., if you were to pick a key as a uniformly distributed random number, the likelihood of that key being weak was pretty high. Does Kuzniechik possess the same interesting property?

**Comment by beldmit** [comment]
Well, no. They both are still in use and Magma is safe enough, and no serious attack are known for now.

**Comment by mouse07410** [comment]
@beldmit out of curiosity, any updates here? Or still Magma-only for S/MIME?

**Comment by beldmit** [comment]
The specification is still not finalized.
