### ISSUE TITLE
Не работает под архитектурой ARM

### ISSUE THREAD

**Issue by protek-vrn** [gost-engine/engine#361]
Добрый день!

Пробовал поставить вот этот пакет `libengine-gost-openssl1.1` по инструкции https://gist.github.com/nook-ru/e697d4748085ab6d2a76b2ac037a76c0 на две убунты 20.04, одна под x86 (с помощью Parallels на макбуке с процессором Intel), другая под arm64 (с помощью Parallels на макбуке с процессором M1)

Под Intel
```
~$ openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support
(gost) Reference implementation of GOST engine
```

Под arm почему-то gost engine не виден
```
~$ openssl engine
(dynamic) Dynamic engine loading support
```

В чём может быть проблема? Есть ли рабочий вариант для работы в parallels/docker на маках с arm-процессором?

Спасибо!

**Comment by beldmit** [comment]
Мне неизвестно никаких препятствий, честно говоря.

**Comment by arturolegovich** [comment]
Добрый вечер.

По опыту знаю, что для того, чтобы завести gost-engine нужно из исходного кода скомпилировать openssl-1.1.1, а потом скомпилировать gost-engine конкретно под эту версию openssl. Openssl 1.1.1 из deb-пакета не будет работать с gost.so, так как в нём чего-то не хватает. 

https://jakondo.ru/kak-dobavit-podderzhku-shifrovaniya-po-gost-r-34-10-2012-v-openssl-1-1-1d-na-debian-9-stretch/

У меня на архитектуре MIPS работает gost-engine-1.10.3, старая версия, но мои задачи выполняет.
Я для OpenWRT когда-то пакет делал: https://github.com/openwrt/packages/tree/master/libs/gost_engine.
И как раз сталкивался с такой же проблемой, решилось компиляцией всего openssl-1.1.1.

**Comment by beldmit** [comment]
В 1.1.1 уже всё должно работать из коробки, если сам openssl не собран с disable-gost.

**Comment by arturolegovich** [comment]
> В 1.1.1 уже всё должно работать из коробки, если сам openssl не собран с disable-gost.

Да, как раз в этом и была проблема. Пришлось в основную ветку OpenWRT (сама прошивка) внести изменения для включения gost по умолчанию.

**Comment by arturolegovich** [comment]
Под Intel - gost включен.
Под arm - disable-gost.

Если бы либа gost.so была не правильно скомпилирована, то сообщение было бы: segmentation fault

**Comment by protek-vrn** [comment]
@arturolegovich а как узнать, с каким флагом скомпилен openssl для арм-дистрибутива убунты? Это к разработчикам ubuntu в их комьюнити попробовать выяснить?

**Comment by beldmit** [comment]
openssl version, кажется, с каким-то ключом может это сказать. Ну и опции сборки в исходниках пакета можно посмотреть

**Comment by arturolegovich** [comment]
> openssl version, кажется, с каким-то ключом может это сказать. Ну и опции сборки в исходниках пакета можно посмотреть

Флаг для ./configure называется "no-gost"  - отключает участок кода, для работы с gost.os.  
Соответственно без этого конфиг-флага при сборке gost.so должен подхватиться.

Посмотреть с какими опциями скомпилирован openssl 1.1.1: 
```
openssl version -f
compiler: mipsel-openwrt-linux-uclibc-gcc -fPIC -pthread -mabi=32 -Wa,--noexecstack -Wall -O3 -O2 -pipe -mno-branch-likely -mips32r2 -mtune=mips32r2 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -msoft-float -fpic -ffunction-sections -fdata-sections -DOPENSSL_USE_NODELETE -DOPENSSL_PIC -DOPENSSL_BN_ASM_MONT -DSHA1_ASM -DSHA256_ASM -DAES_ASM -DZLIB -DZLIB_SHARED -DNDEBUG -DOPENSSL_RAND_SEED_DEVRANDOM_SHM_ID=-1 -DOPENSSL_PREFER_CHACHA_OVER_GCM -DOPENSSL_SMALL_FOOTPRINT
```

**Comment by arturolegovich** [comment]
Какой пакет libssl (openssl), какая версия этого пакета установлена в 20.04 для intel и для ARM и с какими параметрами скомпилировано? Возможно применены патчи при создании .deb пакета к исходному коду для ARM отличные от Intel.

**Comment by protek-vrn** [comment]
> @protek-vrn Вероятно, вам надо в той инструкции поменять в строке с `dynamic_path =` путь на `/usr/lib/aarch64-linux-gnu/engines-1.1/gost.so`.

путь я подставил нужный изначально

**Comment by vt-alt** [comment]
Перед тем как написать я проверял в докере на Ubuntu Focal, по идее это и есть 20.04 (20.04.3). И все работало, запускал так:

```
x86_64$ docker run --platform aarch64 --rm -it arm64v8/ubuntu
```

**Comment by protek-vrn** [comment]
Мда, действительно, на чистом образе убунты работает.. Буду копать дальше, так как мне нужно завести на образе с питоном 3.9. Видимо, какой-то конфликтующий пакет ставится.
Всем спасибо!
