### ISSUE TITLE
Openssl 3 + Gost Engine

### ISSUE THREAD

**Issue by servicerefinance** [gost-engine/engine#362]
Добрый день.

Собираю Openssl 3 с поддержкой Gost.

Собрал и поставил OpenSSL 3.1.0-dev  (Library: OpenSSL 3.1.0-dev).
Скачал Gost Engine. Собираю и вот результат.

[  1%] Building C object CMakeFiles/test_tlstree.dir/test_tlstree.c.o
[  2%] Linking C executable bin/test_tlstree
CMakeFiles/test_tlstree.dir/test_tlstree.c.o: In function `main':
test_tlstree.c:(.text.startup+0x2b2): undefined reference to `EVP_DigestSignUpdate'
test_tlstree.c:(.text.startup+0x2c4): undefined reference to `EVP_DigestSignUpdate'
test_tlstree.c:(.text.startup+0x2de): undefined reference to `EVP_DigestSignUpdate'
test_tlstree.c:(.text.startup+0x496): undefined reference to `EVP_DigestSignUpdate'
test_tlstree.c:(.text.startup+0x4a8): undefined reference to `EVP_DigestSignUpdate'
CMakeFiles/test_tlstree.dir/test_tlstree.c.o:test_tlstree.c:(.text.startup+0x4b8): more undefined references to `EVP_DigestSignUpdate' follow
collect2: error: ld returned 1 exit status
CMakeFiles/test_tlstree.dir/build.make:97: recipe for target 'bin/test_tlstree' failed
make[2]: *** [bin/test_tlstree] Error 1
CMakeFiles/Makefile2:139: recipe for target 'CMakeFiles/test_tlstree.dir/all' failed
make[1]: *** [CMakeFiles/test_tlstree.dir/all] Error 2
Makefile:145: recipe for target 'all' failed
make: *** [all] Error 2

При этом, предыдущие версии собираются на ура. Но мне необходима третья версия.

Спасибо!

**Comment by beldmit** [comment]
Посмотрите, с какими опциями upstream собирается для external tests c gost engine.

**Comment by servicerefinance** [comment]
Очень извиняюсь, не могу найти где посмотреть.

**Comment by servicerefinance** [comment]
//Path to a program.
CMAKE_ADDR2LINE:FILEPATH=/usr/bin/addr2line

//Path to a program.
CMAKE_AR:FILEPATH=/usr/bin/ar

//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=Release

//Enable/Disable color output during build.
CMAKE_COLOR_MAKEFILE:BOOL=ON

//C compiler
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc

//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-8

//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-8

//Flags used by the C compiler during all build types.
CMAKE_C_FLAGS:STRING=

//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

//Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//Path to a program.
CMAKE_DLLTOOL:FILEPATH=CMAKE_DLLTOOL-NOTFOUND

//Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING=

//Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=

//User executables (bin)
CMAKE_INSTALL_BINDIR:PATH=bin

//Read-only architecture-independent data (DATAROOTDIR)
CMAKE_INSTALL_DATADIR:PATH=

//Read-only architecture-independent data root (share)
CMAKE_INSTALL_DATAROOTDIR:PATH=share

//Documentation root (DATAROOTDIR/doc/PROJECT_NAME)
CMAKE_INSTALL_DOCDIR:PATH=

//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include

//Info documentation (DATAROOTDIR/info)
CMAKE_INSTALL_INFODIR:PATH=

//Object code libraries (lib)
CMAKE_INSTALL_LIBDIR:PATH=lib

//Program executables (libexec)
CMAKE_INSTALL_LIBEXECDIR:PATH=libexec

//Locale-dependent data (DATAROOTDIR/locale)
CMAKE_INSTALL_LOCALEDIR:PATH=

//Modifiable single-machine data (var)
CMAKE_INSTALL_LOCALSTATEDIR:PATH=var

//Man documentation (DATAROOTDIR/man)
CMAKE_INSTALL_MANDIR:PATH=

//C header files for non-gcc (/usr/include)
CMAKE_INSTALL_OLDINCLUDEDIR:PATH=/usr/include

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

//Run-time variable data (LOCALSTATEDIR/run)
CMAKE_INSTALL_RUNSTATEDIR:PATH=

//System admin executables (sbin)
CMAKE_INSTALL_SBINDIR:PATH=sbin

//Modifiable architecture-independent data (com)
CMAKE_INSTALL_SHAREDSTATEDIR:PATH=com

//Read-only single-machine data (etc)
CMAKE_INSTALL_SYSCONFDIR:PATH=etc

//Path to a program.
CMAKE_LINKER:FILEPATH=/usr/bin/ld

//Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make

//Flags used by the linker during the creation of modules during
// all build types.
CMAKE_MODULE_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of modules during
// DEBUG builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of modules during
// MINSIZEREL builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of modules during
// RELEASE builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of modules during
// RELWITHDEBINFO builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_NM:FILEPATH=/usr/bin/nm

//Path to a program.
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy

//Path to a program.
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump

//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=gost-engine

//Path to a program.
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib

//Path to a program.
CMAKE_READELF:FILEPATH=/usr/bin/readelf

//Flags used by the linker during the creation of shared libraries
// during all build types.
CMAKE_SHARED_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of shared libraries
// during DEBUG builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of shared libraries
// during MINSIZEREL builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of shared libraries
// during RELEASE builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of shared libraries
// during RELWITHDEBINFO builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

//Flags used by the linker during the creation of static libraries
// during all build types.
CMAKE_STATIC_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of static libraries
// during DEBUG builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of static libraries
// during MINSIZEREL builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of static libraries
// during RELEASE builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of static libraries
// during RELWITHDEBINFO builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_STRIP:FILEPATH=/usr/bin/strip

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

//Path to a library.
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so

//OpenSSL Engines Directory
OPENSSL_ENGINES_DIR:PATH=/opt/openssl/lib64/engines-3

//Path to a file.
OPENSSL_INCLUDE_DIR:PATH=/opt/openssl/include

//No help, variable specified on the command line.
OPENSSL_LIBRARIES:UNINITIALIZED=/opt/openssl/lib64

//Path to a program.
OPENSSL_PROGRAM:FILEPATH=/opt/openssl/bin/openssl

//No help, variable specified on the command line.
OPENSSL_ROOT_DIR:UNINITIALIZED=/opt/openssl

//Path to a library.
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so

//pkg-config executable
PKG_CONFIG_EXECUTABLE:FILEPATH=PKG_CONFIG_EXECUTABLE-NOTFOUND

//Value Computed by CMake
gost-engine_BINARY_DIR:STATIC=/opt/engine-master/build

//Value Computed by CMake
gost-engine_SOURCE_DIR:STATIC=/opt/engine-master

//Value Computed by CMake
libprov_BINARY_DIR:STATIC=/opt/engine-master/build/libprov

//Dependencies for the target
libprov_LIB_DEPENDS:STATIC=general;OpenSSL::Crypto;

//Value Computed by CMake
libprov_SOURCE_DIR:STATIC=/opt/engine-master/libprov

**Comment by servicerefinance** [comment]
> Посмотрите, с какими опциями upstream собирается для external tests c gost engine.

//Path to a program.
CMAKE_ADDR2LINE:FILEPATH=/usr/bin/addr2line

//Path to a program.
CMAKE_AR:FILEPATH=/usr/bin/ar

//Choose the type of build, options are: None Debug Release RelWithDebInfo
// MinSizeRel ...
CMAKE_BUILD_TYPE:STRING=Release

//Enable/Disable color output during build.
CMAKE_COLOR_MAKEFILE:BOOL=ON

//C compiler
CMAKE_C_COMPILER:FILEPATH=/usr/bin/cc

//A wrapper around 'ar' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_AR:FILEPATH=/usr/bin/gcc-ar-8

//A wrapper around 'ranlib' adding the appropriate '--plugin' option
// for the GCC compiler
CMAKE_C_COMPILER_RANLIB:FILEPATH=/usr/bin/gcc-ranlib-8

//Flags used by the C compiler during all build types.
CMAKE_C_FLAGS:STRING=

//Flags used by the C compiler during DEBUG builds.
CMAKE_C_FLAGS_DEBUG:STRING=-g

//Flags used by the C compiler during MINSIZEREL builds.
CMAKE_C_FLAGS_MINSIZEREL:STRING=-Os -DNDEBUG

//Flags used by the C compiler during RELEASE builds.
CMAKE_C_FLAGS_RELEASE:STRING=-O3 -DNDEBUG

//Flags used by the C compiler during RELWITHDEBINFO builds.
CMAKE_C_FLAGS_RELWITHDEBINFO:STRING=-O2 -g -DNDEBUG

//Path to a program.
CMAKE_DLLTOOL:FILEPATH=CMAKE_DLLTOOL-NOTFOUND

//Flags used by the linker during all build types.
CMAKE_EXE_LINKER_FLAGS:STRING=

//Flags used by the linker during DEBUG builds.
CMAKE_EXE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during MINSIZEREL builds.
CMAKE_EXE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during RELEASE builds.
CMAKE_EXE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during RELWITHDEBINFO builds.
CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Enable/Disable output of compile commands during generation.
CMAKE_EXPORT_COMPILE_COMMANDS:BOOL=

//User executables (bin)
CMAKE_INSTALL_BINDIR:PATH=bin

//Read-only architecture-independent data (DATAROOTDIR)
CMAKE_INSTALL_DATADIR:PATH=

//Read-only architecture-independent data root (share)
CMAKE_INSTALL_DATAROOTDIR:PATH=share

//Documentation root (DATAROOTDIR/doc/PROJECT_NAME)
CMAKE_INSTALL_DOCDIR:PATH=

//C header files (include)
CMAKE_INSTALL_INCLUDEDIR:PATH=include

//Info documentation (DATAROOTDIR/info)
CMAKE_INSTALL_INFODIR:PATH=

//Object code libraries (lib)
CMAKE_INSTALL_LIBDIR:PATH=lib

//Program executables (libexec)
CMAKE_INSTALL_LIBEXECDIR:PATH=libexec

//Locale-dependent data (DATAROOTDIR/locale)
CMAKE_INSTALL_LOCALEDIR:PATH=

//Modifiable single-machine data (var)
CMAKE_INSTALL_LOCALSTATEDIR:PATH=var

//Man documentation (DATAROOTDIR/man)
CMAKE_INSTALL_MANDIR:PATH=

//C header files for non-gcc (/usr/include)
CMAKE_INSTALL_OLDINCLUDEDIR:PATH=/usr/include

//Install path prefix, prepended onto install directories.
CMAKE_INSTALL_PREFIX:PATH=/usr/local

//Run-time variable data (LOCALSTATEDIR/run)
CMAKE_INSTALL_RUNSTATEDIR:PATH=

//System admin executables (sbin)
CMAKE_INSTALL_SBINDIR:PATH=sbin

//Modifiable architecture-independent data (com)
CMAKE_INSTALL_SHAREDSTATEDIR:PATH=com

//Read-only single-machine data (etc)
CMAKE_INSTALL_SYSCONFDIR:PATH=etc

//Path to a program.
CMAKE_LINKER:FILEPATH=/usr/bin/ld

//Path to a program.
CMAKE_MAKE_PROGRAM:FILEPATH=/usr/bin/make

//Flags used by the linker during the creation of modules during
// all build types.
CMAKE_MODULE_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of modules during
// DEBUG builds.
CMAKE_MODULE_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of modules during
// MINSIZEREL builds.
CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of modules during
// RELEASE builds.
CMAKE_MODULE_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of modules during
// RELWITHDEBINFO builds.
CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_NM:FILEPATH=/usr/bin/nm

//Path to a program.
CMAKE_OBJCOPY:FILEPATH=/usr/bin/objcopy

//Path to a program.
CMAKE_OBJDUMP:FILEPATH=/usr/bin/objdump

//Value Computed by CMake
CMAKE_PROJECT_DESCRIPTION:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_HOMEPAGE_URL:STATIC=

//Value Computed by CMake
CMAKE_PROJECT_NAME:STATIC=gost-engine

//Path to a program.
CMAKE_RANLIB:FILEPATH=/usr/bin/ranlib

//Path to a program.
CMAKE_READELF:FILEPATH=/usr/bin/readelf

//Flags used by the linker during the creation of shared libraries
// during all build types.
CMAKE_SHARED_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of shared libraries
// during DEBUG builds.
CMAKE_SHARED_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of shared libraries
// during MINSIZEREL builds.
CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of shared libraries
// during RELEASE builds.
CMAKE_SHARED_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of shared libraries
// during RELWITHDEBINFO builds.
CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//If set, runtime paths are not added when installing shared libraries,
// but are added when building.
CMAKE_SKIP_INSTALL_RPATH:BOOL=NO

//If set, runtime paths are not added when using shared libraries.
CMAKE_SKIP_RPATH:BOOL=NO

//Flags used by the linker during the creation of static libraries
// during all build types.
CMAKE_STATIC_LINKER_FLAGS:STRING=

//Flags used by the linker during the creation of static libraries
// during DEBUG builds.
CMAKE_STATIC_LINKER_FLAGS_DEBUG:STRING=

//Flags used by the linker during the creation of static libraries
// during MINSIZEREL builds.
CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL:STRING=

//Flags used by the linker during the creation of static libraries
// during RELEASE builds.
CMAKE_STATIC_LINKER_FLAGS_RELEASE:STRING=

//Flags used by the linker during the creation of static libraries
// during RELWITHDEBINFO builds.
CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO:STRING=

//Path to a program.
CMAKE_STRIP:FILEPATH=/usr/bin/strip

//If this value is on, makefiles will be generated without the
// .SILENT directive, and all commands will be echoed to the console
// during the make.  This is useful for debugging only. With Visual
// Studio IDE projects all commands are done without /nologo.
CMAKE_VERBOSE_MAKEFILE:BOOL=FALSE

//Path to a library.
OPENSSL_CRYPTO_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcrypto.so

//OpenSSL Engines Directory
OPENSSL_ENGINES_DIR:PATH=/opt/openssl/lib64/engines-3

//Path to a file.
OPENSSL_INCLUDE_DIR:PATH=/opt/openssl/include

//No help, variable specified on the command line.
OPENSSL_LIBRARIES:UNINITIALIZED=/opt/openssl/lib64

//Path to a program.
OPENSSL_PROGRAM:FILEPATH=/opt/openssl/bin/openssl

//No help, variable specified on the command line.
OPENSSL_ROOT_DIR:UNINITIALIZED=/opt/openssl

//Path to a library.
OPENSSL_SSL_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libssl.so

//pkg-config executable
PKG_CONFIG_EXECUTABLE:FILEPATH=PKG_CONFIG_EXECUTABLE-NOTFOUND

//Value Computed by CMake
gost-engine_BINARY_DIR:STATIC=/opt/engine-master/build

//Value Computed by CMake
gost-engine_SOURCE_DIR:STATIC=/opt/engine-master

//Value Computed by CMake
libprov_BINARY_DIR:STATIC=/opt/engine-master/build/libprov

//Dependencies for the target
libprov_LIB_DEPENDS:STATIC=general;OpenSSL::Crypto;

//Value Computed by CMake
libprov_SOURCE_DIR:STATIC=/opt/engine-master/libprov

**Comment by beldmit** [comment]
https://github.com/openssl/openssl/blob/master/.github/workflows/ci.yml#L252-L275

**Comment by servicerefinance** [comment]
Все один в один.

external-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: package installs
      run: |
        sudo apt-get update
        sudo apt-get -yq install bison gettext keyutils ldap-utils libldap2-dev libkeyutils-dev python3 python3-paste python3-pyrad slapd tcsh python3-virtualenv virtualenv python3-kdcproxy
    - name: install cpanm and Test2::V0 for gost_engine testing
      uses: perl-actions/install-with-cpanm@v1
      with:
        install: Test2::V0
    - name: setup hostname workaround
      run: sudo hostname localhost
    - name: config
      run: ./config --banner=Configured --strict-warnings --debug no-afalgeng enable-rc5 enable-md2 enable-ssl3 enable-ssl3-method enable-weak-ssl-ciphers enable-zlib enable-ec_nistp_64_gcc_128 enable-external-tests no-fips && perl configdata.pm --dump
    - name: make
      run: make -s -j4
    - name: test external gost-engine
      run: make test TESTS="test_external_gost_engine"
    - name: test external krb5
      run: make test TESTS="test_external_krb5"

**Comment by servicerefinance** [comment]
Пересобрал Openssl c конфигурацией:

Then configure/build OpenSSL enabling external tests:

    $ ./config shared enable-external-tests
    $ make

**Comment by beldmit** [comment]
А engine Вы где собираете?

**Comment by servicerefinance** [comment]
У меня следующий энвайронмент:

Ubuntu 18.04
cmake 3.20.2
perl 5.26.1
gcc 8.4.0
make 4.1


Поэтапно, что делаю:
1. Забираю Openssl из git в /opt/openssl
2. Добавляю gost-engine в /opt/openssl/gost-engine (git submodule update --init)
3. Собираю Openssl ./config shared enable-external-tests -d --prefix=/opt/openssl-gost --openssldir=/opt/openssl-gost
4. Устанавливаю
5. Обновляю путь к библиотеке в конфиге /etc/ld.so.conf.d/openssl.conf
6. Сбрасываю кэш ldconfig
7. За тем, в папке build в /opt/openssl/gost-engines собираю engine
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/opt/openssl-gost -DOPENSSL_LIBRARIES=/opt/openssl-gost/lib64 -DOPENSSL_ENGINES_DIR=/opt/openssl-gost/lib64/engines-3 ..
cmake --build . --config Release

И, получаю ту же самую ошибку

**Comment by beldmit** [comment]
Вообще очень странно, потому что эти функции из 3.0.0 никуда не делись. То есть что-то у Вас с настройкой среды не так.

Советую брать не master-ветку в обеих случаях.

**Comment by servicerefinance** [comment]
Можете подсказать оптимальную среду с версиями?
Соберу отдельный сервер и попробую еще раз.

Спасибо!

**Comment by beldmit** [comment]
У меня работает на Fedora33 и на Debian 10. openssl upstream тестирует на Ubuntu 20.04, кажется.

**Comment by servicerefinance** [comment]
Сейчас попробую и отпишу с подробностями. Спасибо

**Comment by beldmit** [comment]
Вообще в Fedora rawhide (то есть будущая 36 версия) есть и gost engine, и openssl 3.0 в пакете. Ну то есть смотря чего вы хотите от ГОСТ и от openssl.

**Comment by servicerefinance** [comment]
Задача, в целом тривиальная.
В компании все сервисы работают на стеке MERN.

И столкнулся с тем, что необходимо реализовать двухстороннюю аутентификацию с внешней системой. Конечно Гост шифрование.

Вот такой код
```js
const fs = require('fs')
const https = require('https')
const axios = require('axios')

const cert = fs.readFileSync('./keys/cert.pem', 'utf8')
const key =  fs.readFileSync('./keys/publickey.pem', 'utf8')

const httpsAgent = new https.Agent({
  cert: cert,
  key: key
})

const httpsUrl = 'https://someurl.com'

const response = async () => {
  return await axios.get(httpsUrl, { httpsAgent })
}

response()
.then(res => {
  console.log('result', res.data)
})
.catch(err => {
  console.log('error', err)
})
```

выдает такую ошибку:
Error: error:0609E09C:digital envelope routines:pkey_set_type:unsupported algorithm.

Соответственно, возникла необходимость поставить Node js на Openssl, который поддерживает Гост.

**Comment by beldmit** [comment]
Вам должно хватить 1.1.1 для TLS. Ну и конфиг подправить, чтобы engine грузился.

**Comment by servicerefinance** [comment]
Собирал уже 1.1.1 версию, но Node не собрался. Вычитал из их документации, что 3 openssl идеально встает и нет ошибок.

**Comment by servicerefinance** [comment]
@beldmit, удалось собрать стабильную версию Node + Openssl 1.1.1 + Gost Engine на Debian 10. Все работает как часы. Но с третьей так и не справился. Одни и те же ошибки, как только не собирал.

**Comment by vt-alt** [comment]
> 7\. cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/opt/openssl-gost -DOPENSSL_LIBRARIES=/opt/openssl-gost/lib64 -DOPENSSL_ENGINES_DIR=/opt/openssl-gost/lib64/engines-3 ..

Добавьте `-DCMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX=64`.

ps. Возможно, это баг `cmake`.

**Comment by vt-alt** [comment]
Завёл https://gitlab.kitware.com/cmake/cmake/-/issues/22945

**Comment by vt-alt** [comment]
> Завёл https://gitlab.kitware.com/cmake/cmake/-/issues/22945

JFYI. Там ответили, что `cmake` не уиноват, всё из-за Debian.

**Comment by beldmit** [comment]
У openssl есть ключ, который управляет переключением lib/lib64

`./config --libdir=lib`
