### ISSUE TITLE
Parsing GOST 2001 keys using java library BouncyCastle

### ISSUE THREAD

**Issue by MikeSafonov** [gost-engine/engine#38]
Добрый день. Я пытаюсь прочитать ключи ГОСТ 3410 2001 используя [BouncyCastle](https://github.com/bcgit/bc-java).  В [issues](https://github.com/bcgit/bc-java/issues/199) ответили, что, по всей видимости, в РЕМ ключа не хватает определенных байт. 
Данная проблема отсутствует при использовании ccgost, который идет с openssl 1.0.2.
С чем это может быть связано?

**Comment by beldmit** [comment]
В разное время использовалось несколько вариантов представления ключа. Скорее всего Bouncy Castle использует более старую разновидность формата. 

Если Вы добавите какую-либо настройку через опцию конфигурации, которая будет этим управлять, я готов рассмотреть этот патч.

**Comment by MikeSafonov** [comment]
Не могли бы Вы указать стандарт представления ключа, на который вы опирались при реализации?

**Comment by beldmit** [comment]
http://tc26.ru/methods/containers_v1/Addition_to_PKCS8&PKCS12_v1_0.pdf
http://tc26.ru/methods/containers_v1/Addition_to_PKCS15_v_1_0.pdf

**Comment by beldmit** [comment]
Чем всё кончилось?

**Comment by nigredo-tori** [comment]
Извините что поднимаю старую тему... Вот [здесь](https://tc26.ru/standard/rs/%D0%A0%2050.1.112-2016.pdf) есть абзац о том что должно лежать в `privateKey`:

> ```
> PrivateKey ::= OCTET STRING
> ```
> Содержимым данного типа является значение закрытого ключа, закодированное в
> соответствии с типом GostR3410-2012-PrivateKey:
> ```
> GostR3410-2012-PrivateKey ::= CHOICE {
> GostR3410-2012-KeyValueMask,
> GostR3410-2012-KeyValueInfo }
> ```

Т.е. лежащие в `privateKey` (`OCTET STRING`) байты должны декодироваться в ASN1-структуру. Получается, BouncyCastle всё-таки прав, а gost-engine по умолчанию генерирует ключи в legacy-кодировке? Или есть какая-то более новая/релевантная спецификация? Приведённые выше ссылки сломаны, и на http://tc26.ru до соответствующих методических рекомендаций я не добрался.

**Comment by beldmit** [comment]
КриптоПро и Инфотекс пишут ключи по-разному. У кого что, я не помню, но где-то обёртка однократная, где-то двухкратная.
В итоге в engine добавили конфигурационный параметр на запись, а на чтение он может и так, и этак.

**Comment by nigredo-tori** [comment]
@beldmit, спасибо, до этого я уже докопался. :smile: Просто желательно понять какое поведение при записи/генерации ключа соответствует спецификации, и по умолчанию использовать его. Сейчас же мы находимся в странной ситуации когда gost-engine и BouncyCastle используют несовместимые форматы ключей, и в обоих репозиториях уверены что у них всё правильно.

Ну и в идеале BC нужно тоже сделать всеядным, чтобы он понимал существующие ключи без дополнительной обёртки - но это пока мечты.
