### ISSUE TITLE
Certificate message without subsequent CertificateVerify in TLS 1.2

### ISSUE THREAD

**Issue by se-prok** [gost-engine/engine#386]
RFC 8446 prohibites to send `Certificate` without `CertificateVerify` whereas RFC 5246 does not.
Does that mean that in TLS 1.2 the client is allowed to send `Certificate` without `CertificateVerify`?
The question stems from the `openssl/gost-engine` behavior: the TLS 1.2 client omits `CertificateVerify` in the case of unsupported `supported_signature_algorithms` in the server's `CertificateRequest`.

**Comment by se-prok** [comment]
openssl client parameters: -tls12 -cert gost_cert
  where gost_cert's curve is `GOST R 34.10-2012 (512 bit) ParamSet A`

Test 1:
Chosen suite: `[0x0c,0x09]`
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03]]`
Result: client sends `Certificate` but omits `CertificateVerify`

Test 2:
Chosen suite: `[0x0c,0x09]`
`CertificateRequest`: `supported_signature_algorithms` - empty list
Result: client responds with alert code `internal_error(80)`

**Comment by beldmit** [comment]
Now I remember. If we use client authentication, we don't send the CertificateVerify message for GOST, because the key possession is proved by some other message.

**Comment by se-prok** [comment]
Test 3:
openssl client parameters: `-tls12 -cert gost_cert512` ..., where `gost_cert512`'s curve is `GOST R 34.10-2012 (512 bit) ParamSet A`
Server uses the same cert: `gost_cert512`.
Chosen suite: `[0xc1,0x01]` (== GOST2012-MAGMA-MAGMAOMAC)
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03]]` (== [SECP256r1])
Result: client responds with `CertificateVerify` where `algorithm = [0x08,0x41]`

Test 4:
openssl client parameters: `-tls12 -cert gost_cert512` ..., where `gost_cert512`'s curve is `GOST R 34.10-2012 (512 bit) ParamSet A`
Server uses the same cert: `gost_cert512`.
Chosen suite: `[0xc1,0x01]` (== GOST2012-MAGMA-MAGMAOMAC)
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03],[0x07,0x0f],[0x07,0x0e]]` (== [SECP256r1,GostCurve512C,GostCurve512B])
Result: client responds with `CertificateVerify` where `algorithm = [0x07,0x0f]`

Test 5:
openssl client parameters: `-tls12 -cert gost_cert256` ..., where `gost_cert`'s curve is `GOST R 34.10-2012 (256 bit) ParamSet B`
Server uses `gost_cert512`.
Chosen suite: `[0xc1,0x01]` (== GOST2012-MAGMA-MAGMAOMAC)
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03],[0x07,0x0f],[0x07,0x0e]]` (== [SECP256r1,GostCurve512C,GostCurve512B])
Result: client responds with `CertificateVerify` where `algorithm = [0x08,0x40]`

Test 6:
openssl client parameters: `-tls12 -cert gost_cert256` ..., where `gost_cert`'s curve is `GOST R 34.10-2012 (256 bit) ParamSet B`
Server uses the same cert: `gost_cert256`.
Chosen suite: `[0xc1,0x01]` (== GOST2012-MAGMA-MAGMAOMAC)
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03],[0x07,0x0f],[0x07,0x0e]]` (== [SECP256r1,GostCurve512C,GostCurve512B])
Result: client responds with `CertificateVerify` where `algorithm = [0x08,0x40]`

Test 7:
openssl client parameters: `-tls12 -cert gost_cert256` ..., where `gost_cert`'s curve is `GOST R 34.10-2012 (256 bit) ParamSet B`
Server uses the same cert: `gost_cert256`.
Chosen suite: `[0xc1,0x01]` (== GOST2012-MAGMA-MAGMAOMAC)
`CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03],[0x07,0x0c],[0x07,0x0b]]` (== [SECP256r1,GostCurve256D,GostCurve256C])
Result: client responds with `CertificateVerify` where `algorithm = [0x07,0x0c]`

**Comment by se-prok** [comment]
> openssl client parameters: `-tls12 -cert gost_cert512 ...`, where `gost_cert512`'s curve is `GOST R 34.10-2012 (512 bit) ParamSet A` Server uses the same cert: `gost_cert512`.
> 
> Test 1: Chosen suite: `[0x0c,0x09]` (== ECDHE-ECDSA-AES128-SHA) `CertificateRequest`: `supported_signature_algorithms = [[0x04,0x03]]` (== [SECP256r1]) Result: client sends `Certificate` but omits `CertificateVerify`
> 
> Test 2: Chosen suite: `[0x0c,0x09]` (== ECDHE-ECDSA-AES128-SHA) `CertificateRequest`: `supported_signature_algorithms` - empty list Result: client responds with alert code `internal_error(80)`

Turns out the certificate list (in `Certificate` in Test 1) is empty, so it's okay. )
