### ISSUE TITLE
Building openssl-1.1.1 branch against OpenSSL 3.0: lib64 vs lib

### ISSUE THREAD

**Issue by lsh123** [gost-engine/engine#397]
I built openssl-1.1.1 branch against OpenSSL 3.0 and I had major issues with lib64 for OpenSSL (vs lib for older versions). I had to create a symlink at the end.

**Comment by beldmit** [comment]
There was a workaround...

But for your purpose it's worth building the 3.0.0 release, it should be what you want

**Comment by beldmit** [comment]
https://github.com/gost-engine/engine/pull/343 is the corresponding issue. But I don't think building 1.1.1 branch with OpenSSL 3.0 is a good idea.

**Comment by lsh123** [comment]
Thanks, it actually worked for me :)

**Comment by beldmit** [comment]
Closing then...
