### ISSUE TITLE
Создание подписи по ГОСТ Р 34.11-2012/34.10-2012

### ISSUE THREAD

**Issue by vanobl** [gost-engine/engine#399]
Подскажите, пожалуйста, используя данный engine можно ли подписывать,  используя алгоритм подписи ГОСТ Р 34.11-2012/34.10-2012? В **INSTALL.md** даётся ссылка на **RFC 4357**, котором данный ГОСТ не описан.

**Comment by beldmit** [comment]
Можно. Сертифицированным решением это не является, но работает.

**Comment by vanobl** [comment]
В примере указан **CRYPT_PARAMS**:
`CRYPT_PARAMS = id-Gost28147-89-CryptoPro-A-ParamSet`

Какое значение ему нужно присвоить, чтобы использовать ГОСТ Р 34.11-2012/34.10-2012 ?

**Comment by beldmit** [comment]
В каком примере? Я это уберу наконец...

**Comment by beldmit** [comment]
`openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:TCA -out seckey.pem` например

Грузить да, удобнее через файл конфигурации.
