### ISSUE TITLE
Algorithm GOST 34.10 2012_512 with paramset C isn't implemented

### ISSUE THREAD

**Issue by boggard** [gost-engine/engine#40]
Здравствуйте. Столкнулся с проблемой отсутствия возможности генерации ключа алгоритма ГОСТ 34.10 2012_512 с набором параметром "С". С чем связано отсутствие реализации этого набора параметров и планируется ли реализация в будущем?

**Comment by beldmit** [comment]
В планах есть, когда доберусь - не знаю. Это явно к версии 1.1.0+, где кофактор учитывается. 
Патчи приветствуются.

**Comment by boggard** [comment]
Спасибо за информацию!
