### ISSUE TITLE
Endianness of magma cipher

### ISSUE THREAD

**Issue by marcfedorow** [gost-engine/engine#402]
В gost-engine функция gost89 подразумевает little-endian.
Это соответствует стандарту ГОСТ 28147-89 (RFC 5830).
Тем не менее, стандарт алгоритма "Магма", описанный в ГОСТ Р 34.12-2015 (RFC 8891) подразумевает big-endian.
Вот цитата из [RFC 8891](https://datatracker.ietf.org/doc/html/rfc8891):

> key is parsed as a single big-endian integer (compared to the little-endian approach used in [[GOST28147-89](https://datatracker.ietf.org/doc/html/rfc8891#ref-GOST28147-89)]), which results in different subkey values being used;

Так, вызывая функцию `magma-*`, я ожидаю, что ключ будет обсчиытываться как big-endian.

**Comment by beldmit** [comment]
И это тоже делается в соответствующих блочных функциях

**Comment by beldmit** [comment]
Вы можете сравнить 

https://github.com/gost-engine/engine/blob/021a2b61b5d904caaf4ceb26ff3163f1f0e4219f/gost_crypt.c#L680-L695

и

https://github.com/gost-engine/engine/blob/021a2b61b5d904caaf4ceb26ff3163f1f0e4219f/gost_crypt.c#L831-L846

**Comment by marcfedorow** [comment]
Правильно ли я тогда понимаю, что текст преобразуется не внутри блочной функции, а отдельно снаружи?

**Comment by beldmit** [comment]
С моей точки зрения блочная функция - это коллбек, который зовётся из EVP_CipherUpdate. Поэтому с моей точки зрения это всё происходит внутри.

**Comment by beldmit** [comment]
И вероятно, учитывая размер блока в 8 байт, искать вам надо __builtin_bswap64

**Comment by beldmit** [comment]
Ох... Насколько это релевантно при текущей политической и санкционной ситуации?

**Comment by marcfedorow** [comment]
Существуют процессорные ядра, которые лицензированы не российским компаниям, но при этом содержат такие инструкции, так что с моей точки зрения это как минимум не бессмысленно.

**Comment by beldmit** [comment]
Не, я-то всецело за

**Comment by marcfedorow** [comment]
Я могу попробовать порефакторить это место (то есть внести endian-преобразование внутрь функции преобразования одного блока). Будет ли иметь смысл заслать такой PR?

**Comment by beldmit** [comment]
Плюс у меня есть подозрение, что сейчас преобразование делается по факту не 0 и 1 раз, а 1 и 2 раза. Возможно, это получится удавить.

**Comment by marcfedorow** [comment]
https://github.com/gost-engine/engine/pull/403

Есть ещё одна вещь, которая кажется мне проблемой: алгоритм предполагает, что данные, с которыми он работает, unaligned, и перекладывание по одному байту идёт на каждом этапе вложенных вызовов.
Если бы можно было гарантировать, что
```
unsigned char *buf = EVP_CIPHER_CTX_buf_noconst(ctx);
unsigned char *iv = EVP_CIPHER_CTX_iv_noconst(ctx);
```
выделяют выравненные под ширину регистра массивы, и проверять входные данные на alignment в самом начале (и перекладывать их там же не больше одного раза), то есть ощущение, что можно было бы сэкономить достаточно много инструкций.

**Comment by beldmit** [comment]
Про iv надо смотреть, с шансами он выровнен. Про буфер вот нифига не уверен.

**Comment by vt-alt** [comment]
"Если бы можно было", но нельзя. Ни `iv`, ни `buf` не выровнены. Исходить из того, что данные выровнены когда это не гарантируется - баг. Много красивых идей по оптимизации разбиваются об этот факт.

**Comment by beldmit** [comment]
На самом деле можно рассчитывать на выравнивание контекста, который гост-специфичный, в целом, и плясать уже от этого. Ну или локальные переменные, выровненные как надо атрибутом __align__

**Comment by vt-alt** [comment]
Я писал про `EVP_CIPHER_CTX_buf_noconst` и `EVP_CIPHER_CTX_iv_noconst`. В OpenSSL могли бы сделать эти буферы выровненными, но не сделали.

**Comment by beldmit** [comment]
Да, там, где у нас всё своё, там можно. 
Посмотрите пожалуйста, что там в #403 отваливается, на первый взгляд с кодом возврата непорядок.

**Comment by marcfedorow** [comment]
#405 использует новую функцию, чтобы не делать много ненужной работы, включая заполнение и очистку двух буферов с промежуточными вычислениями.

**Comment by marcfedorow** [comment]
Не вижу разумно простого способа покрутить ключи в generic версии.

Идея в том, что вместо magma_key вызывается gost_key (аналогично заменяется get_key для тестов), а внутри функции f ключи берутся в обратном порядке.
Засылать такой PR не буду, потому что на сабсете тестируемых архитектур лучше точно не станет, а хуже может стать.
