### ISSUE TITLE
Не загружается модуль, undefined symbol: bind_engine на OpenSSL 3.0.5

### ISSUE THREAD

**Issue by anutator** [gost-engine/engine#404]

**Comment by anutator** [comment]
С такой конфигой вроде загрузилось:

```
openssl_conf = openssl_def

[openssl_def]
engines = engine_section

[engine_section]
gost = gost_section

[gost_section]
engine_id = gost
dynamic_path = /usr/lib64/engines-3/gost.so
default_algorithms = ALL
```
Показывает модули GOST
```
$ openssl ciphers | tr ":" "\n" | grep GOST
GOST2012-MAGMA-MAGMAOMAC
GOST2012-KUZNYECHIK-KUZNYECHIKOMAC
LEGACY-GOST2012-GOST8912-GOST8912
IANA-GOST2012-GOST8912-GOST8912
GOST2001-GOST89-GOST89
```

**Comment by vt-alt** [comment]
* `libgost.so` библиотека для линковки с исходным кодом (через `-lgost`). Загружать её через `dynamic_path` не правильно, поэтому и была ошибка.
* `gost.so` модуль для расширения функционала OpenSSL и слинкованных с ней приложений. Загружается через конфиг (например, `dynamic_path = gost.so`) **или** через опцию `-engine gost` у `openssl`).
