### ISSUE TITLE
Зачем маскировать ключ в функции gost89?

### ISSUE THREAD

**Issue by marcfedorow** [gost-engine/engine#406]
Ключ gost89 (и соответственно магмы) маскируется с битами, полученными через вызов RAND_priv_bytes.
В OpenSSL, например, в блочном шифре AES, такие манипуляции не производятся.
Это действительно неободимо в gost-engine?

Я понимаю теоретическое обоснования уровня "мы не хотим ни в какой момент хранить ключ в памяти", но есть ощущение, что хранение двух блоков памяти, xor которых даёт ключ, не решает проблему, при том снижает производительность.

**Comment by vt-alt** [comment]
Предположу, что это формальное требование для чего-то типа сертификации поэтому рациональные контраргументы тут бессильны. Например, если задача - поиск известного ключа, то xor решает проблему. Замедление, скорее всего, незначительное, так как это все укладывается в малое кол-во cache lines.

**Comment by vt-alt** [comment]
Да кстати и если задача _поиск ключа через перебор содержимого всей памяти_ ("Bruteforce the Memory" как здесь https://diyinfosec.medium.com/scanning-memory-for-fek-e17ca3db09c9), то xor тоже решает проблему. То что в AES меньший уровень защиты для ключа не оправдание, что для старого госта он не должен быть чуть большим.

**Comment by beldmit** [comment]
Это такой карго-культ, от сертифицированных решений маскирование ключей требуют, и в таком варианте на производительность не влияет примерно никак.

**Comment by marcfedorow** [comment]
> Это такой карго-культ
Понял.
На производительность это влияет достаточно серьёзно.
Каждый раунд — это:
# загрузка ключа
8 lw
# загрузка текста
8 lb
6 <<
6 or
# выгрузка шифртекста
8 sb
6 >>
# 32 раунда
32 f
32 xor
# мы закончили
1 ret
# всё остальное — оверхед, вызванный маскированием
8 load # загрузка маски
8 add # ключ + маска
# нам нужны лишние регистры под маску
2 add # работа с указателем стека
5 sw # выгружаем регистры на стек
5 lw # загружаем обратно
Итого 28 мусорных инструкций в добавок к 107 полезным = больше 20% мусорных инструкций на раунд.

**Comment by marcfedorow** [comment]
Допустим, оверхед на дамп регистров в стек можно побороть магией констреинтов.
В лучшем случае (если повезёт не ждать лоадов), это 16 мусорных инструкций из 107+16, то есть больше 13%. Всё равно очень существенно.

**Comment by vt-alt** [comment]
Кол-во инструкций не показатель, так как есть много других факторов (доступ к памяти, кэш разных уровней, pipelining, front-end, back-end, порты процессора.).

**Comment by marcfedorow** [comment]
Если оставаться в рамках разумных допущений (например, что после первых обращений к тексту и ключу они подгрузятся в кэш, а процессор, сделанный для оптимизации обработки криптографических команд, как минимум учитывает необходимость байпасса для вычисления с IPC близким к единице), то, всё-таки, на конкретно этом примере — показатель.
