### ISSUE TITLE
no suitable signature algorithm in server mode

### ISSUE THREAD

**Issue by metaip** [gost-engine/engine#417]
Добрый день.
 
Есть ГОСТ сертификат, команда “openssl x509 –text” успешно его показывает .
Usage у сертификата - TLS Web Server Authentication, TLS Web Client Authentication. 
Когда подключаюсь как клиент (curl или stunnel с опцией client=yes), то все работает отлично.
Когда запускаю “opensll s_server” с данным сертификатом, то подключаюсь к нему тоже без проблем.
 
Но когда задаю этот сертификат для stunnel в качестве сервера или для апача, то выдает ошибку при подключении к серверу:
_SSL_accept: ssl/t1_lib.c:2760: error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm_
 
В stunnel пробовал задавать engine=gost. Не помогает.
 
Версия openssl — 1.1.1.
stunnel 5.66
apache 2.4.54.
Все скомпилировано из исходников.

Гугление привело к похожей проблеме, но с другим движком – https://github.com/openssl/openssl/issues/19280.
 
Не подскажите, в чем может быть дело?
Заранее спасибо.

**Comment by beldmit** [comment]
Проверьте, что engine вообще подгрузился. Например, через strace.

**Comment by metaip** [comment]
Вывод команды lsof ниже.
Вывод strace во вложении, искомая строка 169 - [strace-stunnel.log](https://github.com/gost-engine/engine/files/9870366/strace-stunnel.log)



~ $ pidof stunnel
10532
~ $ lsof -p 10532
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF      NODE NAME
stunnel 10532 root  rtd    DIR              253,0     4096       128 /
stunnel 10532 root  txt    REG              253,0   894912  26723936 /usr/local/bin/stunnel
stunnel 10532 root  mem    REG              253,0    61560  25349362 /usr/lib64/libnss_files-2.17.so
stunnel 10532 root  mem    REG              253,0   822808  26449615 /usr/local/lib64/libgcc_s.so.1
**stunnel 10532 root  mem    REG              253,0  2819568 268627324 /usr/local/lib64/engines-1.1/gost.so.1.1**
stunnel 10532 root  mem    REG              253,0   118568  17655639 /usr/local/lib/libz.so.1.2.12
stunnel 10532 root  mem    REG              253,0  2156592  25180021 /usr/lib64/libc-2.17.so
stunnel 10532 root  mem    REG              253,0   142144  25367672 /usr/lib64/libpthread-2.17.so
stunnel 10532 root  mem    REG              253,0   115816  25348703 /usr/lib64/libnsl-2.17.so
stunnel 10532 root  mem    REG              253,0    14424  25371328 /usr/lib64/libutil-2.17.so
stunnel 10532 root  mem    REG              253,0    19248  25348413 /usr/lib64/libdl-2.17.so
stunnel 10532 root  mem    REG              253,0  3385176  28037426 /usr/local/lib64/libcrypto.so.1.1
stunnel 10532 root  mem    REG              253,0   690216  28037427 /usr/local/lib64/libssl.so.1.1
stunnel 10532 root  mem    REG              253,0   163312  25180003 /usr/lib64/ld-2.17.so
stunnel 10532 root    0u   CHR              136,0      0t0         3 /dev/pts/0
stunnel 10532 root    1u   CHR              136,0      0t0         3 /dev/pts/0
stunnel 10532 root    2u   CHR              136,0      0t0         3 /dev/pts/0
stunnel 10532 root    4r  FIFO                0,9      0t0  34116095 pipe
stunnel 10532 root    5w  FIFO                0,9      0t0  34116095 pipe
stunnel 10532 root    6r  FIFO                0,9      0t0  34116096 pipe
stunnel 10532 root    7w  FIFO                0,9      0t0  34116096 pipe
stunnel 10532 root    8u  unix 0xffff8d2ccb9bee80      0t0  34116102 socket
stunnel 10532 root    9u  IPv4           34116103      0t0       TCP *:pcsync-https (LISTEN)

**Comment by igus68** [comment]
Если stunnel скомпилирован с openssl 1.1.1, то энжин из конфига stunnel
грузити не только не нужно, но и вредно, поведение будет непредсказуемым.
Загрузка энжина должна быть прописана в openssl.cnf, и убедитесь, что этот
конфиг лежит в правильном месте или что на него указывает переменная
окружения OPENSSL_CONF

**Comment by metaip** [comment]
Я не грузил engine из конфига stunnel. Я просто пробовал кучу вариантов и это один из них.
Конечно в конфиге openssl вставлен текст из файла **example.conf**.

Если указания на gost engine в openssl нет, то stunnel даже не грузится.
Вываливается с таким сообщением:

`[!] error queue: ssl/ssl_rsa.c:314: error:140BF10C:SSL routines:ssl_set_cert:x509 lib`
`[!] error queue: crypto/x509/x_pubkey.c:114: error:0B09406F:x509 certificate routines:x509_pubkey_decode:unsupported algorithm`
`[!] error queue: crypto/evp/p_lib.c:210: error:0609E09C:digital envelope routines:pkey_set_type:unsupported algorithm`
`[!] error queue: crypto/x509/x_pubkey.c:114: error:0B09406F:x509 certificate routines:x509_pubkey_decode:unsupported algorithm`
`[!] SSL_CTX_use_certificate_chain_file: crypto/evp/p_lib.c:210: error:0609E09C:digital envelope routines:pkey_set_type:unsupported algorithm`
`[!] Service [port8443]: Failed to initialize TLS context`
`[!] Configuration failed`

Для проверки использования engine использую команды:

> **$ openssl engine -v**
> (dynamic) Dynamic engine loading support
>      SO_PATH, NO_VCHECK, ID, LIST_ADD, DIR_LOAD, DIR_ADD, LOAD
> (gost) Reference implementation of GOST engine
>      CRYPT_PARAMS, PBE_PARAMS, GOST_PK_FORMAT

> **$ curl --engine list**
> Build-time engines:
>   dynamic
>   gost

**Comment by igus68** [comment]
Что у вас ичпользуется в качестве клиента?
На какой стороне возникает указанная в исходном письме ошибка?
Указаны ли на обеих сторонах гостовские криптонаборы и группы?

чт, 27 окт. 2022 г., 5:15 metaip ***@***.***>:

**Comment by metaip** [comment]
Вначале подключался curl-ом, к удивлению узнал об этой проблеме.

Для опытов и демонстрации все запускаю на одном хосте.
Все логи и примеры выше также с этого одного хоста.
Использую openssl (клиент и сервер) и stunnel(сервер).

Как и писал выше с openssl s_server подключается отлично:
Лог клиента - [openssl-gost-client.log](https://github.com/gost-engine/engine/files/9877664/openssl-gost-client.log)
Лог сервера - [openssl-gost-server.log](https://github.com/gost-engine/engine/files/9877669/openssl-gost-server.log)

При подключении к stunnel в качестве сервера ошибка на клиенте:
Лог клиента - [openssl-gost-client-stunnel.log](https://github.com/gost-engine/engine/files/9877674/openssl-gost-client-stunnel.log)

В итоге не важно какой клиент (curl, openssl) и сервер (apache, stunnel), в любом случае ошибка одна и та же. 
Исключением является только сам  openssl в качестве сервера (openssl s_server).

По поводу последнего последнего вопроса про криптонаборы - везде указываю ciphers = ALL.

**Comment by beldmit** [comment]
Я не уверен, что гостовые шифронаборы входят в ALL

**Comment by metaip** [comment]
> ~ $ openssl ciphers -v ALL | grep -i gost
> GOST2012-GOST8912-GOST8912 TLSv1 Kx=GOST     Au=GOST12 Enc=GOST89(256) Mac=GOST89
> GOST2001-GOST89-GOST89  TLSv1 Kx=GOST     Au=GOST01 Enc=GOST89(256) Mac=GOST89

> ~ $ openssl dgst -list | grep -i gost
> -blake2b512                -blake2s256                -gost-mac
> -gost-mac-12               -grasshopper-mac           -id-tc26-cipher-gostr3412-2015-kuznyechik-ctracpkm-omac
> -md5-sha1                  -md_gost12_256             -md_gost12_512
> -md_gost94                 -mdc2                      -ripemd

Я так понимаю openssl-s_client в обоих случаях в ClientHello шлет одинаковый набор шифров. Но openssl-s_server принимает, а остальной софт сразу обрубает соединение.

**Comment by igus68** [comment]
А можно конфиги и командные строки в студию?

чт, 27 окт. 2022 г., 10:53 metaip ***@***.***>:

**Comment by metaip** [comment]
Рабочий вариант с openssl-s_server:
> openssl s_server -debug -cert server-gost.crt -key server-gost.key -port 8443
> openssl s_client -connect localhost:8443

Вариант с stunnel с ошибкой:
> openssl s_client -connect localhost:8443
Конфиг stunnel - [stunnel.txt](https://github.com/gost-engine/engine/files/9878302/stunnel.txt)

Закомментированные строки в конфиге stunnel - это я пытался разные варианты пробовать.

**Comment by igus68** [comment]
Что я вижу:
- ни в конфиге, ни в командных строках криптонаборы не указаны, то есть
используются умолчания;
- соединение s_client-s_server устанавливается по TLS 1.2, а не 1.3, хотя
никаких ограничений на версию не задано и соединение по идее должно
устанавливаться по самой высокой из доступных сторонам версии протокола.

Что я знаю:
умолчания криптонаборов для TLS 1.2 и для TLS 1.3 разные: для 1.2 это
действительно все поддерживаемые криптонаборы, включая ГОСТовские, если
подгружен энжин, а для TLS1 1.3 это некоторый фиксированный набор
"правильных" криптонаборов, и ГОСТовских среди них нет.

Что я предполагаю:
Сначала клиент и сервер пытаются установить соединение по TLS 1.3,
обмениваются умолчательными списками криптонаборов и не находят среди них
ни одного, к которому подошли бы ГОСТовские ключи сервера. В этом месте
s_server и stunnel, видимо, начинают вести себя по-разному: stunnel говорит
"ну не получилось, значит не получилось", а s_server понижает версию
протокола до 1.2, и вот для него ГОСТовский криптонабор находится.

Что я рекомендую:
при использовании ГОСТовских ключей не лениться и явно указывать на обоих
концах ГОСТовские криптонаборы.
Для TLS 1.2 это параметр -cipher для openssl, ciphers для stunnel, полный
список
GOST2012-MAGMA-MAGMAOMAC:GOST2012-KUZNYECHIK-KUZNYECHIKOMAC:GOST2012-GOST8912-GOST8912
Для TLS 1.3 это параметр -ciphersuites для openssl, ciphersuites для
stunnel, полный список
TLS_GOSTR341112_256_WITH_MAGMA_MGM_L:TLS_GOSTR341112_256_WITH_MAGMA_MGM_S:TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L:TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_S
Ещё для TLS 1.3 было бы правильно указывать ГОСТовскую эллиптическую
кривую, это параметр -curves для openssl, curves для stunnel, полный список
GC256A:GC256B:GC256C:GC256D:GC512A:GC512B:GC512C

**Comment by metaip** [comment]
Добрый новый день.
Немного прояснилось.

Задал параметр в stunnel `"sslVersionMax = TLSv1.2"` и виола - заработало.
Значит, когда подключался к openssl-s_server, то он не видел шифров для TLSv1.3 и проваливался до TLSv1.2.
А stunnel и apache, не видя шифров для TLSv1.3, не хотят проваливаться до TLSv1.2 и рубят соединение.

Тогда вопрос - почему openssl не видит указанные Вами ciphersuites для TLSv1.3 ?

Вот все шифры для ветки 1.1.1:

> $ openssl ciphers -v | grep -E 'GOST|1.3' | column -t
> TLS_AES_256_GCM_SHA384        TLSv1.3  Kx=any   Au=any     Enc=AESGCM(256)             Mac=AEAD
> TLS_CHACHA20_POLY1305_SHA256  TLSv1.3  Kx=any   Au=any     Enc=CHACHA20/POLY1305(256)  Mac=AEAD
> TLS_AES_128_GCM_SHA256        TLSv1.3  Kx=any   Au=any     Enc=AESGCM(128)             Mac=AEAD
> GOST2012-GOST8912-GOST8912    TLSv1    Kx=GOST  Au=GOST12  Enc=GOST89(256)             Mac=GOST89
> GOST2001-GOST89-GOST89        TLSv1    Kx=GOST  Au=GOST01  Enc=GOST89(256)             Mac=GOST89

Я решил поставить ветку 3.0.0. Вот его вывод:

> TLS_AES_256_GCM_SHA384              TLSv1.3  Kx=any     Au=any      Enc=AESGCM(256)             Mac=AEAD
> TLS_CHACHA20_POLY1305_SHA256        TLSv1.3  Kx=any     Au=any      Enc=CHACHA20/POLY1305(256)  Mac=AEAD
> TLS_AES_128_GCM_SHA256              TLSv1.3  Kx=any     Au=any      Enc=AESGCM(128)             Mac=AEAD
> GOST2012-MAGMA-MAGMAOMAC            TLSv1.2  Kx=GOST18  Au=unknown  Enc=MAGMA                   Mac=unknown
> GOST2012-KUZNYECHIK-KUZNYECHIKOMAC  TLSv1.2  Kx=GOST18  Au=unknown  Enc=KUZNYECHIK              Mac=unknown
> LEGACY-GOST2012-GOST8912-GOST8912   TLSv1    Kx=GOST    Au=GOST12   Enc=GOST89(256)             Mac=GOST89
> IANA-GOST2012-GOST8912-GOST8912     TLSv1    Kx=GOST    Au=GOST12   Enc=GOST89(256)             Mac=GOST89
> GOST2001-GOST89-GOST89              TLSv1    Kx=GOST    Au=GOST01   Enc=GOST89(256)             Mac=GOST89

Указывал принудительно список `"TLS_GOSTR341112_256_WITH_MAGMA_MGM_L:TLS_GOSTR341112_256_WITH_MAGMA_MGM_S:TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_L:TLS_GOSTR341112_256_WITH_KUZNYECHIK_MGM_S"`.
Openssl ругается, говорит не знаю.

Может какая-то хитрость есть? Может надо что-то дополнительно прописать в конфиг openssl?
Сейчас у меня прописано только содержимое файла `example.conf` из вашего пакета.

**Comment by igus68** [comment]
Про openssl 3.0 не знаю, дела с ней не имел, а в 1.1.1 для tls1.3 нужно
указывать параметр -ciphersuites со списком гостовских криптонаборов.
Обратите внимание, именно - ciphersuites, а не -ciphers

пт, 28 окт. 2022 г., 7:30 metaip ***@***.***>:

**Comment by alexspirt** [comment]
TLS 1.3 работает только с gost-engine из ветки ossl_patched с патченным openssl 1.1.1.
В других ветках, включая master c openssl 3.0 TLS 1.3, пока реализован не до конца.

**Comment by metaip** [comment]
Мужчины, спасибо! Вопрос закрыт.
