### ISSUE TITLE
Support for 0xC100, 0xC101, 0xC102 ciphers

### ISSUE THREAD

**Issue by Flashed** [gost-engine/engine#429]
I have built branch openssl1_1_1 for openssl-1.1.1g version.  
The openssl ciphers command outputs two GOST entries:
```
openssl ciphers | grep GOST | tr ':' '\n'
GOST2012-GOST8912-GOST8912
GOST2001-GOST89-GOST89
```
From the current output, I don't understand if the ciphers are supported:
```
TLS_GOSTR341112_256_WITH_KUZNYECHIK_CTR_OMAC (0xC100)
TLS_GOSTR341112_256_WITH_MAGMA_CTR_OMAC (0xC101)
TLS_GOSTR341112_256_WITH_28147_CNT_IMIT (0xC102)

```
When I make a curl request using openssl I only see two ciphers in the ServerHello message:
```
TLS_GOSTR341001_WITH_28147_CNT_IMIT (0x0081)
Unknown (0xff85)
```

**Comment by beldmit** [comment]
0xC100, 0xC101, 0xC102 ciphers are not supported in the openssl1_1_1 branch

**Comment by beldmit** [comment]
ossl_patched, you will have to build custom OpenSSL
