### ISSUE TITLE
ГОСТ Р 34.11 2012 или 2018

### ISSUE THREAD

**Issue by mikhailnov** [gost-engine/engine#432]
Здравствуйте!
Есть ГОСТ Р 34.11-2018 (https://files.stroyinf.ru/Data2/1/4293732/4293732953.pdf), который "подготовлен на основе применения ГОСТ Р 34.11-2012".
Подскажите, пожалуйста, md_gost12_256 и md_gost12_512 реализуют ГОСТ Р 34.11-2012 или 2018 по факту тоже реализуют?

**Comment by beldmit** [comment]
Проверьте на контрольных примерах, но я не помню, чтобы это было что-то за пределами стандартизации на уровне ЕАЭС того, что применяется в России. Так что должно соответствовать.

**Comment by mikhailnov** [comment]
А, да, это международная стандартизация, спасибо!

**Comment by igus68** [comment]
И в его номере нет буквы Р, т.е. не ГОСТ Р 34.11-2018, а ГОСТ 34.11-2018,
потому что международный.
