### ISSUE TITLE
Performance drop after creating missing NIDs

### ISSUE THREAD

**Issue by marcfedorow** [gost-engine/engine#433]
https://github.com/gost-engine/engine/commit/97b3db1ebf985b73718faaae6c425782d526d44f
This exact patch gives 2% performance decrease on my RISC-V processor.
test:
```bash
openssl speed -evp kuznyechik-ecb -seconds 5
```

I do not understand how a function that is called once may affect performance that much.

**Comment by beldmit** [comment]
If you are looking for a performance, I'd suggest really profile the code. Cipher itself has a lot of place to improve

BTW, NID allocation may require some locking.

**Comment by marcfedorow** [comment]
I re-wrote it with inline assembly so that's 2% of optimized score.
Still, that seems alot.

**Comment by marcfedorow** [comment]
Performance drop is caused by call of `create_NIDs` function.
It is true even if I define it like this
(which is similar in context of missing_NIDs having 0 elements):

```c
__attribute__((noinline))
static int create_NIDs() {
    int i;
    asm("");
    return 1;
}
```

**Comment by marcfedorow** [comment]
Not sure this will be investigated any further so I close this ticket.
