### ISSUE TITLE
Не загружается в openssl 3.0.7 по умолчанию через конфиг

### ISSUE THREAD

**Issue by alex-eri** [gost-engine/engine#435]
Собрал и установил ветку master. Установил секцию в /etc/ssl/openssl.cnf

```
$ openssl engine
(rdrand) Intel RDRAND engine
(dynamic) Dynamic engine loading support

```
Но динамически загружается

```
$ openssl engine gost -t
(gost) Reference implementation of GOST engine
     [ available ]

```

Без указания  -engine gost  не работает. А нужно чтоб шифры появились в библиотеке, которая использует библиотеку, которая использует openssl

Работает

`openssl s_client  -engine gost  -connect lkul.nalog.ru:443 `

**Comment by beldmit** [comment]
Покажите конфиг

**Comment by alex-eri** [comment]
Нашел после кучи комментариев ещё одну строчку `openssl_conf = openssl_init`. Убрал. Загрузилось.
