### ISSUE TITLE
EVP_key_check

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#44]
Implement EVP_PKEY_check (master).

**Comment by beldmit** [comment]
Do not know what did I mean.

**Comment by vt-alt** [comment]
Полный список:

1. `EVP_PKEY_check` вызывает `ctx->pmeth->check` или `pkey->ameth->pkey_check`
2. `EVP_PKEY_public_check` вызывает `ctx->pmeth->public_check` или `pkey->ameth->pkey_public_check`
3. `EVP_PKEY_param_check` вызывает `ctx->pmeth->param_check` или `pkey->ameth->pkey_param_check`.

Есть ли рекомендации что проверять?
