### ISSUE TITLE
Openssl pkcs12. error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)

### ISSUE THREAD

**Issue by agibalovsa** [gost-engine/engine#444]
Здравствуйте.

Поставил на дистрибутиве devuan 4.0 следующие продукты:
openssl 3.0.9, gost-engine с мастера.

```
$> openssl engine gost
(gost) Reference implementation of GOST engine
```

```
$> openssl ciphers|tr ':' '\n'|grep GOST
GOST2012-MAGMA-MAGMAOMAC
GOST2012-KUZNYECHIK-KUZNYECHIKOMAC
LEGACY-GOST2012-GOST8912-GOST8912
IANA-GOST2012-GOST8912-GOST8912
GOST2001-GOST89-GOST89
```

Вроде все работает, ключ и сертификаты генерируются с ГОСТ алгоритмами

```
$> openssl genpkey -aes256 -algorithm gost2012_256 -pkeyopt paramset:A -out intermediate/private/user_2.key.pem
$> openssl req -config openssl.cnf -key intermediate/private/user_2.key.pem -new -engine gost -md_gost12_256 -out intermediate/csr/user_2.csr.pem
$> openssl ca -config openssl.cnf -extensions usr_cert -days 375 -notext -engine gost -md md_gost12_256 -in intermediate/csr/user_2.csr.pem -out intermediate/certs/user_2.cert.pem
```

Однако ошибка происходит при экспорте ключа и сертификата

```
$> openssl pkcs12 -engine gost -export -inkey intermediate/private/user_2.key.pem -in intermediate/certs/user_2.cert.pem -out intermediate/certs/user_2.pfx -keypbe gost89 -certpbe gost89 -macalg md_gost12_256
Engine "gost" set.
Enter pass phrase for intermediate/private/user_2.key.pem:
Enter Export Password:
Verifying - Enter Export Password:
40D7B7A7C27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
40D7B7A7C27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (md_gost12_512 : 107), Properties (<null>)
40D7B7A7C27F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:373:Global default library context, Algorithm (GOST R 34.11-2012 with 512 bit hash : 107), Properties (<null>)
```

Не понятно, по каким причинам происходит данная ошибка. Если параметры keypbe, certpbe, macalg не указывать, то пакет формируется нормально. Но для импорта в криптопровайдер КриптоПРО нужно указывать именно такие параметры.

Буду благодарен за разъяснение причин ошибок.

**Comment by beldmit** [comment]
Попробуйте грузить Engine через конфиг

**Comment by agibalovsa** [comment]
Дмитрий, а можете уточнить, как это реализовать? Текущий конфиг по инструкции (см. ниже)

```
[openssl_def]
engines = engine_sect        

[engine_sect]
gost = gost_sect          

[gost_sect]
engine_id = gost       
dynamic_path = /usr/local/ssl/lib64/engines-3/gost.so
default_algorithms = ALL 
CRYPT_PARAMS=id-Gost28147-89-CryptoPro-A-ParamSet
```

**Comment by beldmit** [comment]
Там не хватает первой строки:

openssl_init = openssl_def

**Comment by agibalovsa** [comment]
По умолчанию было так

![image](https://user-images.githubusercontent.com/14235747/230893458-e3c0ef58-e4a5-4b54-ad59-411457d41e49.png)

Я поменял на такой вариант

![image](https://user-images.githubusercontent.com/14235747/230893566-8e35a8d4-100d-4d2c-bac0-9fd2e21e1447.png)

Пробовал такой вариант

![image](https://user-images.githubusercontent.com/14235747/230893800-835271cb-3589-40a0-9c6a-b0b5d4fb29ff.png)

все равно не работает

**Comment by agibalovsa** [comment]
Здравствуйте.
Снял вывод strace.
Тест проводил на OpenSSL 3.0.8 и OpenSSL 3.2 . В обоих случая выполнял одни и те же действия. В обоих случаях наблюдаются ошибки. Но текст ошибок разный.

strace -v -s 4096 openssl pkcs12 -export -inkey intermediate/private/user_2.key.pem -in intermediate/certs/user_2.cert.pem -out intermediate/certs/user_2.pfx -engine gost -keypbe gost89 -certpbe gost89 -macalg md_gost12_256

Прикладываю файлы. Я сам посмотрел, ничего не могу сказать по сути ошибок.

[OpenSSL3_0_8_PKCS12_ER.txt](https://github.com/gost-engine/engine/files/11200420/OpenSSL3_0_8_PKCS12_ER.txt)
[OpenSSL3_2_PKCS12_ER.txt](https://github.com/gost-engine/engine/files/11200421/OpenSSL3_2_PKCS12_ER.txt)

**Comment by beldmit** [comment]
Попробуйте убрать -engine gost из командной строки

**Comment by agibalovsa** [comment]
Ни как не повлияло. Вывод strace точно такой же.

**Comment by beldmit** [comment]
Я запустил тесты. Вижу эти записи в логе, но тем не менее pkcs#12 файлы у меня создаются и нормально разбираются.

**Comment by beldmit** [comment]
Ошибкой не считать. В принципе можно попытаться раскопать, где же в OpenSSL ошибка из стека не убивается, но мне скорее лениво.

**Comment by agibalovsa** [comment]
@beldmit а можете мне подсказать куда покапать, чтобы понять причину ошибки?

**Comment by beldmit** [comment]
crypto/evp/evp_fetch.c окрестности строки 373. Смотреть, где пропущена ERR_pop_to_mark

**Comment by agibalovsa** [comment]
> crypto/evp/evp_fetch.c окрестности строки 373. Смотреть, где пропущена ERR_pop_to_mark

Как я понял из анализа вывода ошибки, не удается получить переменную method. Она получается 2мя способами: ossl_method_store_cache_set или ossl_method_construct.

Не понятно где эти методы определяются.

**Comment by beldmit** [comment]
Мне откровенно лень это отлаживать, извините.

**Comment by agibalovsa** [comment]
Да я бы сам отладил. Не понятно только как отладку запустить. какая среда нужна. Если бы Вы подсказали, я бы занялся.

Также интересует, в какой среде у Вас тестирование идет, может стоит на другом дистрибутиве поднять систему.

Также интересует, может ли влиять на работу библиотеки то, что в системе предустановлена openssl 1.1.1n. В документации к Openssl 3.x написано, что на это внимание обращать не стоит. Разные версии не конфликтуют, если установлены в разных каталогах.

**Comment by beldmit** [comment]
Под линуксом я использую gdb.

Тестирую я на Fedora и на Ubuntu бегают автотесты на github. Версия 1.1.1 мешать не должна. 

Собственно, общий принцип - пытаются найти объект (дайджест) сначала по-новому, через провайдеры, потом по-старому. При этом то, что его не нашли через провайдеры, не ошибка, пока legacy путь ещё с нами. Поэтому там фетчинг надо завернуть в ERR_set_mark/ERR_pop_to_mark.

**Comment by ypenkin** [comment]
```C
diff --git a/crypto/evp/p5_crpt2.c b/crypto/evp/p5_crpt2.c
index b7455be1cf..3561739023 100644
--- a/crypto/evp/p5_crpt2.c
+++ b/crypto/evp/p5_crpt2.c
@@ -231,13 +231,16 @@ int PKCS5_v2_PBKDF2_keyivgen_ex(EVP_CIPHER_CTX *ctx, const char *pass,
         goto err;
     }
 
+    (void)ERR_set_mark();
     prfmd = prfmd_fetch = EVP_MD_fetch(libctx, OBJ_nid2sn(hmac_md_nid), propq);
     if (prfmd == NULL)
         prfmd = EVP_get_digestbynid(hmac_md_nid);
     if (prfmd == NULL) {
+        (void)ERR_clear_last_mark();
         ERR_raise(ERR_LIB_EVP, EVP_R_UNSUPPORTED_PRF);
         goto err;
     }
+    (void)ERR_pop_to_mark();
 
     if (kdf->salt->type != V_ASN1_OCTET_STRING) {
         ERR_raise(ERR_LIB_EVP, EVP_R_UNSUPPORTED_SALT_TYPE);
diff --git a/crypto/pkcs12/p12_mutl.c b/crypto/pkcs12/p12_mutl.c
index afdb8d688b..2fd17a63b2 100644
--- a/crypto/pkcs12/p12_mutl.c
+++ b/crypto/pkcs12/p12_mutl.c
@@ -108,15 +108,20 @@ static int pkcs12_gen_mac(PKCS12 *p12, const char *pass, int passlen,
     X509_ALGOR_get0(&macoid, NULL, NULL, macalg);
     if (OBJ_obj2txt(md_name, sizeof(md_name), macoid, 0) < 0)
         return 0;
+
+    (void)ERR_set_mark();
     md = md_fetch = EVP_MD_fetch(p12->authsafes->ctx.libctx, md_name,
                                  p12->authsafes->ctx.propq);
     if (md == NULL)
         md = EVP_get_digestbynid(OBJ_obj2nid(macoid));
 
     if (md == NULL) {
+        (void)ERR_clear_last_mark();
         ERR_raise(ERR_LIB_PKCS12, PKCS12_R_UNKNOWN_DIGEST_ALGORITHM);
         return 0;
     }
+    (void)ERR_pop_to_mark();
+
     md_size = EVP_MD_get_size(md);
     md_nid = EVP_MD_get_type(md);
     if (md_size < 0)
```

@agibalovsa можете попробовать этот патч на ветку openssl-3.0

**Comment by agibalovsa** [comment]
@ypenkin спасибо большое, данный патч помог.

Я сгенерировал корневой сертификат -> промежуточный сертификат -> пользовательский сертификат, список отзыва.
Экспортировал пользовательский сертификат в pkcs12, загрузил в Крипто ПРО, установил все остальные сертификаты и список отзыва. Подцепил пользовательский сертификат в 1С. Выполнил подпись документа с помощью Крипто ПРО.
![КриптоПРО](https://github.com/gost-engine/engine/assets/14235747/dd6322ab-2068-4d23-b3f1-eefeb6c09c04)

Использовал алгоритм gost2012_256 и кэш md_gost12_256, gost2012_512 и кэш md_gost12_512.

Хотел уточнить, данный патч войдет в репозиторий openssl?

**Comment by beldmit** [comment]
Чтобы этот патч вошёл в OpenSSL upstream, его надо туда отправить. Лучше всего если это сделает автор патча.

**Comment by ypenkin** [comment]
> @ypenkin спасибо большое, данный патч помог.
> 
> Я сгенерировал корневой сертификат -> промежуточный сертификат -> пользовательский сертификат, список отзыва. Экспортировал пользовательский сертификат в pkcs12, загрузил в Крипто ПРО, установил все остальные сертификаты и список отзыва. Подцепил пользовательский сертификат в 1С. Выполнил подпись документа с помощью Крипто ПРО. ![image](https://user-images.githubusercontent.com/14235747/239598850-07a09ace-aee5-46ae-a008-26c9430c57de.png)
> 
> Использовал алгоритм gost2012_256 и кэш md_gost12_256, gost2012_512 и кэш md_gost12_512.
> 
> Хотел уточнить, данный патч войдет в репозиторий openssl?

Вошёл
