### ISSUE TITLE
adapt tests for openssl crl/req exit code on verification failure

### ISSUE THREAD

**Issue by vladak** [gost-engine/engine#452]
In PR https://github.com/openssl/openssl/pull/23773 I am about to change the exit code used by the `openssl req` and `openssl crl` commands on verification failure. This will likely be part of OpenSSL 3.3.x. Some of the gost-engine tests expect the exit code on verification failure to be 0. These have to be adapted to the new behavior.

**Comment by vt-alt** [comment]
Thanks for the heads up. Will look at this on weekend.

**Comment by vt-alt** [comment]
I introduced the test suite change that should make tests pass with and without your PR.
