### ISSUE TITLE
cmake failed (env: windows 64, wsl, Ubuntu-24.04):  No such file or directory    14 | #include "prov/err.h"

### ISSUE THREAD

**Issue by GW00234847** [gost-engine/engine#460]
Hi Guys, I just ran into this problem when I was trying to build Gost on Windows 64, and here comes the detailed info:
Env: windows 22H2  19045, wsl 2, Ubuntu-24.04, OpenSSL 3.0.13, CMake 3.28.3
Steps:
 1. update apt-get & install all dependencies for build: build-essential git cmake libssl-dev;
 2. git clone from this project, use the master branch.
 3. build gost-engine: mkdir build & cd build & cmake .. & make
 4. when running 'make', here comes the error like No such file or directory  14 | #include "prov/err.h"
 5. 
![image](https://github.com/gost-engine/engine/assets/149048134/2547559b-3be5-4ad5-84e4-a32abfb99eef)

I can not find the 'prov/err.h', there is no 'prov' directory. Don't know how to solve it. Has anyone encountered this issue?

**Comment by Mironenko** [comment]
Hi! Looks like you've forgotten to make `git submodule update --init` after cloning the project. See https://github.com/gost-engine/engine/blob/master/INSTALL.md#how-to-build 
`prov/err.h`  resides libprov submodule.

**Comment by GW00234847** [comment]
> Hi! Looks like you've forgotten to make `git submodule update --init` after cloning the project. See https://github.com/gost-engine/engine/blob/master/INSTALL.md#how-to-build `prov/err.h` resides libprov submodule.

Yes, I did miss it. After installing submodule, it works now. Thanks a lot.
