### ISSUE TITLE
OpenSSL compatibility

### ISSUE THREAD

**Issue by Dunemaster** [gost-engine/engine#50]
Hello!

Could you clarify, which versions of openSSL is compatible with the engine?

Is 1.0.2 compatible?

**Comment by beldmit** [comment]
Branch 1_0_2 is compatible, but requires patching openssl itself to provide support of GOST2012 algorithms.

**Comment by Dunemaster** [comment]
@beldmit , it would beneficial  greatly if you write it in README.md
I

**Comment by beldmit** [comment]
Well, I think it's written in documentation in the 1_0_2 branch. Ok, I think it will be useful to add.

**Comment by beldmit** [comment]
Done.
