### ISSUE TITLE
Bug in gost_grasshopper_cipher_do_ctr

### ISSUE THREAD

**Issue by andyk555** [gost-engine/engine#51]
The following is not correct for x86 archs:
memcpy(c->iv_buffer.b + 8, &c->counter, 8); and c->counter += 1;
See comment in crypto/modes/ctr128.c: "... the IV/counter CTR mode is big-endian".
Also you can see it in GOST_R_3413-2015, item A.2.2.1, table A.8 for input block values.
It's possible to fix as:
<pre>
static void ctr128_inc(unsigned char *counter)
{
    unsigned int n = 16;
    unsigned char c;

    do {
        --n;
        c = counter[n];
        ++c;
        counter[n] = c;
        if (c) return;
    } while (n);
}
</pre>
and replace lines: c->counter += 1
by ctr128_inc(c->iv_buffer.b)

**Comment by beldmit** [comment]
Could you please provide a pull request?

**Comment by beldmit** [comment]
Fix applied some time ago.
