### ISSUE TITLE
gosthash2012 don't work without L_ENDIAN

### ISSUE THREAD

**Issue by DarovskikhAndrei** [gost-engine/engine#53]
If L_ENDIAN is not defined, then used other constant. It make incorrect hash and handshake will failed.

**Comment by beldmit** [comment]
For 1.1.0+ branches this value should be defined by cmake. 1.0.2 branch is drop-in replacement for openssl engines/ccgost content and should have the define.

**Comment by DarovskikhAndrei** [comment]
This define are conflict with openssl defines and working only in separated compile of projects. In one project compile it is not working.

**Comment by beldmit** [comment]
Which branch do you use?

**Comment by DarovskikhAndrei** [comment]
In my result project I using master branch with openssl 1.1.0g

**Comment by beldmit** [comment]
Well, the library should be built separately from openssl itself. 
What is the define in openssl conflicting with L_ENDIAN?

**Comment by DarovskikhAndrei** [comment]
I test after full rebuild ny project with L_ENDIAN define - It is working. Issuer not confirmed.
