### ISSUE TITLE
INSTALL.md

### ISSUE THREAD

**Issue by Wladdy** [gost-engine/engine#54]
Hello, I tried to install the engine using your guide located in INSTALL.md file, and that try was unsuccessful. So help me please :) Ready to give all information you need about my installation process
- Ubuntu 16.04
- OpenSSL 1.1.1-pre4 and -pre6
- While installing i found that on step 2 "How to Install" the file gost.so was installed in .../engines-1_1 folder, not in .../engines-1.1 as guided. So i created symlink and finished the installation but the output of:
openssl ciphers | tr ':' '\n' | grep GOST
was empty

**Comment by beldmit** [comment]
You should do the following:
1. Specify openssl config loading the GOST engine
2. Enable @SECLEVEL=0

**Comment by Wladdy** [comment]
1. I edited openssl.cnf as was written in guide.
2. I misunderstood second step, where should I type "@seclevel=0"?

**Comment by beldmit** [comment]
openssl ciphers 'ALL:@SECLEVEL=0'

**Comment by Wladdy** [comment]
openssl ciphers 'ALL:@seclevel=0'
Error in cipher list
139639036819200:error:260B6091:engine routines:dynamic_load:version incompatibility:crypto/engine/eng_dyn.c:454:
139639036819200:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=gost_section, name=dynamic_path, value=/usr/lib/ssl/engines/libgost.so
139639036819200:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:174:module=engines, value=engine_section, retcode=-1      
139639036819200:error:140E6118:SSL routines:ssl_cipher_process_rulestr:invalid command:ssl/ssl_ciph.c:1194:

**Comment by Wladdy** [comment]
Just followed your guide...
Thanks for reply anyway!

**Comment by nurlanarysbaev** [comment]
Hello.
Help me please. How install on windows?

**Comment by beldmit** [comment]
I'm afraid manually only.
