### ISSUE TITLE
OPENSSL_zalloc

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#6]
The patch to be applied

https://git.openssl.org/gitweb/?p=openssl.git;a=commitdiff;h=b51bce942023325e727ca4225252d06c49d8f2b7#patch33

**Comment by beldmit** [comment]
http://freshbsd.org/commit/openbsd/a859477cc19eea768817f40de8f4366686e51c74

**Comment by amdei** [comment]
There is a patches made in the past to cleanse sensitive data, such as premaster sectes for DH ciphersuites, in memory.
But is missed for GOST ones.

To apply patch use following command in root of current OpenSSL development
tree:

patch -p1 -l -u -b -i prem_cleanup_gost.patch.txt
[prem_cleanup_gost.patch.txt](https://github.com/gost-engine/engine/files/35406/prem_cleanup_gost.patch.txt)

**Comment by beldmit** [comment]
Not actual for openssl upstream.

**Comment by beldmit** [comment]
Not actual.
