### ISSUE TITLE
не совсем правильный путь при "make install"

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#60]
при установке путь до папки с engine выбирается неправильно.
пример, берем CentOS7, ставим на нее openssl-1.1.0, ставим engine ... он видит установленную нами версию openssl, но неправильно формирует путь до папки

```
wget https://www.openssl.org/source/openssl-1.1.0h.tar.gz
tar xf openssl-1.1.0h.tar.gz
cd openssl-1.1.0h
./config shared
make all install_sw
cd ..
git clone https://github.com/gost-engine/engine.git
cd engine
cmake3 .
make all install


#ls /usr/local/lib64/| grep engines
engines-1_1
engines-1.1
# 

```

engines-1.1 - тут хочет видеть openssl
engines-1_1 - сюда кладет инсталятор

если openssl ставится с недефолтным префиксом (как, например, тут https://github.com/gost-engine/engine/pull/59), то магия с определением путей ломается еще сильнее (engine, несмотря на то, что ему передали OPENSSL_ROOT_DIR, все равно ставит в /usr/local)

я (пока) не осилил эту магию, поэтому issue, а не PR

**Comment by beldmit** [comment]
Проверьте, не поможет ли исправление строчки
set(OPENSSL_ENGINES_INSTALL_DIR ${CMAKE_INSTALL_LIBDIR}/engines-${OPENSSL_VERSION_MAJOR}_${OPENSSL_VERSION_MINOR})
в CMakeLists.txt

**Comment by chipitsine** [comment]
хардкодом поменять подчеркивание на точку ?

**Comment by beldmit** [comment]
Для начала да.

Мне вообще не нравится цель install в Makefile, честно говоря. Директорию для покладания engine надо выяснять из openssl, причём родными средствами.

**Comment by chipitsine** [comment]
а есть идея, как эту директорию "выяснить" ?

**Comment by beldmit** [comment]
Для юниксопоодбия - из Configurations/unix-Makefile.tmpl
# $(libdir) is chosen to be compatible with the GNU coding standards
libdir={- file_name_is_absolute($libdir)
          ? $libdir : '$(INSTALLTOP)/$(LIBDIR)' -}
ENGINESDIR=$(libdir)/engines-{- $sover_dirname -}

     our $sover_dirname = $config{shlib_version_number};
     $sover_dirname =~ s|\.|_|g
         if $config{target} =~ /^mingw/;
В смысле, для windows (mingw, MSVC) и для Unix там разные пути.

**Comment by levitte** [comment]
If you want, I might be able to help, but I need to have the issue in English...

**Comment by chipitsine** [comment]
@levitte , we are looking for some "proper" way how cmake-based openssl engine can detect openssl engine path (either via cmake magic or via some openssl magic)

i.e. something like "tell me what is folder of engines" would be nice

it is needed in order to install built engine "so" into that folder

@beldmit told something about "mingw and MSVC are even more different", but I tend to refuse install if such a platform detected :)

**Comment by levitte** [comment]
The command line method would be to run `openssl version -e` and parse the output:

```
: ; openssl version -e
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
```

Otherwise, if you'd rather rely on the libcrypto library only, running this small code snippet does the trick:

``` C
#include <stdio.h>
#include <openssl/crypto.h>

int main()
{
  printf("%s\n", OpenSSL_version(OPENSSL_ENGINES_DIR));
}
```

The output will be exactly the same as `openssl version -e`

**Comment by chipitsine** [comment]
Nice. I think, I can wrap it with cmake

**Comment by candrews** [comment]
This issue can now be closed.
