### ISSUE TITLE
OpenSSL 1.0.2

### ISSUE THREAD

**Issue by Jenstel** [gost-engine/engine#61]
Подскажите, пожалуйста, как собрать на Debian под OpenSSL 1.0.2?

**Comment by beldmit** [comment]
Взять исходники OpenSSL, применить патчи к основному дереву, заменить
директорию ccgost на результат git checkout, собрать OpenSSL.

чт, 21 июн. 2018 г., 8:51 Alex <notifications@github.com>:

**Comment by Jenstel** [comment]
Можно, пожалуйста, поподробнее что нужно сделать?

**Comment by beldmit** [comment]
COMPILING AND INSTALLATION

This engine is a drop-in replacement of the GOST engine included in openssl
1.0.2. The original openssl version does not support GOST2012 algorithms.  To compile
it, you MUST apply the required patches (from the patches/ folder) to the
openssl 1.0.2 source tree and copy all files from the current directory to the
openssl/engines/ccgost folder.  After that you will be able to configure and
build openssl using standard options.

**Comment by Jenstel** [comment]
`# patch -i patches/1.0.2/cipher_modes.diff
can't find file to patch at input line 4
Perhaps you should have used the -p or --strip option?
The text leading up to this was:
--------------------------
|diff -uNr crypto/objects_orig/obj_dat.h crypto/objects/obj_dat.h
|--- crypto/objects_orig/obj_dat.h      2015-10-06 20:43:14.000000000 +0300
|+++ crypto/objects/obj_dat.h   2015-10-06 20:45:53.000000000 +0300
--------------------------
File to patch:
`

**Comment by beldmit** [comment]
1. Вытащите более свежую версию engine.
2. Патчи применются к исходникам OpenSSL.
3. Укажите ключ -p1

**Comment by chipitsine** [comment]
добрый день

1. может удалить папку patches из ветки master, оставить только в ветке openssl_1_0_2 ?
2. @Jenstel , кажется, только вы сможете актуализировать инструкции по установке :)

можете в INSTALL.md посмотреть, как именно стоит добавить вот такую штуку (и для openssl-1.1.0 и выше - будет другая инструкция)
```
wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
tar xf openssl-1.0.2o.tar.gz
openssl-1.0.2o

for p in `ls ../engine/patches/1.0.2/`; do patch -p1 < ../engine/patches/1.0.2/$p; done
```



@beldmit - на что патчи должны накладываться ? я проверил, оно фейлится и на 1.0.2o, и на ветку OpenSSL_1_0_2-stable ...


```
patching file crypto/objects/obj_dat.h
patching file crypto/objects/obj_mac.h
patching file crypto/objects/obj_mac.num
patching file crypto/objects/obj_xref.h
patching file crypto/objects/obj_xref.txt
patching file crypto/objects/objects.txt
patching file crypto/asn1/a_mbstr.c
patching file crypto/asn1/a_strnid.c
patching file crypto/evp/evp_pbe.c
patching file crypto/pkcs12/p12_mutl.c
patching file crypto/cms/cms_sd.c
patching file crypto/pkcs7/pk7_smime.c
patching file crypto/asn1/a_mbstr.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] y
Hunk #1 FAILED at 173.
1 out of 1 hunk FAILED -- saving rejects to file crypto/asn1/a_mbstr.c.rej
patching file crypto/asn1/a_strnid.c
Hunk #1 FAILED at 192.
1 out of 1 hunk FAILED -- saving rejects to file crypto/asn1/a_strnid.c.rej
patching file crypto/cms/cms_sd.c
Reversed (or previously applied) patch detected!  Assume -R? [n] y
Hunk #1 succeeded at 943 (offset 2 lines).
patching file crypto/pkcs7/pk7_smime.c
Reversed (or previously applied) patch detected!  Assume -R? [n] y
```

**Comment by beldmit** [comment]
Судя по этому логу, у вас двойной комплект патчей, старый и новый.

Выпишите engine с нуля и скажите, что в папке patches/

**Comment by beldmit** [comment]
Понял. Я запутался при коммитах. Те патчи, которые без номера в начале, надо удалить. Остальное применять к 1.0.2-stable. Завтра закоммичу удаление лишнего.

**Comment by beldmit** [comment]
Удалил дубликаты патчей. Должно прикладываться.

**Comment by Jenstel** [comment]
Может только у меня так, но теперь папка 'patches' исчезла...

**Comment by beldmit** [comment]
В ветке master и должна была. Переключитесь на сетку openssl_1_0_2

**Comment by chipitsine** [comment]
@Jenstel - я привел примерный код, как переключиться на ветку openssl_1_0_2
поможете это оформить в INSTALL.md ?

**Comment by beldmit** [comment]
Я бы в INSTALL.md это не писал. Максимум оставил бы в README.md указание, что для каждой ветки openssl необходимо брать соответствующую ветку engine и следовать тамошним инструкциям.

**Comment by Jenstel** [comment]
У меня не особо много опыта в работе с Git, подскажите, как в Debian получить ветку openssl_1_0_2 и собрать с ГОСТ2012?

**Comment by beldmit** [comment]
Давайте Вы изучите документацию самостоятельно.

**Comment by batonser** [comment]
Всем доброго дня.
При накладывания патчей столкнулся с такой ошибкой, исходники openssl-1.0.1k
 for p in `ls ../engine/patches/1.0.2/`; do patch -p1 < ../engine/patches/1.0.2/$p; done
patching file crypto/objects/obj_dat.h
patching file crypto/objects/obj_mac.h
patching file crypto/objects/obj_mac.num
patching file crypto/objects/obj_xref.h
patching file crypto/objects/obj_xref.txt
patching file crypto/objects/objects.txt
patching file crypto/asn1/a_mbstr.c
patching file crypto/asn1/a_strnid.c
Hunk #1 FAILED at 193.
1 out of 1 hunk FAILED -- saving rejects to file crypto/asn1/a_strnid.c.rej
patching file crypto/evp/evp_pbe.c
patching file crypto/pkcs12/p12_mutl.c
patching file crypto/cms/cms_sd.c
patching file crypto/pkcs7/pk7_smime.c

**Comment by chipitsine** [comment]
@batonser , это весьма странная идея, начинать обсуждение своей ошибки в чужом (закрытом) треде.
в общем, кажется, что открыть новый баг это почти во всех случаях было бы лучше.

у вас версия openssl-1.0.1k ? для нее вроде бы и не должно работать. предполагается поддержка для 1.0.2

**Comment by batonser** [comment]
> @batonser , это весьма странная идея, начинать обсуждение своей ошибки в чужом (закрытом) треде.
> в общем, кажется, что открыть новый баг это почти во всех случаях было бы лучше.
> 
> у вас версия openssl-1.0.1k ? для нее вроде бы и не должно работать. предполагается поддержка для 1.0.2

Вы правы, не увидел что закрытый тред. я новый создам.
