### ISSUE TITLE
перенос тестов из ветки  object_db в мастер

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#63]
00-engine.t - кажется, этот тест перекрывает собой 'openssl engine | grep GOST', после его включения, наверное, проверку https://github.com/gost-engine/engine/blob/master/.ci/build-check.sh#L11 можно убрать?

абсолютный способ определения пути до библиотеки $ENV{'OPENSSL_ENGINES'} = abs_path("../.libs"); кажется, не очень удобен. может сделать условное присваивание, если переменная не задана, то задать ее таким значением. это не поломает текущее поведение и даст возможность переопределять путь

частично тесты падают
https://travis-ci.org/chipitsine/engine/builds/396454774

надо бы их посмотреть

насчет переноса тестов в мастер, перенесете своими силами? если я буду, то комит пойдет с моим авторством, что не очень правильно.

**Comment by chipitsine** [comment]
думаю, достаточно перенести *.t файлы. и прогонять их утилитой "prove".

**Comment by beldmit** [comment]
@vbwagner, ты ведь их писал? Может, ты и перенесёшь?

**Comment by chipitsine** [comment]
и явное задание https://github.com/gost-engine/engine/blob/master/.ci/build-openssl.sh#L10-L23 , наверное, можно будет выкинуть

**Comment by chipitsine** [comment]
как перенесете, я трависные скрипты адаптирую потом

**Comment by beldmit** [comment]
Перенёс.
