### ISSUE TITLE
не работает тест 04-pkey.t

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#66]
если кто-то понимает, как это должно работать, посмотрите, плиз ?
я (пока) не осилил

**Comment by beldmit** [comment]
Тест содержит массив из приватного ключа, строкового наименования параметров, публичного ключа в PEM-формате и числового представления приватного и публичного ключей. 

Можете вывод теста сюда кинуть?

**Comment by chipitsine** [comment]
https://travis-ci.org/chipitsine/engine/builds/398417544


я пробовал вручную запускать openssl с теми параметрами, которые в тесте, все работает. такое чувство, что что-то с синтаксисом Test::More

**Comment by beldmit** [comment]
Изменился формат вывода. Теперь при выводе private key он не выводит публичный ну и так далее.

**Comment by chipitsine** [comment]
выводит ))

**Comment by beldmit** [comment]
Не воспроизводится.

beldmit@manul$ OPENSSL_ENGINES=`pwd`/bin/ perl test/04-pkey.t 
1..15
ok 1 - Print key pair gost2001:A
ok 2 - Compute public key gost2001:A
ok 3 - Read and print public key gost2001:paramset
ok 4 - Print key pair gost2001:B
ok 5 - Compute public key gost2001:B
ok 6 - Read and print public key gost2001:paramset
ok 7 - Print key pair gost2001:C
ok 8 - Compute public key gost2001:C
ok 9 - Read and print public key gost2001:paramset
ok 10 - Print key pair gost2001:XA
ok 11 - Compute public key gost2001:XA
ok 12 - Read and print public key gost2001:paramset
ok 13 - Print key pair gost2001:XB
ok 14 - Compute public key gost2001:XB
ok 15 - Read and print public key gost2001:paramset
beldmit@manul$ perl -v

This is perl 5, version 24, subversion 1 (v5.24.1) built for x86_64-linux-gnu-thread-multi
(with 81 registered patches, see perl -V for more detail)

**Comment by chipitsine** [comment]
попробовал через perlbrew поднять перл до 5.24

https://travis-ci.org/chipitsine/engine/jobs/398992243

все равно падает

**Comment by chipitsine** [comment]
проверил на ubuntu 14.04 установленной с нуля - тест проходит
