### ISSUE TITLE
Problem with OpenSSL 1.1.0g

### ISSUE THREAD

**Issue by AlexanderVZorin** [gost-engine/engine#69]
I used 0.9 version of OpenSSL with GOST-engine without problems.

Now I explore installation with OpenSSL 1.1.0g ang this gost-engine.

OpenSSL operates OK in many cases (key/csr generation, etc.) but reports about problems at some checks, e.g.:
---------------------------------------------------------------
C:\openssl\bin>openssl engine -t -post list_csps
(dynamic) Dynamic engine loading support
     [ unavailable ]
(capi) CryptoAPI ENGINE
     [ available ]
Available CSPs:
0. Aktiv ruToken CSP v1.0, type 1
1. Crypto-Pro GOST R 34.10-2001 Cryptographic Service Provider, type 75
2. Crypto-Pro GOST R 34.10-2012 Cryptographic Service Provider, type 80
3. Crypto-Pro GOST R 34.10-2012 Strong Cryptographic Service Provider, type 81
4. eToken Base Cryptographic Provider, type 1
5. Microsoft Base Cryptographic Provider v1.0, type 1
6. Microsoft Base DSS and Diffie-Hellman Cryptographic Provider, type 13
7. Microsoft Base DSS Cryptographic Provider, type 3
8. Microsoft Base Smart Card Crypto Provider, type 1
9. Microsoft DH SChannel Cryptographic Provider, type 18
10. Microsoft Enhanced Cryptographic Provider v1.0, type 1
11. Microsoft Enhanced DSS and Diffie-Hellman Cryptographic Provider, type 13
12. Microsoft Enhanced RSA and AES Cryptographic Provider, type 24
13. Microsoft Exchange Cryptographic Provider v1.0, type 5
14. Microsoft RSA SChannel Cryptographic Provider, type 12
15. Microsoft Strong Cryptographic Provider, type 1
[Success]: list_csps
(gost) Reference implementation of GOST engine
     [ available ]
[Failure]: list_csps
7728:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto\engine\eng_ctrl.c:85:
7728:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto\engine\eng_ctrl.c:263:
---------------------------------------------------------------

Engine section is the following:
 #-------------------------------------------------------------------
[engine_section]
capi = capi_config
gost = gost_section
#-------------------------------------------------------------------
[capi_config]
engine_id = capi
dynamic_path = ./engines/capi.dll
#default_algorithms = ALL
init=1
#-------------------------------------------------------------------
[gost_section]
engine_id = gost
dynamic_path = ./engines/gost.dll
default_algorithms = ALL
init = 0
#-------------------------------------------------------------------

If gost=gost_section is commented, I have no problem.
What is a problem and how to solve ?

**Comment by beldmit** [comment]
Gost engine does not support the command list_csps.

пт, 20 июл. 2018 г., 19:25 AlexanderVZorin <notifications@github.com>:
