### ISSUE TITLE
hash

### ISSUE THREAD

**Issue by YuDudysheva** [gost-engine/engine#70]
Gost hash 2012 (both 256 and 512) produces an incorrect result. ( It does not match examples from the standard Gost R 3411 2012).

**Comment by beldmit** [comment]
What branch do you use?

**Comment by YuDudysheva** [comment]
master

**Comment by beldmit** [comment]
Examples from GOST are present in etalon/ folder. Please test using them and switch to openssl_1_1_0 branch.

**Comment by YuDudysheva** [comment]
In openssl_1_1_0 brach everything is ok.

**Comment by beldmit** [comment]
The most common problem is mess with endianess. Could you please send an output of your cmake call?

**Comment by beldmit** [comment]
Not reproduced.
