### ISSUE TITLE
OpenSSL 1.0.2 и GOST2012

### ISSUE THREAD

**Issue by alexanderk23** [gost-engine/engine#71]
Пытаюсь собрать `OpenSSL_1_0_2-stable` с `gost-engine` из ветки `openssl_1_0_2`.
Согласно инструкции накладываю патчи из `engine/patches/1.0.2` и копирую `engine/*` в `engines/ccgost`:

```
$ git clone git@github.com:gost-engine/engine.git
$ cd engine && git checkout openssl_1_0_2
$ cd ../openssl-OpenSSL_1_0_2-stable
$ patch -p1 < ../engine/patches/1.0.2/1.oids.diff
$ patch -p1 < ../engine/patches/1.0.2/2.numeric.diff
$ patch -p1 < ../engine/patches/1.0.2/3.pkcs12.diff
$ patch -p1 < ../engine/patches/1.0.2/4.smimecap.diff
$ cp -rf ../engine/* engines/ccgost/
$ ./config --prefix=/opt/openssl-1.0.2-gost --openssldir=/opt/openssl-1.0.2-gost/ssl -Wl,-rpath,/opt/openssl-1.0.2-gost/lib shared
$ make depend && make -j4 && sudo make install
```

Патчи накладываются без ошибок, сборка проходит нормально. Однако в списке ciphers присутствует только:

```
$ LD_LIBRARY_PATH=/opt/openssl-1.0.2-gost/lib /opt/openssl-1.0.2-gost/bin/openssl ciphers | tr ":" "\n" | grep GOST
GOST2001-GOST89-GOST89
```
Так и должно быть или я что-то делаю не так?

**Comment by beldmit** [comment]
Да, патч, обеспечивающий поддержку TLS я не прикладывал из-за большого объёма.

**Comment by alexanderk23** [comment]
Прошу простить за наглость, но можно ли тогда его заполучить каким-то образом? :)

**Comment by beldmit** [comment]
Ну я бы предпочёл продать Вам коммерческую версию. Но в приницпе, наверное, можно.

**Comment by alexanderk23** [comment]
Конечно, в организацию на продакшн (когда до него дойдёт) по понятным причинам будем брать коммерческую -- тем более, что уже пользуемся решениями Вашей компании. Если можно, забросьте, пожалуйста, на [alexanderk23@ya.ru](alexanderk23@ya.ru). Спасибо.

**Comment by Jenstel** [comment]
Я бы тоже купил готовый deb-пакет OpenSSL 1.0.2 с поддержкой ГОСТ2001 и ГОСТ2012

**Comment by alexanderk23** [comment]
Так [вот же он](http://www.cryptocom.ru/products/cryptopacket.html).

**Comment by beldmit** [comment]
Прислеть на адрес из профиля?

**Comment by Jenstel** [comment]
Да я бы прикупил готовую либу ГОСТ2012 под 1.0.2, взамен родной, да и все...

**Comment by beldmit** [comment]
Напишите на support@cryptocom.ru

**Comment by Jenstel** [comment]
Я написал еще утром, не отвечает пока (Igor Ustinov)

**Comment by AlexeyZaharov** [comment]
Sorry for reopening issue, but i don`t understand how I can get patch which allows support TLS with GOST2012 ciphers?

**Comment by AlexeyZaharov** [comment]
Thank you for answer
