### ISSUE TITLE
Слинковать в статическую библиотеку вместе с OpenSSL

### ISSUE THREAD

**Issue by kolayuk** [gost-engine/engine#73]
Привет! Я правильно понимаю что тк OpenSSL перешел в 1.1.0 на динамическую загрузку модулей то слинковать это все (OpenSSL + ГОСТ) в одну статическую библиотеку (*.a) больше невозможно? Так как при развертывании есть сложности с развертыванием дополнительных файлов, хочется один большой статически слинкованный бинарник.
На выходе хочется получить OpenSSL для статической сборки сразу с gost-engine (как было в версиях 1.0.1 при сборке с no-shared)

**Comment by beldmit** [comment]
У меня это и раньше не получалось.
