### ISSUE TITLE
Идентификаторы параметров для ГОСТ-2012-256

### ISSUE THREAD

**Issue by IamUndef** [gost-engine/engine#74]
Подскажите, почему тут так?

https://github.com/gost-engine/engine/blob/ae3020da5ffba97df84a283eacc2a7fb41471c13/gost_params.c#L90

У КриптоПро идентификаторы параметров для ГОСТ-2012-256 отличаются от ГОСТ-2001.

https://cpdn.cryptopro.ru/content/csp40/html/group___pro_c_s_p_ex_CP_PARAM_OIDS.html

**Comment by beldmit** [comment]
Сами параметры совпадают. Отличаются идентификаторы, причём, как мне помнится, не изначально, а с какого-то момента.
