### ISSUE TITLE
openssl dgst using wrong digest algo

### ISSUE THREAD

**Issue by lumag** [gost-engine/engine#79]
`openssl dgst -md_gost94` results in GOST R 34.11-2012 digest calculation (using OpenSSL 1.1.0i + engine from `openssl_1_1_0` branch):

```
$ echo -n |  openssl dgst -engine gost -md_gost94
engine "gost" set.
(stdin)= 3f539a213e97c802cc229d474c6aa32a825a360b2a933a949fd925208d9ce1bb
```

**Comment by beldmit** [comment]
Well, example you've provided is about md_gost12_256

**Comment by lumag** [comment]
@beldmit fixed. Wrong c&p.

**Comment by beldmit** [comment]
Well...

beldmit@manul$ echo -n | OPENSSL_ENGINES=`pwd`/bin openssl dgst -engine gost -md_gost94
engine "gost" set.
(stdin)= 3f25bc1fbbce27ca10fb1958f319473ae7e17482c3b53ecf47a7e2de8aabe4c8
beldmit@manul$ echo -n | OPENSSL_ENGINES=`pwd`/bin openssl dgst -engine gost -md_gost12_256
engine "gost" set.
(stdin)= 3f539a213e97c802cc229d474c6aa32a825a360b2a933a949fd925208d9ce1bb

**Comment by lumag** [comment]
Mea culpa, closing now.
