### ISSUE TITLE
билды по расписанию для ветки openssl_1_1_0

### ISSUE THREAD

**Issue by chipitsine** [gost-engine/engine#81]
добрый день!

добавьте, пожалуйста в travis-ci ежедневные билды для ветки openssl_1_1_0

**Comment by beldmit** [comment]
Это куда прописать?

**Comment by chipitsine** [comment]
![screenshot from 2018-08-30 10-43-01](https://user-images.githubusercontent.com/2217296/44831807-a2dc5300-ac41-11e8-821c-3fbdb2f03cd8.png)

**Comment by beldmit** [comment]
Ага, понял, вроде добавил.
