### ISSUE TITLE
Parameter set for GOST R 34.10-2012 with 256 bit modulus

### ISSUE THREAD

**Issue by HeavyDutySoul** [gost-engine/engine#84]
Приветствую, при создании сертификата с алгоритмом подписи ГОСТ Р 34.10-2012 для ключей длины 256 бит, параметры кривой публичного ключа в сертфикате имеют вид id-GostR3410-2001-CryptoPro-A-ParamSet. Насколько я понимаю должно быть как-то так GOST R 34.10-2012 (256 bit) ParamSet A. Пробовал с кодом из ветки master и 1.1.0.

**Comment by beldmit** [comment]
Для 1.1.0 это так и останется скорее всего. 
Для master с удовольствием приму патч или подождите, пока руки дойдут. 
Уверенности в том, какой OID сейчас должен писаться, у меня нет.

**Comment by HeavyDutySoul** [comment]
Печально, сам не погроммист, очевидно 1.2.643.7.1.1.1.1, будем ждать.

**Comment by vt-alt** [comment]
Философский вопрос - сейчас 256-битные параметры CryptoPro-2001 в `paramset` называются `A`, `B`, `C` - как назвать параметры tc26-2012, которые тоже `A`, `B`, `C`, `D`?

**Comment by beldmit** [comment]
А A,B,C там не эквивалентны?

**Comment by vt-alt** [comment]
Эквивалентны другим буквам.

**Comment by beldmit** [comment]
Тогда я бы делал TCA, TCB...

**Comment by vt-alt** [comment]
> Эквивалентны другим буквам.

Точнее, это даже не важно так как в сертификате должны быть другие OIDы, которые н еэквивалентны.

> Тогда я бы делал TCA, TCB...

Вторая идея, для tc26 OIDов использовать маленкие буквы a, b, c, d,

**Comment by beldmit** [comment]
Не, это точно плохо.

**Comment by vt-alt** [comment]
Может две буквы - TA, TB, TC, TD? Или AA, BB, CC, DD?

**Comment by beldmit** [comment]
TC - понятно. Technical Committee. А просто T - хрен знает что.

**Comment by vt-alt** [comment]
```bash
$ openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:A | openssl asn1parse -i
    0:d=0  hl=2 l=  70 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim:  INTEGER           :00
    5:d=1  hl=2 l=  31 cons:  SEQUENCE
    7:d=2  hl=2 l=   8 prim:   OBJECT            :GOST R 34.10-2012 with 256 bit modulus
   17:d=2  hl=2 l=  19 cons:   SEQUENCE
   19:d=3  hl=2 l=   7 prim:    OBJECT            :id-GostR3410-2001-CryptoPro-A-ParamSet
   28:d=3  hl=2 l=   8 prim:    OBJECT            :GOST R 34.11-2012 with 256 bit hash
   38:d=1  hl=2 l=  32 prim:  OCTET STRING      [HEX DUMP]:8B8F3D47A2CE86607AFC7881407CCFF61A93B9172C84187F6512CB5832D92A3E

$ openssl genpkey -algorithm gost2012_256 -pkeyopt paramset:TCA | openssl asn1parse -i
    0:d=0  hl=2 l=  62 cons: SEQUENCE
    2:d=1  hl=2 l=   1 prim:  INTEGER           :00
    5:d=1  hl=2 l=  23 cons:  SEQUENCE
    7:d=2  hl=2 l=   8 prim:   OBJECT            :GOST R 34.10-2012 with 256 bit modulus
   17:d=2  hl=2 l=  11 cons:   SEQUENCE
   19:d=3  hl=2 l=   9 prim:    OBJECT            :GOST R 34.10-2012 (256 bit) ParamSet A
   30:d=1  hl=2 l=  32 prim:  OCTET STRING      [HEX DUMP]:71CDC29C61D6AA96F2E6D8DFF19137C007E2EEE672950C9D9EF88D11A5701702
```
