### ISSUE TITLE
Console message "GOST engine already loaded"

### ISSUE THREAD

**Issue by shadz3rg** [gost-engine/engine#89]
Ubuntu 18.04
OpenSSL 1.1.0g
Установил и настроил по мануалу, openssl s_client и консольный curl 7.58 работают как надо.
 
Wget 1.19.4 выдает перед каждым вызовом "GOST engine already loaded"
```
root@home_server:/home/atari# wget https://curl.haxx.se/download/curl-7.61.1.tar.gz
--2018-10-06 12:30:56--  https://curl.haxx.se/download/curl-7.61.1.tar.gz
GOST engine already loaded
Resolving curl.haxx.se (curl.haxx.se)... 151.101.38.49, 2a04:4e42:9::561
Connecting to curl.haxx.se (curl.haxx.se)|151.101.38.49|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3986062 (3.8M) [application/x-gzip]
Saving to: ‘curl-7.61.1.tar.gz.2’

curl-7.61.1.tar.gz.2                     100%[================================================================================>]   3.80M  2.19MB/s    in 1.7s

2018-10-06 12:30:58 (2.19 MB/s) - ‘curl-7.61.1.tar.gz.2’ saved [3986062/3986062]
```

PHP 7.2.10 + OpenSSL = все ОК
```
root@home_server:/home/atari# php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

PHP 7.2.10 + OpenSSL + Libcurl = То же сообщение
```
root@home_server:/home/atari# php -v
GOST engine already loaded
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
```

Правильно я понимаю что вывод на функционал не влияет и можно его просто закомментировать? Или можно подобные сообщения как то отключить через конфиг (уровень verbose или что то в этом духе)?

**Comment by beldmit** [comment]
Это сообщение означает, что вы грузите engine дважды, что не очень правильно. Один раз из Openssl и один раз из curl во втором случае, и непонятно откуда в первом. Если всё работает, то ок.

А как вы настраивали и собирали curl? У меня сходу не взлетел, хотя и с 1.0.2

**Comment by shadz3rg** [comment]
@beldmit был уверен что проблема кроется в libcurl который подключается к PHP, даже хотел к ним тикет написать, пока не увидел то же сообщение в Wget

В данном случае curl, wget, openssl - все шло из коробки с Убунтой, версии есть в первом посте. Система вообще чистая, отдельно ставил только PHP.

**Comment by xoyteam** [comment]
Используйте вызов openss с указанием engine:
openssl -engine gost ciphers
и удалите из конфига информацию о ручной подгрузке библиотеки gost engine.
