### ISSUE TITLE
Add interface to assign UZ to key individually.

### ISSUE THREAD

**Issue by amdei** [gost-engine/engine#9]
Now UZ specified globally.
Need ability to override key parameters for each key separately.

This is required, for example, for IKE in GOST IPSec.

**Comment by beldmit** [comment]
Waiting for https://github.com/openssl/openssl/pull/418.

**Comment by amdei** [comment]
Now quite clear from the discussion in #418: will EVP_CTRL_SET_SBOX accept integer, representing SBOX code, or char*, representing SBOX itself?

From general point of view first solution lokks better.

**Comment by beldmit** [comment]
I think that char* representing OID.

**Comment by amdei** [comment]
May be specifying NID, as a named constant, would be more straightforward from user point of view?
OID's is not really human-understandable.

**Comment by beldmit** [comment]
Currently the global default value is specified via OID. So I decided to provide the similar interface.
As the patch is not currently accepted by the Openssl team, it may change.

**Comment by mattcaswell** [comment]
openssl/openssl#418 has now been merged.

**Comment by beldmit** [comment]
Fixed for 1.1.0 in commit 83cf06d40ed3d4dc1d97c8dc6bb19e295e31e2ac.
