### ISSUE TITLE
Engine errors     

### ISSUE THREAD

**Issue by se-sve** [gost-engine/engine#90]
Здравствуйте! 
Mint 18.2

Установил engine, все алгоритмы работают корректно (как при использовании исполняемого файла openssl , так и при использовании API), но при выполнении некоторых команд (в частности: openssl -c engine, openssl speed -evp gost89) после вывода результата выполнения этих команд в конце выводится ошибка следующего содержания:

139674310013376:error:260AC089:engine routines:int_ctrl_helper:invalid cmd name:crypto/engine/eng_ctrl.c:87:
139674310013376:error:260AB089:engine routines:ENGINE_ctrl_cmd_string:invalid cmd name:crypto/engine/eng_ctrl.c:255:
139674310013376:error:260BC066:engine routines:int_engine_configure:engine configuration error:crypto/engine/eng_cnf.c:141:section=gost_section, name=HOME, value=.
139674310013376:error:0E07606D:configuration file routines:module_run:module initialization error:crypto/conf/conf_mod.c:174:module=engines, value=engine_section, retcode=-1

**Comment by beldmit** [comment]
Покажите свой конфигурационный файл.

**Comment by se-sve** [comment]
Та часть, которую я добавлял

openssl_conf = openssl_def
[openssl_def]
engines = engine_section

[engine_section]
gost = gost_section

[gost_section]
engine_id = gost
dynamic_path = /usr/lib/engines-1.1/gost.so
default_algorithms = ALL
CRYPT_PARAMS = id-tc26-gost-28147-param-Z

**Comment by beldmit** [comment]
Лучше полный. 
Не исключено, что строка 
openssl_conf = openssl_def должна идти первой.

**Comment by se-sve** [comment]
[openssl.cnf.txt](https://github.com/gost-engine/engine/files/2488716/openssl.cnf.txt)

**Comment by se-sve** [comment]
Виноват! спасибо огромное за помощь!
