### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by candrews** [gost-engine/engine#91]
Can you please create a new release?

I'm specifically interested in the new release having the CMake improvements that are in `master` that are absent in the last release, https://github.com/gost-engine/engine/releases/tag/v1.1.0.3 - but the rest of the improvements would be great to have as well :)

Thanks!

**Comment by candrews** [comment]
If you can please ensure that all tests pass before making the release, that would be really nice too: https://github.com/gost-engine/engine/issues/92

**Comment by beldmit** [comment]
I currently do not have plans to make a new release until we have stabilized new specs for X.509, CMS etc or bug occurs.

**Comment by candrews** [comment]
If you make a release now (since #94 is in), it'll be much easier for downstreams (such as Linux distros) to include gost-engine :angel:

**Comment by beldmit** [comment]
Well, gost-engine is already included in Fedora and Debian...

**Comment by beldmit** [comment]
I have plans to create a new release for the 1.1.1 branch.

**Comment by bgermann** [comment]
3.0.0 was released. so this can be closed.
