### ISSUE TITLE
Test failure in master

### ISSUE THREAD

**Issue by candrews** [gost-engine/engine#92]
Currently, the tests are failing. LastTest.log: https://pastebin.com/Tmw6LsiQ
I'm using current master https://github.com/gost-engine/engine/commit/cfcac4f8ac54927d04f262bbdf97858f04a70303 and OpenSSL 1.1.1.

**Comment by beldmit** [comment]
It looks like your setup is incomplete. Travis tests are passing, and it makes sense to look not through the high-level log but to the log of concrete Perl scripts.

**Comment by candrews** [comment]
I'm a Gentoo developer looking to package gost-engine for that distribution. I'm hoping we can figure this out so I can do so :)

What information can I provide that would help track down this issue?

Here's the build.log which includes all the commands run and output:  https://pastebin.com/iuAULrGT

In short, I'm `cmake` to build it then running `ctest -j 5 --test-load 999` which is pretty standard

**Comment by candrews** [comment]
In `master`, CMake calls perl which does that, see https://github.com/gost-engine/engine/blob/cfcac4f8ac54927d04f262bbdf97858f04a70303/CMakeLists.txt#L131

I think .travis.yml should be updated to run tests using cmake - here's a PR for that: https://github.com/gost-engine/engine/pull/93

**Comment by candrews** [comment]
The problem is that the tests don't run with the gost engine enabled when an out of source build is performed.
