### ISSUE TITLE
Legacy PK wrap is invalid

### ISSUE THREAD

**Issue by Hiller** [gost-engine/engine#97]
When using LEGACY_PK_WRAP set, private key is wrapped incorrect. It should be wrapped into ASN1_Integer instead of ASN1_string. 
So correct way should be like this
```C++
ASN1_INTEGER *octet = NULL;
octet = BN_to_ASN1_INTEGER(gost_get0_priv_key(pk), octet);
int priv_len = 0;
unsigned char *priv_buf = NULL;
priv_len = i2d_ASN1_INTEGER(octet, &priv_buf);
ASN1_INTEGER_free(octet);
		
OPENSSL_free(buf);
return PKCS8_pkey_set0(p8, algobj, 0, V_ASN1_SEQUENCE, params,
                               priv_buf, priv_len);
````
Это вроде как известно ))

**Comment by beldmit** [comment]
Nyet. (C)

There were more than one legacy variants of GOST private keys. This one is the most obsoleted and I do not know any software supporting only this variant of wrap.
