### ISSUE TITLE
Raw private/public keys to be supported

### ISSUE THREAD

**Issue by beldmit** [gost-engine/engine#99]
It's useful to provide methods setting/getting raw private/public keys for GOST ameths.

**Comment by vt-alt** [comment]
Это про `EVP_PKEY_new_raw_public_key` или что-то другое?

**Comment by beldmit** [comment]
Вроде да.

**Comment by beldmit** [comment]
Я вот тоже пока не понимаю. Но можно задокументировать, что порядок байт как пишут в сертификатах, и на этом успокоиться. 

Про параметры - ну можно требовать, чтобы они уже были установлены,  а иначе возвращать какой-нибудь  bad order.

**Comment by vt-alt** [comment]
Они не могут быть уже установлены, так как это альтернатива `EVP_PKEY_new`, только ещё сразу можно задать ключ. Это первый вызов создающий EVP_PKEY определенного типа, а в типе нет указания на кривую.

**Comment by vt-alt** [comment]
Интересно, можно ли схитрить и передать в `type` не `nid` алгоритма, а сразу `nid` параметра. (Не факт, что такое вообще сработает, кроме того, что это странно.)

**Comment by beldmit** [comment]
> Интересно, можно ли схитрить и передать в `type` не `nid` алгоритма, а сразу `nid` параметра. (Не факт, что такое вообще сработает, кроме того, что это странно.)

Не, это хак, даже если сработает.

**Comment by vt-alt** [comment]
Для `EVP_PKEY_EC` `set_pub_key` и `set_priv_key` не определены (в `crypto/ec/ec_ameth.c`). В мане вообще написано _"The value should be a NID for a public key algorithm that supports raw private keys, i.e. one of EVP_PKEY_HMAC, EVP_PKEY_POLY1305, EVP_PKEY_SIPHASH, EVP_PKEY_X25519, EVP_PKEY_ED25519, EVP_PKEY_X448 or EVP_PKEY_ED448."_ То есть ожидается, что далеко не все алгоритмы это поддерживают. Пока мне кажется, что не получится это реализовать.

**Comment by beldmit** [comment]
Да, пожалуй.

**Comment by beldmit** [comment]
Давай похороним тогда эту идею.

**Comment by vt-alt** [comment]
Ещё можно определять какой кривой принадлежит точка публичного ключа.

> Давай похороним тогда эту идею.

Хм. Ок. Но `ctrl` для установки ключа бы не помешал. Сейчас в тестах приходится вручную создавать `EC_KEY` и вызывать `fill_GOST_EC_params`. Если бы можно было делать просто два `ctrl` вызова (для установки параметров кривой и ключа) было бы удобнее.

**Comment by beldmit** [comment]
Вот этот вариант мне не очень нравится, потому что тут работа с нестандартными (до PKCS#8) форматами ключей.

**Comment by vt-alt** [comment]
В примере речь про публичный ключ. (С приватными не разбирался, он мне не был нужен в raw форме). На публичный ключ мы повлиять не можем, так как он определен нашими стандартами странным образом. Если бы `i2o_ECPublicKey()` работала из коробки правильно для гостовых ключей, то кое-какой софт, которому это нужно только для определения keyid по приватному ключу, чтоб знать какой сертификат ему соответствует), можно было бы даже не править (например `evmctl`). А значит не слать им патчей со словом Gost, что плюс.

**Comment by vt-alt** [comment]
> Если бы `i2o_ECPublicKey()` работала из коробки правильно для гостовых ключей, то кое-какой софт, которому это нужно только для определения keyid по приватному ключу, чтоб знать какой сертификат ему соответствует), можно было бы даже не править (например `evmctl`). А значит не слать им патчей со словом Gost, что плюс.

Хотя, я придумал как это обойти, в данном конкретном случае. Вместо того, чтоб различать тип ключа и для гостовых юзать `X509_PUBKEY_set`+`X509_PUBKEY_get0_param`, а для остальных `i2o_ECPublicKey`, я решил всегда юзать `X509_PUBKEY_*`, так как он и для не гостовых ключей дает правильный результат (проверил на RSA и ECDSA). А значит, упоминание Gost из патчей можно убрать.
